// Plate: Compiler. Structure only; per-component entries live in details*.js.
ATLAS.register({
  slug: "compiler",
  title: "Compiler",
  lede: "Every component of an optimizing ahead-of-time compiler for a general-purpose language, arranged by layer. A small teaching compiler keeps a parser, a checker and a simple code generator; a production one has all of it.",
  ground: ["Target machine", "Operating system", "Linker", "Runtime library", "Build system"],
  crossIntro: "Some properties belong to no single pass. Whether the same input always yields the same bytes, how fast compilation is, how helpful errors are, what can be redone incrementally, what the language promises about undefined behavior, and how easily a new target is added all have to be designed in from the start, because every stage either preserves them or breaks them.",
  cross: [
    { id: "determinism-of-output", n: "Determinism of output" },
    { id: "compile-time-performance", n: "Compile-time performance" },
    { id: "diagnostics-quality", n: "Diagnostics quality" },
    { id: "incrementality", n: "Incrementality" },
    { id: "undefined-behavior-semantics", n: "Undefined behavior semantics" },
    { id: "retargetability", n: "Retargetability" },
  ],
  bands: [
    { label: "Tooling & drivers", groups: ["drv", "bld", "ide"],
      intro: "What people and build systems actually touch: the command that starts a compile, the machinery that avoids repeating work, and the services that turn the compiler's knowledge into editor feedback." },
    { label: "Front end", groups: ["src", "parse", "sema"],
      intro: "Reads source text and decides what the program means. Output is a fully checked, typed tree. Everything here is specific to the source language and knows nothing about the target machine." },
    { label: "Middle end", groups: ["ir", "ana", "opt"],
      intro: "Language-neutral and machine-neutral. Programs are held in an intermediate form that is easy to analyze, and a pipeline of passes makes them faster and smaller without changing what they do." },
    { label: "Back end", groups: ["cg", "emit"],
      intro: "Commits to one target machine: chooses instructions and registers, lays out stack frames, then writes object files with the symbol, relocation, debug and unwind data a linker and debugger need." },
    { label: "Runtime & verification", groups: ["rt", "test"],
      intro: "Code that ships with or is injected into the output, and the machinery that keeps the compiler itself trustworthy. Optimizers are large, subtle programs, so testing is a component, not an afterthought." },
    { label: "Shared infrastructure", groups: ["found"],
      intro: "General-purpose building blocks used by every stage: allocators, interned strings, uniqued objects, a task scheduler, a file abstraction and exact arithmetic. Their performance sets the compiler's speed floor." },
  ],
  groups: {
    drv: { title: "Driver & command line", color: 1,
      about: "The driver is the compiler's main program. It interprets options, picks a target, runs each stage as a function call or a subprocess, and finally calls the linker. Users judge a compiler first by how this layer behaves.",
      items: [
        { id: "command-line-parsing", n: "Command-line parsing" },
        { id: "option-model", n: "Option & flag model" },
        { id: "target-selection", n: "Target & toolchain selection" },
        { id: "stage-orchestration", n: "Stage orchestration" },
        { id: "linker-invocation", n: "Linker invocation" },
      ] },
    bld: { title: "Build integration & caching", color: 2,
      about: "Real projects compile thousands of files, mostly unchanged since the last run. This group lets a build system skip, share or distribute work safely, which usually matters more to developers than raw compile speed.",
      items: [
        { id: "dependency-files", n: "Dependency files" },
        { id: "incremental-compilation", n: "Incremental compilation" },
        { id: "compilation-cache", n: "Compilation cache" },
        { id: "module-interfaces", n: "Module interfaces" },
        { id: "distributed-compilation", n: "Distributed compilation" },
      ] },
    ide: { title: "Diagnostics & editor services", color: 3,
      about: "Compilers talk to people through diagnostics, and increasingly through editors. The same front end that rejects a program must also answer 'what is at this cursor?' on code that is half typed and wrong.",
      items: [
        { id: "diagnostic-engine", n: "Diagnostic engine" },
        { id: "message-rendering", n: "Message rendering" },
        { id: "fix-it-hints", n: "Fix-it suggestions" },
        { id: "warning-controls", n: "Warning controls" },
        { id: "language-server", n: "Language server" },
        { id: "demand-driven-queries", n: "Demand-driven queries" },
      ] },
    src: { title: "Source management & preprocessing", color: 4,
      about: "Before any parsing, the compiler must find, load and track source text. Locations assigned here travel through every later stage so that errors and debug information can point back at the author's code.",
      items: [
        { id: "source-file-manager", n: "Source file manager" },
        { id: "source-locations", n: "Source locations & spans" },
        { id: "preprocessor", n: "Preprocessor" },
        { id: "macro-expansion", n: "Macro expansion" },
        { id: "import-resolution", n: "Import & include resolution" },
      ] },
    parse: { title: "Lexing & parsing", color: 5,
      about: "Turns characters into tokens and tokens into a tree. The hard part is not accepting valid programs but handling invalid ones: a parser that stops at the first error is nearly useless in an editor.",
      items: [
        { id: "lexer", n: "Lexer" },
        { id: "parser", n: "Parser" },
        { id: "ambiguity-resolution", n: "Ambiguity resolution" },
        { id: "ast", n: "Abstract syntax tree" },
        { id: "error-recovery", n: "Parse error recovery" },
        { id: "lossless-syntax-tree", n: "Lossless syntax tree" },
      ] },
    sema: { title: "Semantic analysis", color: 6,
      about: "Gives the tree meaning: which declaration each name refers to, what type each expression has, and whether the program obeys the language's rules. This is usually the largest and most intricate part of a front end.",
      items: [
        { id: "scope-and-symbol-tables", n: "Scopes & symbol tables" },
        { id: "name-resolution", n: "Name resolution" },
        { id: "type-representation", n: "Type representation" },
        { id: "type-checker", n: "Type checker" },
        { id: "type-inference", n: "Type inference" },
        { id: "overload-and-trait-resolution", n: "Overload & trait resolution" },
        { id: "generics-and-monomorphization", n: "Generics & monomorphization" },
        { id: "constant-evaluation", n: "Compile-time evaluation" },
        { id: "flow-checks", n: "Definite assignment checks" },
        { id: "desugaring", n: "Desugaring" },
      ] },
    ir: { title: "Intermediate representation", color: 7,
      about: "The program's form between source and machine. Good IR design makes analyses cheap and transformations local. Most compilers use several levels, from close to the source down to close to the target.",
      items: [
        { id: "high-level-ir", n: "High-level IR" },
        { id: "ir-lowering", n: "Lowering to IR" },
        { id: "ssa-form", n: "SSA form" },
        { id: "control-flow-graph", n: "Control-flow graph" },
        { id: "mid-level-ir", n: "Mid-level IR" },
        { id: "machine-ir", n: "Machine IR" },
        { id: "ir-verifier", n: "IR verifier" },
      ] },
    ana: { title: "Program analyses", color: 8,
      about: "Optimizations are only legal when analyses prove their preconditions. Analyses compute facts such as who dominates whom, what may alias, and which values are live, and must be recomputed or updated when passes change the code.",
      items: [
        { id: "dominators-and-loops", n: "Dominators & loop detection" },
        { id: "alias-analysis", n: "Alias analysis" },
        { id: "dataflow-framework", n: "Data-flow framework" },
        { id: "call-graph", n: "Call graph" },
        { id: "liveness-analysis", n: "Liveness analysis" },
        { id: "induction-and-trip-counts", n: "Induction & trip counts" },
        { id: "escape-analysis", n: "Escape & purity analysis" },
        { id: "analysis-invalidation", n: "Analysis caching & invalidation" },
      ] },
    opt: { title: "Optimization passes", color: 9,
      about: "Transformations that preserve behavior but cut time or size. Passes are ordered into a pipeline whose sequence matters: inlining exposes constants, constants expose dead code, dead code shrinks loops. Quality comes from the interaction, not any one pass.",
      items: [
        { id: "pass-manager", n: "Pass manager" },
        { id: "inlining", n: "Inlining" },
        { id: "constant-propagation", n: "Constant propagation & folding" },
        { id: "dead-code-elimination", n: "Dead code elimination" },
        { id: "redundancy-elimination", n: "Redundancy elimination" },
        { id: "peephole-simplification", n: "Peephole simplification" },
        { id: "scalar-replacement", n: "Scalar replacement" },
        { id: "loop-invariant-motion", n: "Loop-invariant code motion" },
        { id: "loop-unrolling", n: "Loop unrolling" },
        { id: "vectorization", n: "Vectorization" },
        { id: "devirtualization", n: "Devirtualization" },
        { id: "interprocedural-opt", n: "Interprocedural optimization" },
        { id: "link-time-optimization", n: "Link-time optimization", },
      ] },
    cg: { title: "Code generation", color: 10,
      about: "Maps target-independent IR onto one machine's instructions, registers and calling rules. Each decision here, from instruction choice to spill placement, trades code quality against compile time.",
      items: [
        { id: "instruction-selection", n: "Instruction selection" },
        { id: "legalization", n: "Legalization" },
        { id: "register-allocation", n: "Register allocation" },
        { id: "instruction-scheduling", n: "Instruction scheduling" },
        { id: "calling-conventions", n: "Calling conventions" },
        { id: "stack-frame-layout", n: "Stack frame layout" },
        { id: "block-placement", n: "Block placement, relaxation" },
        { id: "target-description", n: "Target description" },
      ] },
    emit: { title: "Emission & object output", color: 11,
      about: "Turns chosen instructions into the bytes and tables a linker, loader and debugger consume. Mistakes here rarely crash the compiler; they produce programs that link but misbehave, or debuggers that lie.",
      items: [
        { id: "assembly-printer", n: "Assembly printer" },
        { id: "machine-code-encoder", n: "Machine code encoder" },
        { id: "object-file-writer", n: "Object file writer" },
        { id: "relocations", n: "Relocations" },
        { id: "symbols-and-linkage", n: "Symbols & linkage" },
        { id: "section-layout", n: "Section & data layout" },
        { id: "debug-info", n: "Debug information" },
        { id: "unwind-info", n: "Unwind & exception tables" },
      ] },
    rt: { title: "Runtime support & instrumentation", color: 12,
      about: "Output code does not run alone. Startup code, helper routines and instrumentation hooks are supplied or injected by the compiler, and must agree exactly with what the code generator assumes.",
      items: [
        { id: "startup-code", n: "Startup & shutdown code" },
        { id: "runtime-library", n: "Compiler runtime library" },
        { id: "intrinsics", n: "Intrinsics & builtins" },
        { id: "sanitizers", n: "Sanitizer instrumentation" },
        { id: "profile-guided-optimization", n: "Profile-guided optimization" },
        { id: "coverage-instrumentation", n: "Coverage instrumentation" },
      ] },
    test: { title: "Testing & verification", color: 13,
      about: "A miscompile silently corrupts every program it touches, so compiler testing is unusually heavy: huge regression suites, generated programs, cross-checking between implementations, and the compiler building itself.",
      items: [
        { id: "regression-suites", n: "Regression suites" },
        { id: "conformance-suite", n: "Conformance suite" },
        { id: "fuzzing", n: "Fuzzing" },
        { id: "differential-testing", n: "Differential testing" },
        { id: "test-case-reduction", n: "Test-case reduction" },
        { id: "bootstrapping", n: "Bootstrapping" },
        { id: "compile-time-benchmarks", n: "Compile-time benchmarks" },
      ] },
    found: { title: "Compiler infrastructure", color: 14,
      about: "Plain data-structure and system plumbing, not compiler theory. Compilers allocate millions of small, short-lived objects and compare names constantly, so these primitives decide how fast the whole tool runs.",
      items: [
        { id: "arena-allocation", n: "Arena allocation" },
        { id: "string-interning", n: "String interning" },
        { id: "uniquing", n: "Type & constant uniquing" },
        { id: "parallel-task-runtime", n: "Parallel task runtime" },
        { id: "virtual-file-system", n: "Virtual file system" },
        { id: "arbitrary-precision", n: "Arbitrary-precision arithmetic" },
      ] },
  },
});
