// Plate: Relational database. Structure only; per-component entries live in details*.js.
ATLAS.register({
  slug: "relational-database",
  title: "Relational Database",
  lede: "Every component of a full client-server relational database, arranged by layer: from the wire protocol and SQL planner down to pages on disk, with the logging, replication and operational machinery that keeps committed data safe.",
  ground: ["Operating system and file system","Block storage and its cache","Network stack","Memory and CPU cores","Clock and time source"],
  crossIntro: "Some guarantees belong to no single component. What a commit promises after a crash, what concurrent readers may observe, how memory is divided, what an operator can see, and whether old data and clients keep working after an upgrade are decided once and then honored by every layer below.",
  cross: [
    { id: "durability-guarantees", n: "Durability guarantees" },
    { id: "isolation-semantics", n: "Isolation semantics" },
    { id: "memory-management", n: "Memory management" },
    { id: "observability", n: "Observability" },
    { id: "upgrade-compatibility", n: "Upgrade compatibility" },
    { id: "fault-tolerance", n: "Fault tolerance" },
  ],
  bands: [
    { label: "Operations & governance", groups: ["ops","sec"],
      intro: "What surrounds the running server: how it is configured, watched and maintained, and how access to data is controlled, encrypted and audited." },
    { label: "Client interface", groups: ["conn"],
      intro: "How applications reach the server: the wire protocol, the processes or threads that serve each connection, who is allowed in, and what state a session carries between statements." },
    { label: "Query language & planning", groups: ["parse","opt"],
      intro: "Where text becomes a plan. The front end gives SQL its meaning, and the optimizer picks, from many equivalent plans, the one it estimates to be cheapest." },
    { label: "Execution & schema", groups: ["exec","cat","prog"],
      intro: "Where plans run and the rules of the data live: the operators that produce rows, the catalog that describes every object, and the constraints and code that run inside the database." },
    { label: "Transactions & durability", groups: ["txn","wal"],
      intro: "The machinery behind atomic, isolated and durable work: versioned rows and locks let transactions overlap safely, and the log lets the server recover exactly what was committed." },
    { label: "Availability & recovery", groups: ["repl","backup"],
      intro: "How the log leaves the machine: copied to replicas for failover and scale, and archived so the database can be rebuilt at any past moment." },
    { label: "Storage engine", groups: ["buf","acc","store"],
      intro: "The foundation that holds the data: fixed-size pages on disk, a cache that decides which pages live in memory, and the indexes that find rows without reading everything." },
  ],
  groups: {
    ops: { title: "Operations & maintenance", color: 13,
      about: "A database is a long-lived service that tunes and repairs itself in the background. Settings, counters, logs and scheduled maintenance give operators control, and expose what the engine would otherwise keep to itself.",
      items: [
        { id: "configuration-system", n: "Configuration system" },
        { id: "runtime-statistics-views", n: "Runtime statistics views" },
        { id: "slow-query-logging", n: "Slow query logging" },
        { id: "background-workers", n: "Background workers" },
        { id: "maintenance-scheduler", n: "Maintenance scheduler" },
        { id: "resource-governance", n: "Resource governance" },
      ] },
    sec: { title: "Security", color: 14,
      about: "Defense in depth: who may connect, what each role may do, which rows each user may see, and whether data is protected on the wire and on disk. Audit records show afterward who did what.",
      items: [
        { id: "roles-and-privileges", n: "Roles & privileges" },
        { id: "row-level-security", n: "Row-level security" },
        { id: "encryption-in-transit", n: "Encryption in transit" },
        { id: "encryption-at-rest", n: "Encryption at rest" },
        { id: "audit-logging", n: "Audit logging" },
      ] },
    conn: { title: "Connections & sessions", color: 1,
      about: "Each client talks to a server-side session through a framed wire protocol. Connections are costly because each holds memory and often a process, so servers limit them and clients pool them.",
      items: [
        { id: "wire-protocol", n: "Client wire protocol" },
        { id: "connection-handling", n: "Connection handling" },
        { id: "connection-pooling", n: "Connection pooling" },
        { id: "authentication", n: "Authentication" },
        { id: "session-state", n: "Session & transaction state" },
        { id: "result-streaming", n: "Result streaming & cursors" },
      ] },
    parse: { title: "SQL front end", color: 2,
      about: "Turns a statement into a validated tree whose every name, type and view is resolved. Nothing here chooses an algorithm; it only fixes what the query means, so later stages can transform it freely.",
      items: [
        { id: "lexer-and-parser", n: "Lexer & parser" },
        { id: "analyzer-and-binder", n: "Analyzer & binder" },
        { id: "type-coercion", n: "Type system & coercion" },
        { id: "views-and-expansion", n: "Views & expansion" },
        { id: "query-rewriter", n: "Query rewriter" },
        { id: "cte-and-recursion", n: "CTEs & recursion" },
      ] },
    opt: { title: "Query optimizer", color: 3,
      about: "SQL says what, not how. The optimizer enumerates plans, estimates the cost of each from statistics about the data, and keeps the cheapest. Its estimates are wrong often enough that everything around it is built to limit the damage.",
      items: [
        { id: "statistics-collection", n: "Statistics collection" },
        { id: "histograms-and-mcvs", n: "Histograms & common values" },
        { id: "cardinality-estimation", n: "Cardinality estimation" },
        { id: "cost-model", n: "Cost model" },
        { id: "join-ordering", n: "Join ordering" },
        { id: "access-path-selection", n: "Access path selection" },
        { id: "partition-pruning", n: "Partition pruning" },
        { id: "plan-cache", n: "Plan cache" },
        { id: "prepared-statements", n: "Prepared statements" },
      ] },
    exec: { title: "Query executor", color: 4,
      about: "Runs the chosen plan as a tree of operators that pull or push rows between them. Throughput depends on how rows move through the tree, how operators behave when memory runs out, and how work spreads across cores.",
      items: [
        { id: "iterator-model", n: "Iterator model" },
        { id: "vectorized-execution", n: "Vectorized execution" },
        { id: "expression-evaluation", n: "Expression evaluation" },
        { id: "sequential-scan", n: "Sequential scan" },
        { id: "index-scan", n: "Index scan" },
        { id: "nested-loop-join", n: "Nested loop join" },
        { id: "hash-join", n: "Hash join" },
        { id: "merge-join", n: "Merge join" },
        { id: "aggregation", n: "Aggregation" },
        { id: "sorting", n: "Sorting" },
        { id: "spill-to-disk", n: "Spilling to disk" },
        { id: "parallel-query", n: "Parallel query" },
      ] },
    cat: { title: "Catalog & schema management", color: 5,
      about: "The database describes itself in ordinary tables: every table, column, index and type is a row somewhere. Changing that description while queries run is among the most delicate things a database does.",
      items: [
        { id: "system-catalog", n: "System catalog" },
        { id: "ddl-execution", n: "DDL execution" },
        { id: "transactional-ddl", n: "Transactional DDL" },
        { id: "online-schema-change", n: "Online schema change" },
        { id: "table-partitioning", n: "Table partitioning" },
      ] },
    prog: { title: "Constraints & programmability", color: 6, optional: true,
      about: "Rules and code that run inside the server so every client gets them for free. Constraints refuse bad data, while triggers, routines and extensions move logic next to the data.",
      items: [
        { id: "constraint-enforcement", n: "Constraint enforcement" },
        { id: "foreign-keys", n: "Foreign keys" },
        { id: "triggers", n: "Triggers" },
        { id: "stored-procedures", n: "Stored procedures" },
        { id: "user-defined-functions", n: "User-defined functions" },
        { id: "extension-framework", n: "Extension framework" },
      ] },
    txn: { title: "Transactions & concurrency", color: 7,
      about: "Many sessions read and write the same rows at once, yet each must see a consistent world. Versioned rows let readers avoid writers, locks order the conflicts that remain, and cleanup reclaims versions nobody can see.",
      items: [
        { id: "transaction-manager", n: "Transaction manager" },
        { id: "mvcc-versioning", n: "MVCC row versioning" },
        { id: "snapshot-management", n: "Snapshot management" },
        { id: "isolation-levels", n: "Isolation levels" },
        { id: "serializable-validation", n: "Serializable validation" },
        { id: "lock-manager", n: "Lock manager" },
        { id: "deadlock-detection", n: "Deadlock detection" },
        { id: "latches", n: "Latches" },
        { id: "version-garbage-collection", n: "Version garbage collection" },
        { id: "transaction-id-management", n: "Transaction ID management" },
        { id: "savepoints", n: "Savepoints & subtransactions" },
      ] },
    wal: { title: "Logging & recovery", color: 8,
      about: "Changes are described in a sequential log before they reach data pages, so a commit costs one sequential write and a crash costs only a replay. Everything about durability follows from the order of those writes.",
      items: [
        { id: "write-ahead-log", n: "Write-ahead log" },
        { id: "log-record-format", n: "Log record format" },
        { id: "group-commit", n: "Group commit" },
        { id: "checkpointing", n: "Checkpointing" },
        { id: "crash-recovery", n: "Crash recovery" },
        { id: "rollback-and-undo", n: "Rollback & undo" },
        { id: "torn-page-protection", n: "Torn-page protection" },
      ] },
    repl: { title: "Replication", color: 9, optional: true,
      about: "Copies of the database on other machines for failover, read scaling and data distribution. The central choice is whether a commit waits for the copy, trading latency against the data lost when the primary dies.",
      items: [
        { id: "physical-replication", n: "Physical replication" },
        { id: "logical-replication", n: "Logical replication" },
        { id: "synchronous-commit-modes", n: "Synchronous vs async commit" },
        { id: "replication-slots", n: "Replication slots" },
        { id: "failover-promotion", n: "Failover & promotion" },
        { id: "replica-query-conflicts", n: "Replica query conflicts" },
      ] },
    backup: { title: "Backup & point-in-time recovery", color: 10,
      about: "Replication copies mistakes as faithfully as data, so a separate path keeps old states. A base copy plus the archived log can rebuild the database to any moment, including the one just before a bad statement.",
      items: [
        { id: "base-backup", n: "Base backup" },
        { id: "log-archiving", n: "Log archiving" },
        { id: "point-in-time-recovery", n: "Point-in-time recovery" },
      ] },
    buf: { title: "Buffer pool & I/O", color: 11,
      about: "Disk is orders of magnitude slower than memory, so the engine runs its own page cache rather than trusting the operating system's. It decides what stays resident, when dirty pages are written, and how far ahead to read.",
      items: [
        { id: "buffer-pool", n: "Buffer pool" },
        { id: "page-replacement", n: "Page replacement" },
        { id: "background-writer", n: "Background writer" },
        { id: "prefetching", n: "Read-ahead & prefetching" },
        { id: "asynchronous-io", n: "Asynchronous I/O" },
      ] },
    acc: { title: "Access methods & indexes", color: 12,
      about: "Indexes trade write cost and space for fast lookup. Each index type implements the same small interface, so the executor can use a tree, a hash table or a spatial structure without knowing which.",
      items: [
        { id: "btree-index", n: "B-tree index" },
        { id: "btree-concurrency", n: "B-tree concurrency" },
        { id: "hash-index", n: "Hash index" },
        { id: "inverted-index", n: "Inverted index" },
        { id: "spatial-index", n: "Spatial index" },
        { id: "expression-and-partial-indexes", n: "Expression & partial indexes" },
        { id: "index-maintenance", n: "Index maintenance" },
        { id: "concurrent-index-build", n: "Concurrent index build" },
      ] },
    store: { title: "Storage layout", color: 15,
      about: "Tables are arrays of fixed-size pages, and pages are arrays of variable-length rows. The layout decides how many rows fit, how updates reuse space, and how large values and compression are handled.",
      items: [
        { id: "page-layout", n: "Page layout" },
        { id: "heap-files", n: "Heap files" },
        { id: "tuple-format", n: "Tuple format" },
        { id: "free-space-map", n: "Free space tracking" },
        { id: "visibility-map", n: "Visibility map" },
        { id: "large-value-storage", n: "Large value storage" },
        { id: "page-compression", n: "Compression" },
        { id: "file-segment-manager", n: "File & segment manager" },
      ] },
  },
});
