// Plate: Operating system kernel. Structure only; per-component entries live in details*.js.
ATLAS.register({
  slug: "os-kernel",
  title: "Operating System Kernel",
  lede: "Every component of a general-purpose operating system kernel, arranged by layer. A small embedded kernel keeps scheduling, memory and a few drivers; a full server kernel has all of it, plus networking, containers and live tracing.",
  ground: ["CPU & MMU","Firmware","Interrupt controller","Devices & buses","Hypervisor (when virtualized)"],
  crossIntro: "Some decisions are not components. Which code may sleep, how locks are ordered, where the line between trusted kernel and untrusted program sits, whether services live inside one address space, and what the kernel does when something breaks must be settled early, because every layer is written under those answers.",
  cross: [
    { id: "concurrency-discipline", n: "Concurrency & locking discipline" },
    { id: "execution-contexts", n: "Execution contexts" },
    { id: "trust-boundary", n: "Kernel/user trust boundary" },
    { id: "kernel-structure", n: "Monolithic vs. microkernel" },
    { id: "failure-policy", n: "Failure & error policy" },
    { id: "portability", n: "Portability & hardware abstraction" },
  ],
  bands: [
    { label: "Program interface", groups: ["iface"],
      intro: "The contract with every program: how it asks the kernel for work, how it names kernel objects, and how it is interrupted, notified or connected to other programs." },
    { label: "Policy & control", groups: ["proc","sec","resctl"],
      intro: "Who runs, who is allowed to do what, and how much of the machine each group may consume. These layers decide; the layers below carry the decisions out." },
    { label: "Core services", groups: ["vm","fs","net"],
      intro: "The large resource managers: memory, persistent data and networks. Each virtualizes a raw resource into something programs can share safely and name conveniently." },
    { label: "Devices & I/O", groups: ["block","drivers","power"],
      intro: "How the kernel finds hardware, talks to it, queues requests to it and keeps its power draw under control, behind interfaces the services above can treat uniformly." },
    { label: "Kernel infrastructure", groups: ["sync","time","observe","modules"],
      intro: "Machinery the rest of the kernel is built from: locking, clocks and timers, ways to see what the kernel is doing, and the means to extend it while it runs." },
    { label: "Hardware interface", groups: ["bootarch"],
      intro: "The thin, machine-specific layer: bringing the kernel up from firmware, handling traps and interrupts, starting other CPUs and switching between threads." },
  ],
  groups: {
    iface: { title: "Program interface & IPC", color: 1,
      about: "The system call boundary is the only sanctioned way in. Handles, signals and IPC objects hang off it, and every one of them is a promise to programs that must survive decades of kernel change.",
      items: [
        { id: "syscall-dispatch", n: "System call entry & dispatch" },
        { id: "user-memory-access", n: "User memory access" },
        { id: "fast-user-paths", n: "Fast user-space paths" },
        { id: "file-descriptors", n: "Descriptor tables" },
        { id: "event-polling", n: "Readiness & event polling" },
        { id: "signals", n: "Signals" },
        { id: "pipes-and-queues", n: "Pipes & message queues" },
        { id: "shared-memory", n: "Shared memory objects" },
      ] },
    proc: { title: "Processes, threads & scheduling", color: 2,
      about: "A process is an address space plus resources; a thread is a schedulable flow of control. The scheduler multiplexes many runnable threads onto few CPUs while balancing throughput, latency and fairness.",
      items: [
        { id: "task-structures", n: "Task structures" },
        { id: "process-creation", n: "Process creation" },
        { id: "program-loader", n: "Program loader" },
        { id: "thread-model", n: "Thread model" },
        { id: "run-queues", n: "Run queues" },
        { id: "scheduling-policies", n: "Scheduling policies" },
        { id: "load-balancing", n: "Load balancing & topology" },
      ] },
    sec: { title: "Security", color: 3,
      about: "The kernel enforces isolation between principals. Identity, permission checks and capability splitting are the base; mandatory policy, syscall filtering and hardening limit the damage when something above or inside is compromised.",
      items: [
        { id: "credentials", n: "Credentials" },
        { id: "permission-checks", n: "Permission checks" },
        { id: "capabilities", n: "Capabilities" },
        { id: "mandatory-access-control", n: "Mandatory access control" },
        { id: "syscall-filtering", n: "Syscall filtering & sandboxing" },
        { id: "kernel-hardening", n: "Kernel hardening" },
        { id: "keyrings-and-integrity", n: "Keyrings & integrity checks" },
      ] },
    resctl: { title: "Resource control & namespaces", color: 4, optional: true,
      about: "Containers are not a kernel object; they are namespaces that change what a process can see plus control groups that limit what it can use. Small and single-purpose kernels often omit both.",
      items: [
        { id: "namespaces", n: "Namespaces" },
        { id: "control-groups", n: "Control groups" },
        { id: "cpu-memory-limits", n: "CPU & memory limits" },
        { id: "resource-pressure", n: "Pressure & accounting" },
      ] },
    vm: { title: "Virtual memory", color: 5,
      about: "Each process sees a private, contiguous address space that the kernel backs lazily with scarce physical frames, files and swap. Getting reclaim, caching and fragmentation right decides how a machine behaves under load.",
      items: [
        { id: "address-space-layout", n: "Address space layout" },
        { id: "page-tables", n: "Page tables" },
        { id: "tlb-management", n: "TLB management" },
        { id: "page-fault-handler", n: "Page fault handler" },
        { id: "memory-mapping", n: "Memory mapping" },
        { id: "physical-allocator", n: "Physical page allocator" },
        { id: "slab-allocator", n: "Kernel object allocators" },
        { id: "page-cache", n: "Page cache" },
        { id: "page-reclaim", n: "Page reclaim" },
        { id: "swap", n: "Swap" },
        { id: "huge-pages", n: "Huge pages" },
        { id: "oom-handler", n: "Out-of-memory handling" },
      ] },
    fs: { title: "Virtual file system & filesystems", color: 6,
      about: "A common layer presents one namespace of files over many storage formats and synthetic trees. Caches make it fast, journaling or copy-on-write make it survive power loss, and the page cache ties it to memory.",
      items: [
        { id: "vfs-layer", n: "VFS layer" },
        { id: "path-lookup", n: "Path lookup" },
        { id: "dentry-inode-caches", n: "Directory & inode caches" },
        { id: "mount-table", n: "Mounts" },
        { id: "disk-filesystem", n: "On-disk filesystem" },
        { id: "journaling-recovery", n: "Journaling & recovery" },
        { id: "writeback", n: "Dirty data writeback" },
        { id: "pseudo-filesystems", n: "Pseudo-filesystems" },
        { id: "file-locking", n: "File locking" },
      ] },
    net: { title: "Networking stack", color: 7, optional: true,
      about: "Packets travel up and down a pipeline of protocol layers, each handing off to the next through shared buffer structures. The stack must keep up with line rate while many sockets and filters watch the same traffic.",
      items: [
        { id: "socket-layer", n: "Socket layer" },
        { id: "packet-buffers", n: "Packet buffers" },
        { id: "tcp-engine", n: "TCP engine" },
        { id: "ip-layer", n: "IP layer" },
        { id: "routing-forwarding", n: "Routing & forwarding" },
        { id: "packet-filtering", n: "Packet filtering hooks" },
        { id: "netdev-interface", n: "Network device interface" },
        { id: "rx-polling-offload", n: "Receive polling & offloads" },
      ] },
    block: { title: "Block I/O layer", color: 8,
      about: "Between filesystems and storage drivers sits a layer that turns page-sized requests into ordered, merged, device-sized commands, and can stack remapping layers such as striping, mirroring and encryption in between.",
      items: [
        { id: "bio-requests", n: "I/O request structures" },
        { id: "io-schedulers", n: "I/O schedulers" },
        { id: "multi-queue-dispatch", n: "Multi-queue dispatch" },
        { id: "volume-mapping", n: "Volume mapping & RAID" },
        { id: "partition-parsing", n: "Partition parsing" },
      ] },
    drivers: { title: "Device & driver model", color: 9,
      about: "Hardware is discovered, described, matched to drivers and given safe paths for interrupts and memory transfers. A uniform device model keeps thousands of drivers from each reinventing enumeration, binding and teardown.",
      items: [
        { id: "device-model", n: "Device model" },
        { id: "bus-enumeration", n: "Bus enumeration" },
        { id: "driver-binding", n: "Driver binding" },
        { id: "hardware-description", n: "Hardware description tables" },
        { id: "irq-subsystem", n: "Interrupt handling" },
        { id: "deferred-work", n: "Deferred work" },
        { id: "dma-mapping", n: "DMA mapping" },
        { id: "iommu", n: "IOMMU management" },
        { id: "pcie-bus", n: "PCIe bus support" },
        { id: "hotplug-events", n: "Hotplug & device events" },
      ] },
    power: { title: "Power management", color: 15,
      about: "Saving energy touches everything: idle CPUs, scaled frequencies, sleeping devices and whole-system suspend. Each is a negotiation between drivers, scheduler and timers, and each can silently break correctness if state is not restored.",
      items: [
        { id: "system-suspend", n: "System suspend & resume" },
        { id: "idle-states", n: "CPU idle states" },
        { id: "frequency-scaling", n: "Frequency & voltage scaling" },
        { id: "runtime-pm", n: "Runtime device power" },
        { id: "thermal-control", n: "Thermal control" },
      ] },
    sync: { title: "Synchronization & concurrency", color: 10,
      about: "Every CPU runs kernel code at once, and interrupts preempt it. Atomic operations, several lock types and lock-free readers protect shared state, each with different costs, sleeping rules and ways to deadlock.",
      items: [
        { id: "atomics-and-barriers", n: "Atomics & memory barriers" },
        { id: "spinlocks", n: "Spinlocks" },
        { id: "sleeping-mutexes", n: "Sleeping mutexes" },
        { id: "rw-locks-seqlocks", n: "Reader-writer locks & seqlocks" },
        { id: "read-copy-update", n: "Read-copy-update" },
        { id: "per-cpu-data", n: "Per-CPU data" },
        { id: "futex-wait-queues", n: "Wait queues & futexes" },
        { id: "lock-validator", n: "Lock validator" },
      ] },
    time: { title: "Timekeeping & timers", color: 11,
      about: "The kernel turns oscillators and counters into wall-clock time, monotonic time and one-shot or periodic events. Scheduling, timeouts, network retransmits and idle power all depend on these being cheap, monotonic and accurate.",
      items: [
        { id: "clocksources", n: "Clock sources" },
        { id: "clock-events", n: "Clock event devices" },
        { id: "tick-management", n: "Tick management" },
        { id: "high-res-timers", n: "High-resolution timers" },
        { id: "wall-clock-discipline", n: "Wall-clock discipline" },
      ] },
    observe: { title: "Tracing, debugging & crash handling", color: 12,
      about: "A kernel cannot be stopped and inspected like a normal program. Logs, trace points, counters and probes show it running; panic handling and crash dumps preserve evidence when it fails.",
      items: [
        { id: "kernel-log", n: "Kernel log buffer" },
        { id: "tracepoints", n: "Tracepoints & function tracing" },
        { id: "perf-events", n: "Performance counters" },
        { id: "dynamic-probes", n: "Dynamic probes" },
        { id: "sandboxed-bytecode", n: "Verified in-kernel programs" },
        { id: "panic-and-oops", n: "Panic & oops handling" },
        { id: "crash-dump", n: "Crash dump capture" },
      ] },
    modules: { title: "Loadable modules & live patching", color: 13, optional: true,
      about: "Code can be linked into a running kernel on demand, which keeps the base image small and drivers optional. It also widens the trust boundary and raises hard questions about versioning, unloading and patching live.",
      items: [
        { id: "module-loader", n: "Module loader" },
        { id: "symbol-versioning", n: "Symbol export & versioning" },
        { id: "module-signing", n: "Module signing" },
        { id: "live-patching", n: "Live patching" },
      ] },
    bootarch: { title: "Boot & architecture support", color: 14,
      about: "Everything machine-specific: taking control from firmware, building the first memory map, catching traps and interrupts, switching threads, and waking the other CPUs. Written once per CPU family, and the part most likely to hide subtle bugs.",
      items: [
        { id: "firmware-handoff", n: "Firmware handoff" },
        { id: "early-init", n: "Early architecture init" },
        { id: "early-allocator", n: "Early memory allocator" },
        { id: "init-sequence", n: "Kernel init sequence" },
        { id: "initramfs", n: "Initial root image" },
        { id: "trap-entry", n: "Trap & exception entry" },
        { id: "interrupt-controller", n: "Interrupt controller driver" },
        { id: "context-switch", n: "Context switch" },
        { id: "smp-bringup", n: "SMP bring-up & CPU hotplug" },
      ] },
  },
});
