// Details for the Operating System Kernel plate, part 1: program interface, processes, security.
ATLAS.details("os-kernel", {
  "syscall-dispatch": {
    s: "The single gate from unprivileged code into the kernel: a trap instruction switches privilege, saves state, and a number indexes a table of handlers.",
    d: "A program places a call number and arguments in registers and executes a trap instruction. The architecture entry code switches to a kernel stack, saves user registers, and jumps through a table indexed by call number. The handler runs on the calling thread's behalf, in process context, and may sleep. On return the entry code checks for pending work such as signals or rescheduling before restoring user state. The table is the public ABI: numbers are never reused or reordered, and each entry must tolerate hostile arguments.",
    k: ["Register-passed arguments vs. a memory argument block: registers are fast and need no user copy, but limit argument count; a block allows large structures and needs careful copying.",
        "Table-driven dispatch vs. generated per-call stubs: a table is simple to audit, stubs can add tracing, filtering and compatibility wrapping at one place."],
    p: ["Returning to user mode with stale kernel state (leftover privileged registers, unfinished work flags) leaks kernel data or skips signal delivery.",
        "Adding a call without validating every argument turns it into a privilege escalation path."],
    v: "Fuzz every call with random numbers and arguments for hours under a sanitizing build; no crashes, no kernel addresses leaked in return values, and unknown numbers uniformly fail with a clean error.",
    dep: ["trap-entry", "user-memory-access", "task-structures"],
  },
  "user-memory-access": {
    s: "The checked routines the kernel uses to read and write user memory, because a user pointer may be invalid, unmapped, swapped out or malicious.",
    d: "The kernel never dereferences a user pointer directly. Dedicated copy routines verify the range lies in user address space, then perform the access with a recovery mechanism: if a page fault occurs inside the routine, a fixup table redirects execution to an error return rather than crashing. A fault may also legitimately sleep while the page is read from disk. Hardware features that forbid kernel access to user pages outside these routines catch mistakes. Hard parts are time-of-check to time-of-use races and copying structures whose size the user controls.",
    k: ["Copy in, validate, then use vs. operating on user memory in place: a private copy cannot change under the kernel's feet, in-place access saves a copy but invites races.",
        "Fault-driven recovery vs. pre-faulting pages: fixups keep the fast path free of checks, pre-faulting avoids sleeping inside critical sections but costs more."],
    p: ["Reading a length from user memory twice, once to allocate and once to copy, lets another thread change it between the two reads and overflow the buffer.",
        "Copying uninitialized structure padding to user space leaks kernel stack contents."],
    v: "Pass unmapped, kernel-range and partially mapped pointers to every call taking a buffer; each must return an error without a kernel fault, and a concurrent remap test never corrupts kernel memory.",
    dep: ["page-fault-handler", "address-space-layout", "trap-entry"],
  },
  "fast-user-paths": {
    s: "Kernel-provided code and data mapped into every process so common queries, such as reading the clock, complete without a privilege transition.",
    d: "Some calls are so frequent and read-only that a trap costs more than the work. The kernel maps a small read-only region into every address space containing code and data it updates, such as clock counters guarded by a sequence number. User libraries call into that code like a normal function. The kernel keeps the data fresh from its timekeeping core. Related fast paths include user-space locks that enter the kernel only on contention. The design constraint is that this code runs in user mode and must stay correct as the kernel changes.",
    k: ["Shared data page read with a retry loop vs. a real system call: the page is an order of magnitude faster, but the layout becomes ABI and must be updated carefully.",
        "Mapping at a randomized address vs. a fixed one: randomization frustrates attacks, a fixed address is simpler to debug and bind."],
    p: ["Updating the shared clock data without a sequence counter lets a reader observe a half-updated time and see it jump backwards.",
        "Leaving writable or sensitive data in the mapped page exposes kernel state to every process."],
    v: "Read the clock from many threads while stepping the system time and migrating CPUs; readings stay monotonic, and a trace shows zero kernel entries for the calls on the fast path.",
    dep: ["clocksources", "wall-clock-discipline", "address-space-layout"],
  },
  "file-descriptors": {
    s: "Per-process tables mapping small integers to references to open kernel objects, with sharing and inheritance rules across fork and exec.",
    d: "An open file, socket, pipe or device is a kernel object; a descriptor is a process-local index into a table of references to it. Duplicating a descriptor or forking shares the underlying open object, including its read-write offset, while closing drops one reference. Flags control whether a descriptor survives program replacement. Lookups happen on nearly every call, so the table is read mostly lock-free. Passing descriptors between processes over local sockets transfers references. The design makes almost everything nameable by one uniform handle, which is also why leaked descriptors are so costly.",
    k: ["Lowest-free-number allocation vs. unordered handles: lowest-first is the traditional contract and needs a bitmap scan, opaque handles scale better but break assumptions in old programs.",
        "Shared table across threads vs. per-thread tables: sharing matches the process model, per-thread tables isolate state but complicate descriptor passing."],
    p: ["A close racing with a lookup in another thread can free the object while it is in use unless lookups hold a reference.",
        "Forgetting close-on-exec marking leaks sensitive descriptors into spawned programs."],
    v: "Run a multithreaded open, dup, fork and close stress test; object reference counters return to baseline, no descriptor appears in a child that asked for close-on-exec, and the table never exceeds its limit.",
    dep: ["task-structures", "vfs-layer", "atomics-and-barriers"],
  },
  "event-polling": {
    s: "Interfaces that let one thread wait efficiently for readiness on thousands of descriptors, from level scans to persistent interest sets with edge triggers.",
    d: "A server must wait on many sockets and pipes without a thread each. The simple interface copies a full list of descriptors on every call and scans them. Scalable interfaces keep a persistent interest set in the kernel: each watched object has a wait-queue callback that appends to a ready list when its state changes, and the waiter dequeues only ready items. Choices include level-triggered or edge-triggered reporting and how to wake multiple waiters. Complexity comes from objects of every type needing to report readiness, and from locking between the ready list and wakeups.",
    k: ["Persistent interest set vs. rescanning per call: persistence makes cost proportional to activity rather than set size, but the kernel must track lifetime of watched objects.",
        "Edge-triggered vs. level-triggered reporting: edge reports fewer wakeups but loses events if the program does not drain the object; level is forgiving but wakes repeatedly."],
    p: ["A watched descriptor closed in another thread can leave a stale entry that reports events for a recycled number.",
        "Waking every waiter for each event causes a thundering herd that burns CPUs for one unit of work."],
    v: "Watch 100,000 idle sockets and send events to a few; CPU use stays near zero when idle, every event is delivered exactly once under edge mode, and close-during-wait tests report no stale readiness.",
    dep: ["file-descriptors", "futex-wait-queues", "socket-layer"],
  },
  "signals": {
    s: "Asynchronous notifications sent to processes or threads, from faults, other programs, timers and the terminal, with masks, queues and default actions.",
    d: "A signal is a small message that interrupts normal flow. The kernel records it as pending on a thread or process, and at the next return to user mode the thread checks for deliverable signals not blocked by its mask. Each has a default action (terminate, stop, ignore, dump) unless the program installed a handler. Hardware faults such as invalid memory access become synchronous signals to the faulting thread. Real-time variants queue with payload. Signals also drive job control and child-exit notification. They are hard because handlers interrupt arbitrary code, so only a tiny set of operations is safe inside them.",
    k: ["Coalescing standard signals vs. queueing all of them: coalescing bounds kernel memory but loses counts; queueing preserves every event and needs allocation limits.",
        "Process-directed delivery to any eligible thread vs. thread-directed only: process-directed fits the classic model, thread-directed gives precision but demands explicit routing."],
    p: ["Delivering a signal to a thread that is exiting can leak the pending entry or lose a termination request.",
        "Handlers that call non-reentrant routines deadlock when the interrupted code held the same lock."],
    v: "Send random signals to a multithreaded program under load while it forks and execs; every termination signal is honored, queued real-time signals arrive in order with payloads intact, and no pending-signal memory leaks.",
    dep: ["task-structures", "trap-entry", "permission-checks"],
  },
  "pipes-and-queues": {
    s: "Kernel-buffered channels between processes: byte pipes for streams and message queues that preserve record boundaries and priorities.",
    d: "A pipe is a bounded kernel buffer with a read end and a write end exposed as descriptors. Writers block when it is full, readers block when it is empty, and closing the last writer delivers end-of-file. Small writes are atomic. Named variants live in the filesystem namespace so unrelated programs can connect. Message queues instead keep discrete messages with priorities and system-wide names. Both rely on wait queues and the descriptor layer, and both must bound memory per user. Concerns include buffer sizing, zero-copy transfer by moving page references, and wakeups that do not stampede.",
    k: ["Ring of page references vs. a copied byte buffer: page references allow zero-copy splicing, copying is simple and avoids pinning memory shared with files.",
        "Stream semantics vs. message semantics: streams compose with every byte-oriented tool, messages remove the need for framing at the cost of size limits."],
    p: ["Broken-pipe handling that ignores the closed read end lets a writer spin or block forever.",
        "Unbounded per-user queue memory allows one user to exhaust kernel memory with queued messages."],
    v: "Pump data through a long pipeline of processes while killing random stages; no process hangs, no data is duplicated or reordered, and buffer pages return to the allocator when all ends close.",
    dep: ["file-descriptors", "futex-wait-queues", "physical-allocator"],
  },
  "shared-memory": {
    s: "Memory objects that several processes map at once, giving the fastest IPC, since data moves without any kernel copy once mapped.",
    d: "A shared memory object is a named or anonymous region backed by pages that more than one address space maps. After setup, processes read and write directly; the kernel is involved only for creating, sizing, permissioning and unmapping. Backing is typically a memory-resident filesystem, so pages can be swapped and are accounted to their owners. The kernel provides no synchronization, so users combine it with user-space locks or futexes. Challenges include truncation while mapped, which must not crash readers, memory accounting across sharers, and cleanup when the last user exits.",
    k: ["Backing by a pseudo-filesystem vs. a dedicated object type: reusing the filesystem gives names, permissions and sizing for free, a dedicated type is simpler but duplicates mechanisms.",
        "Allowing resize while mapped vs. sealing size: resize is flexible but unsafe for readers, sealing lets a receiver trust the mapping's bounds."],
    p: ["Truncating a mapped object without handling the resulting faults gives other processes an unexpected bus error.",
        "Charging shared pages to nobody lets a process hide unbounded memory use behind sharing."],
    v: "Map one object in many processes, resize and seal it while they read and write; readers either see valid data or a defined error, and after all exit the allocator reports every page returned.",
    dep: ["memory-mapping", "pseudo-filesystems", "page-fault-handler", "permission-checks"],
  },
  "task-structures": {
    s: "The per-thread and per-process kernel records tying together identity, state, memory, files, credentials and scheduling data for everything that runs.",
    d: "Each schedulable entity has a kernel record holding its state, kernel stack, scheduling entity, signal state, pointers to shared sub-objects such as the address space, descriptor table and credentials, and accounting. Threads in one process share many of those pointers; separate processes do not. The record outlives the running thread until the parent collects exit status, giving the zombie state. Lookup by numeric id uses a hash. The difficult parts are reference counting of shared sub-objects, locking granularity, and keeping the record small since there can be hundreds of thousands.",
    k: ["Many small shared sub-objects vs. one monolithic record: sub-objects let threads share exactly what the creation flags request, but multiply reference counting and lifetime rules.",
        "Embedding kernel stack and record together vs. separate allocation: embedding makes current-thread lookup trivial, separation avoids stack overflow corrupting the record."],
    p: ["Freeing a record while another CPU still reads it through a lookup causes use-after-free; lookup needs deferred reclamation.",
        "A kernel stack overflow silently corrupting adjacent fields yields wild, unrelated-looking crashes."],
    v: "Create and exit a million processes and threads in parallel; slab counters return to baseline, no zombie remains once parents wait, and a lookup stress test never touches freed records.",
    dep: ["slab-allocator", "read-copy-update", "address-space-layout", "credentials"],
  },
  "process-creation": {
    s: "How new processes and threads come into being, by duplicating an existing one with selective sharing, or by direct spawn.",
    d: "The classic model duplicates the caller: the child gets a copy of the address space (lazily, by copy-on-write), descriptor table and credentials, then typically replaces its program. A more general clone call takes flags choosing which resources are shared or copied, which also creates threads and namespaced containers. A direct spawn call skips the duplicate. Creation allocates the task record and kernel stack, sets up the child's first return to user mode, assigns an id and places it on a run queue. Hard parts are making duplication cheap for huge address spaces and doing it safely while other threads run.",
    k: ["Duplicate-then-replace vs. spawn: duplication is flexible, letting the child adjust itself before the new program, but costs page-table copying; spawn is cheaper but needs a rich argument set.",
        "Flag-selected sharing vs. separate thread and process calls: one primitive covers all variants, at the price of many flag combinations that must be validated."],
    p: ["Duplicating a multithreaded process leaves locks held by vanished threads locked forever in the child.",
        "Failing midway through creation without unwinding each step leaks memory, ids or half-attached references."],
    v: "Run a fork-exec stress test across all CPUs for an hour; no leaked page frames in the allocator counters, no stuck children, process ids never collide, and no lockup warnings.",
    dep: ["task-structures", "address-space-layout", "page-tables", "file-descriptors", "run-queues"],
  },
  "program-loader": {
    s: "The code that replaces a process's address space with a new executable image and sets up its entry state, stack and arguments.",
    d: "On a program-replace call the kernel opens the file, identifies the format by header, discards the old address space, and maps the executable's segments with the right permissions, lazily backed by the file. It maps a dynamic linker if requested, builds the initial user stack holding arguments, environment and an auxiliary vector of facts (page size, entry point, random bytes), applies permission-changing file attributes, closes marked descriptors and resets signal handlers. Support for several formats is pluggable. It is security sensitive: it parses untrusted headers and decides whether to elevate privileges.",
    k: ["In-kernel format handlers vs. delegating everything to a user-space interpreter: native handlers are fast and self-contained, while delegation shrinks the trusted parser at a performance cost.",
        "Randomized segment placement vs. fixed addresses: randomization hampers exploitation but requires position-independent code and fragmenting address space."],
    p: ["Trusting segment sizes and offsets from the file header allows overlapping or out-of-range mappings.",
        "Computing privilege change after a point where the file can still be swapped leaves a race that runs attacker code with elevated rights."],
    v: "Execute thousands of malformed and truncated images; every one fails cleanly or runs unprivileged, valid ones start with a correctly aligned stack, and a comparison of two runs shows differing segment base addresses.",
    dep: ["address-space-layout", "memory-mapping", "vfs-layer", "credentials", "file-descriptors"],
  },
  "thread-model": {
    s: "How user threads relate to kernel scheduling entities, and how threads within a process share state and are created, joined and cancelled.",
    d: "Modern kernels schedule threads directly: each user thread has its own kernel task, stack and scheduling state, while sharing address space and descriptors with its siblings. Thread-specific data such as the user stack pointer and thread-local storage base lives in per-thread architecture state. Process-wide actions, such as exit, exec and signals aimed at the process, must coordinate every thread. Exit in one thread may need to terminate all. The model also fixes what credentials, working directory and signal handlers are per thread or per process, a source of subtle inconsistencies.",
    k: ["One-to-one kernel threads vs. many-to-one user-level threads: one-to-one uses multiple CPUs and blocks independently, user-level switching is cheaper but a blocking call stalls all.",
        "Per-thread vs. per-process credentials: per-thread allows narrow privilege use but complicates the security model for shared resources."],
    p: ["Exec in a multithreaded process must kill other threads first; skipping that leaves threads running in a vanished address space.",
        "Thread exit racing with process-directed signals can lose the signal if the chosen target already left."],
    v: "Create and cancel thousands of threads while one calls exec and others receive signals; all threads vanish after exec, the new program starts alone, and no thread record or stack is left allocated.",
    dep: ["task-structures", "process-creation", "signals", "context-switch"],
  },
  "run-queues": {
    s: "The per-CPU structures holding runnable threads, and the enqueue, dequeue and pick-next operations the scheduler core is built around.",
    d: "Each CPU owns a run queue ordered by the active policy: priority arrays, a time-ordered tree of virtual runtimes, or deadline lists. When a thread wakes, the scheduler picks a CPU, enqueues the thread, and may flag the running thread for preemption. At each scheduling point the core asks policies in priority order for the next thread, then performs a context switch. Per-CPU queues avoid a global lock, so cross-CPU operations such as wakeup placement and migration need ordered double locking or remote queues. Accounting for time slices and preemption points lives here.",
    k: ["Per-CPU queues vs. one global queue: per-CPU queues scale and keep caches warm but need load balancing; a global queue is fair but contends on one lock.",
        "Tick-driven preemption only vs. immediate wakeup preemption: ticks are simple and cheap, immediate preemption lowers latency but increases context switches."],
    p: ["Waking a thread on a CPU just as it goes idle can leave the thread runnable but unscheduled until the next tick.",
        "Lock-ordering errors between two run queues during migration deadlock the whole machine."],
    v: "Run a wakeup storm with thousands of short-lived threads on all CPUs; trace latency from wakeup to run stays under the target, lock-validator reports nothing, and no runnable thread waits beyond the starvation bound.",
    dep: ["task-structures", "spinlocks", "per-cpu-data", "context-switch"],
  },
  "scheduling-policies": {
    s: "The algorithms deciding which runnable thread gets a CPU and for how long, from fair-share time slicing to fixed-priority and deadline classes.",
    d: "Kernels host several scheduling classes ranked by precedence. Real-time classes run fixed-priority first-in-first-out or round-robin threads, and deadline classes admit tasks with declared runtime and period. The default fair class gives each thread a share proportional to weight, tracked as virtual runtime, favoring those that have run less. Interactive tasks get low latency by sleeping often. Policies interact with priorities inherited through locks, with group quotas, and with idle. Tuning is hard because throughput, latency and fairness trade against each other and workloads vary.",
    k: ["Fair-share by weight vs. strict priority: fair-share prevents starvation, strict priority gives predictable latency to critical tasks but lets them starve the rest.",
        "Admission control for deadline tasks vs. best effort: admission guarantees schedulability but rejects work, best effort accepts everything and misses deadlines under overload."],
    p: ["A runaway real-time thread with no throttle monopolizes a CPU and locks the system.",
        "Priority inversion through a lock held by a low-priority thread silently defeats the real-time guarantees."],
    v: "Run mixed CPU-bound and interactive load with real-time tasks; a latency trace shows real-time wakeup delay within the configured bound and CPU-bound tasks get shares within a few percent of their weights.",
    dep: ["run-queues", "tick-management", "high-res-timers", "sleeping-mutexes"],
  },
  "load-balancing": {
    s: "Spreading threads across CPUs by migrating them between run queues while respecting cache sharing, memory locality and power topology.",
    d: "Idle CPUs steal work and periodic rebalancing moves threads from busy queues to light ones. The scheduler models the machine as nested domains such as sibling hardware threads, cores sharing a cache, sockets and memory nodes, balancing frequently inside small domains and rarely across large ones. Policies weigh migration cost against imbalance, honor affinity masks, and consider where a thread's memory lives. Energy-aware placement packs work on efficient cores to let others sleep. Hard because load is bursty and measuring it takes time, so decisions chase stale data.",
    k: ["Pull by idle CPUs vs. push from busy ones: pulling reacts exactly when capacity exists but adds idle wakeup cost; pushing needs periodic checks yet spreads proactively.",
        "Strict affinity vs. soft preference for the last CPU: strict gives determinism, soft preference keeps caches warm while still letting work spread."],
    p: ["Over-eager migration thrashes caches and makes a loaded system slower than an unbalanced one.",
        "Ignoring memory node locality moves a thread away from its data, silently doubling its memory latency."],
    v: "Pin a heterogeneous workload set on a multi-socket machine; per-CPU utilization differs by only a few percent, migrations per second stay moderate, and remote memory access counters stay low.",
    dep: ["run-queues", "scheduling-policies", "per-cpu-data", "smp-bringup", "idle-states"],
  },
  "credentials": {
    s: "The identity record attached to each task: user and group ids, supplementary groups, capability sets and security labels, treated as immutable once published.",
    d: "Every task points to a credentials object with real, effective and saved identities, group lists, capability sets and mandatory-access-control labels. The object is shared and never modified in place: to change identity, code prepares a copy, edits it and atomically commits it, so concurrent readers always see a consistent set. Program execution may compute new credentials, for instance for privileged files. Namespaces map ids so an identity inside a container differs from outside. Changes follow strict rules about what a thread may become.",
    k: ["Copy-on-modify immutable credentials vs. in-place update under a lock: immutability makes reads lock-free and consistent, but each change allocates and needs care to publish.",
        "Separate real and effective identities vs. a single one: two identities allow temporary privilege use and drop, but double the number of checks that must be reasoned about."],
    p: ["Dropping group membership after user id change in the wrong order leaves a process holding privileged groups.",
        "Checking against the task's current credentials rather than the opener's at use time lets a later change retroactively grant or revoke access."],
    v: "Fuzz identity-changing calls from threads with random privilege sets; no sequence ever raises effective rights beyond the starting capabilities, and credential object counts return to baseline after all tasks exit.",
    dep: ["task-structures", "read-copy-update", "namespaces"],
  },
  "permission-checks": {
    s: "The classic owner, group and other permission model plus access control lists, evaluated for every access to a protected object.",
    d: "Each file, IPC object and device carries an owner, a group and permission bits, optionally extended by lists naming additional principals. On access, the kernel compares the caller's credentials against these and then also asks the mandatory layers. Directory traversal checks search permission on every path component. Special bits change execution identity or constrain deletion in shared directories. The check must be performed at the right time: at open for file data, per operation for others. Subtle questions include privileged bypass, sticky directories and interactions with namespaces.",
    k: ["Discretionary owner-controlled permissions vs. system-wide policy only: owners can share easily, but any compromised program running as that owner inherits everything.",
        "Check at open vs. check at each operation: checking once is fast and matches descriptor passing semantics, checking each time allows revocation but costs more."],
    p: ["Checking permission and then acting in a separate step allows the object to be swapped, such as by symbolic link, between check and use.",
        "Forgetting the check on one of several paths to the same object, such as an alternate entry call, creates a bypass."],
    v: "Run a matrix test with every combination of owner, group, other, list entries and privilege across read, write, execute and traversal; results match the specification table exactly, including denied cases.",
    dep: ["credentials", "vfs-layer", "capabilities", "mandatory-access-control"],
  },
  "capabilities": {
    s: "Splitting the all-powerful superuser into distinct, individually grantable privileges, held in sets that bound what a task may exercise or pass on.",
    d: "Instead of one root identity bypassing all checks, privileged operations each demand a named capability, such as binding low network ports, loading modules or changing the clock. A task holds several sets: those it currently exercises, those it may enable, and those that survive program execution. Files can carry capability attributes to grant limited rights on execution. Bounding sets cap what any descendant can obtain. A separate, object-capability style uses unforgeable handles to objects as authority itself. Hard parts are choosing granularity and noticing that some single capabilities are nearly root.",
    k: ["Fine-grained privileges vs. a few coarse ones: fine grains allow least privilege, but there are many to audit and some become effectively equivalent to full control.",
        "Ambient process capabilities vs. handle-based capabilities: ambient is compatible with existing programs, handles prevent the confused deputy problem but need new interfaces."],
    p: ["A catch-all capability that gates many unrelated operations is handed out for one small need and becomes a full privilege escalation.",
        "Inheriting capabilities across program execution without limit lets a compromised child regain powers the parent meant to drop."],
    v: "Drop all but one capability and attempt every privileged call from a test program; only operations requiring that capability succeed, and exec of an unprivileged program from it yields an empty set.",
    dep: ["credentials", "permission-checks", "namespaces"],
  },
  "mandatory-access-control": {
    s: "A system-wide policy, set by administrators rather than owners, deciding which labeled subjects may perform which operations on which labeled objects.",
    d: "A security framework places hooks at every sensitive decision: file open, process signal, socket connect, memory mapping. Each hook consults a loaded policy module that compares the subject's label with the object's, and answers allow or deny after the normal checks succeed. Labels live in extended attributes or in the policy itself, and transitions on program execution change a subject's domain. Policies are compiled and loaded at runtime, and denials are logged. The challenge is coverage of hooks, performance on hot paths, and writing policies that are complete without being unusable.",
    k: ["Label-based type enforcement vs. path-based rules: labels follow objects through renames and links but need relabeling, path rules are readable but break when paths change.",
        "Stacked modules vs. exactly one policy engine: stacking permits layered policies, a single engine has simpler semantics and fewer interaction bugs."],
    p: ["A missing hook on one code path leaves the policy silently unenforced for that operation.",
        "Permissive-mode logs that nobody reviews let a policy ship with allow-everything gaps."],
    v: "Load a policy denying a test domain network access and file writes; attempts through every route, including via descriptor passing and alternate calls, are denied and each logs an audit record naming the rule.",
    dep: ["permission-checks", "credentials", "vfs-layer", "keyrings-and-integrity"],
  },
  "syscall-filtering": {
    s: "Per-process rules, installed by the process itself and irreversible, restricting which system calls and arguments it may use, forming the base of sandboxes.",
    d: "A process loads a small program that the kernel runs on each call entry, inspecting the call number and argument registers and returning allow, deny with an error, trap, kill or log. Filters are inherited by children and can only be tightened, never removed, so a program can lock itself down after setup and before touching untrusted input. Combined with namespaces and capability dropping, it forms a sandbox. The filter language is deliberately limited and verified to terminate. Hard: pointer arguments cannot be safely inspected because contents may change, and call lists must track the evolving ABI.",
    k: ["Allow-list vs. deny-list of calls: an allow list fails closed when new calls appear, a deny list is easier to write but misses new dangerous calls.",
        "Filtering on registers only vs. inspecting user memory: registers are race-free, memory inspection is more expressive but open to time-of-check races."],
    p: ["Filtering by call number without checking the ABI variant lets a program use an alternate numbering to reach denied calls.",
        "Filters that allow a call to change the filter or load code by another route can be unwound."],
    v: "Install a filter permitting a minimal call set and run a test program that tries every call number and ABI variant; only the permitted ones succeed, and the filter survives fork and exec.",
    dep: ["syscall-dispatch", "task-structures", "capabilities", "sandboxed-bytecode"],
  },
  "kernel-hardening": {
    s: "Defenses that make kernel bugs harder to exploit: randomization, memory protections, bounds and integrity checks, and removal of dangerous interfaces.",
    d: "Hardening assumes the kernel contains bugs and raises the cost of using them. Measures include randomizing the kernel's own layout, marking code read-only and data non-executable, guarding stacks, clearing freed and newly allocated memory, checking object sizes on copy to user space, protecting function pointers with integrity checks, and hiding addresses from unprivileged users. Hardware features such as supervisor-mode access barriers and pointer authentication add more. Each has a performance cost, a compatibility cost, and an attacker workaround, so they are layered rather than relied on individually.",
    k: ["Always-on checks vs. debug-only sanitizers: always-on checks catch real exploitation, but cost throughput; debug sanitizers are thorough but never run in production.",
        "Memory zeroing on allocation or free vs. neither: zeroing prevents leaks and uninitialized use but costs bandwidth, especially for large buffers."],
    p: ["Exposing kernel addresses through logs or interfaces defeats layout randomization at once.",
        "Disabling a hardening feature for one driver's performance quietly removes the protection for the whole system."],
    v: "Run exploit regression tests for known bug classes against a hardened build: stack smashing, freed-object reuse, and write to read-only code each fault or are detected, and kernel addresses read from unprivileged interfaces appear as zero.",
    dep: ["page-tables", "slab-allocator", "user-memory-access", "early-init"],
  },
  "keyrings-and-integrity": {
    s: "Kernel storage for cryptographic keys and the machinery that verifies the integrity of executables, modules and files against trusted measurements.",
    d: "Keyrings hold keys, credentials and certificates in kernel memory, referenced by handles with their own permissions and lifetimes, so secrets never need to enter user address space. Integrity subsystems measure files when read or executed, comparing hashes or signatures against trusted values anchored in firmware or hardware, and can refuse to run mismatches. Measurement logs support remote attestation. The same machinery verifies module signatures. The hard part is the chain of trust: every link from firmware to the root image needs a verified predecessor, and a single unchecked step breaks it.",
    k: ["Verify at load time vs. verify on every page read: load time is cheap, per-page verification catches later tampering of underlying storage but costs on every fault.",
        "Enforce on mismatch vs. record only: enforcement stops tampering at the cost of availability when signatures are wrong; recording preserves function and shifts detection to later."],
    p: ["Trusting a file's verified contents but not its metadata lets an attacker change attributes that alter execution.",
        "Keys left in a keyring that outlives its owning process stay reachable after the privilege is gone."],
    v: "Modify one byte of a signed executable and of a signed module on disk; both are refused, a measurement entry records each attempt, and unmodified copies load normally.",
    dep: ["credentials", "vfs-layer", "page-cache", "firmware-handoff"],
  },
});
