// Details for the Operating System Kernel plate, part 3: networking, block layer, drivers, power.
ATLAS.details("os-kernel", {
  "socket-layer": {
    s: "The program-facing network abstraction: endpoints created, bound, connected and used through descriptors, independent of the protocol underneath.",
    d: "A socket is an endpoint object behind a descriptor, created by address family and type (stream, datagram, raw, local). The layer dispatches calls such as bind, listen, accept, connect, send and receive to the protocol implementation through operation tables, and holds per-socket send and receive queues, options, timeouts and wait queues for readiness. It enforces limits on buffer memory and the connection backlog. Local sockets use the same interface for same-machine communication and can pass descriptors and credentials. Making blocking, non-blocking and event-driven use all correct over the same state machine is the difficulty.",
    k: ["One generic socket interface vs. protocol-specific calls: one interface lets programs be protocol-agnostic, but exposes least-common-denominator semantics and option sprawl.",
        "Per-socket lock with backlog queue vs. a fully lockless path: a lock with backlog is simple to keep consistent between user calls and packet arrival, lockless is faster but intricate."],
    p: ["A listen backlog without limits lets a flood of half-open connections exhaust memory.",
        "Closing a socket while another thread blocks in it must wake that thread rather than leave it sleeping on freed state."],
    v: "Open and close hundreds of thousands of connections while threads block in accept, send and receive; all blocked calls return on close, socket and buffer counters return to baseline, and memory limits hold under a flood.",
    dep: ["file-descriptors", "packet-buffers", "tcp-engine", "event-polling", "permission-checks"],
  },
  "packet-buffers": {
    s: "The structure carrying a packet through the stack, with headroom for headers, shared payload references and metadata, designed to avoid copying.",
    d: "Each packet is described by a buffer header pointing into a data area with reserved space in front, so each layer prepends its header by moving a pointer instead of copying. Headers are parsed in place on receive. Payload can be split across fragments or pages, and clones share data with copy on write semantics. Metadata records checksum state, timestamps, the incoming device and the owning socket for memory accounting. Buffers come from per-CPU caches. The structure is touched by every layer and every filter, so correctness of ownership, length and offset arithmetic dominates security.",
    k: ["Linear data area vs. scatter-gather fragments: linear is simple to parse, fragments allow zero-copy transmit of file pages and large offloads but complicate every parser.",
        "Cloning with shared data vs. always copying: sharing is cheap for taps and retransmits but requires care before modification."],
    p: ["Off-by-one in header length arithmetic is the classic source of remote memory corruption.",
        "Failing to charge buffers to the sending socket lets one sender consume unlimited memory in queues."],
    v: "Feed the stack malformed, truncated and fragmented packets with a sanitizing build; no out-of-bounds access is reported, buffer allocations return to baseline, and a zero-copy transmit of a file sends the exact bytes.",
    dep: ["slab-allocator", "per-cpu-data", "physical-allocator"],
  },
  "tcp-engine": {
    s: "Reliable, ordered byte streams over unreliable packets: connection state machine, retransmission, flow control and congestion control.",
    d: "The engine implements the connection state machine, sequence numbers, acknowledgments, timers for retransmission and keepalive, window management for flow control, and congestion control that adapts sending rate to loss and delay signals. It segments and coalesces data, handles out-of-order arrival with reassembly queues, and negotiates options at setup. Congestion control algorithms are pluggable. Performance work includes segmentation offload, small-queue limits and busy polling. It faces hostile input constantly: connection floods, malformed options, and slow peers, so state and timer memory must be bounded.",
    k: ["Pluggable congestion control vs. one fixed algorithm: pluggable lets operators match algorithms to loss and latency conditions, but adds an interface to keep stable and fair.",
        "Cookie-based handling of connection floods vs. storing state per half-open connection: cookies resist floods but drop some options, state keeps full features and exhausts memory."],
    p: ["Retransmission timers that lack a backoff cap retransmit a storm into a congested link.",
        "Sequence number wraparound comparisons done with plain integer comparison break at the boundary after long uptimes."],
    v: "Run bulk transfers across an emulated link with loss, reordering and delay; throughput approaches the model's expectation, data arrives intact and in order, and a SYN flood leaves legitimate connections serviceable.",
    dep: ["socket-layer", "packet-buffers", "ip-layer", "high-res-timers"],
  },
  "ip-layer": {
    s: "Addressing and delivery of packets between hosts: header validation, fragmentation and reassembly, and handing packets to transports or forwarding.",
    d: "On receive, the layer validates headers and checksums, runs input filtering hooks, and decides whether the packet is for this host (deliver upward by protocol number) or should be forwarded. On transmit it builds headers, chooses source addresses, consults the routing table, fragments oversized packets or relies on path size discovery, and passes down to the device layer. Reassembly of fragments uses bounded queues with timeouts. Supports multiple address versions, multicast groups and error messages. It is the first parser of untrusted network input, so validation and resource bounds are critical.",
    k: ["Kernel fragment reassembly vs. dropping fragments: reassembly keeps old applications working, but costs memory and is an attack surface; dropping is safe and breaks some traffic.",
        "Route lookup cached per socket vs. every packet: caching saves a lookup but must be invalidated whenever routes change."],
    p: ["Unbounded reassembly queues let an attacker with partial fragments exhaust memory.",
        "Trusting the header length field without verifying against the buffer reads past the packet."],
    v: "Send fragmented, overlapping and oversized packets from a fuzzer for an hour; reassembly memory stays under its limit, malformed packets are dropped with counters incremented, and valid traffic still arrives.",
    dep: ["packet-buffers", "routing-forwarding", "packet-filtering", "netdev-interface"],
  },
  "routing-forwarding": {
    s: "The table and lookup logic that map a destination address to a next hop and outgoing interface, including policy rules and forwarding between interfaces.",
    d: "Routes map destination prefixes to gateways and interfaces; lookup picks the longest matching prefix, optionally after policy rules select among several tables by source, mark or interface. Lookup structures are tries or hash-based and designed for lock-free reads while routing daemons update them. Forwarding decrements hop limits, applies filtering, may rewrite addresses, and sends the packet out. Equal-cost multipath spreads flows across links. Neighbor tables resolve next-hop addresses to link addresses. Large tables with frequent updates and fast, consistent lookups make this a classic read-copy-update workload.",
    k: ["Trie with longest-prefix match vs. hashing per prefix length: tries give predictable lookup and scale to large tables, hashing is simple for few prefixes.",
        "Per-flow vs. per-packet multipath: per-flow keeps ordering for each connection, per-packet balances load more evenly but reorders."],
    p: ["Updating routes in place while readers walk the table causes lookups to follow a freed node.",
        "Forwarding without verifying the source address's expected interface lets spoofed traffic transit the host."],
    v: "Load a table of hundreds of thousands of routes and flap entries while forwarding traffic; no packet follows a stale or half-updated route, lookup rate stays high, and a spoofed-source test is dropped.",
    dep: ["ip-layer", "read-copy-update", "netdev-interface", "namespaces"],
  },
  "packet-filtering": {
    s: "Hook points in the packet path where rules can accept, drop, rewrite or redirect traffic, the basis of firewalls and address translation.",
    d: "The stack exposes hooks at fixed stages: after receive, before and after routing, and before transmit. Rule sets register callbacks at each with an order; each returns accept, drop, steal or queue to user space. Rule engines compile user-supplied tables into a matching program, with connection tracking recording flow state so established traffic is allowed and related traffic such as data channels is recognized. Address translation rewrites headers and keeps per-flow mappings. Hooks run on every packet, so rule evaluation must be fast and updates atomic, and tracking tables must be bounded.",
    k: ["Stateful connection tracking vs. stateless rules: stateful rules are expressive and simple for administrators, but cost memory and can be exhausted by floods.",
        "Compiled rule programs in the kernel vs. fixed match tables: programs are flexible and fast after load, but need a verifier and add complexity."],
    p: ["A full connection-tracking table drops legitimate new connections during a flood.",
        "A rule update that is applied incrementally leaves a window where neither the old nor the new policy is in force."],
    v: "Load a policy and send matching, non-matching and replayed traffic; each is handled per rule, established flows pass, a table-fill test degrades predictably, and swapping rule sets never shows a mixed policy.",
    dep: ["ip-layer", "packet-buffers", "read-copy-update", "sandboxed-bytecode"],
  },
  "netdev-interface": {
    s: "The abstraction between the protocol stack and network hardware or virtual links: transmit queues, receive entry, statistics and capability flags.",
    d: "Every link, physical or virtual, registers an interface object with operations to open, close and transmit, advertising features such as checksum and segmentation offload. The stack hands outgoing packets to per-interface multiqueue transmit rings, applying queueing disciplines, and drivers signal backpressure to stop and restart queues. Receive delivers packets upward through a common entry. Virtual devices (bridges, tunnels, bonds, virtual ethernet pairs) stack on the same interface, enabling containers and virtual machines. Statistics, link state and address lists are managed here. Mismatched offload promises are a rich source of subtle bugs.",
    k: ["Stackable virtual devices vs. special cases in the stack: stacking gives composable bridges and tunnels, but long chains add per-packet overhead and recursion risk.",
        "Driver-advertised offloads vs. always software: offloads save CPU and cut per-packet cost, but depend on correct hardware and make debugging harder."],
    p: ["Stopping a transmit queue and failing to wake it after completion stalls the interface forever.",
        "Advertising an offload the hardware performs incorrectly corrupts packets in ways that appear only under load."],
    v: "Pass traffic through stacked virtual devices on multiple queues and hot-add or remove the interface under load; no packets are corrupted, queues recover from stalls, and statistics match packet counts at both ends.",
    dep: ["device-model", "packet-buffers", "rx-polling-offload", "dma-mapping"],
  },
  "rx-polling-offload": {
    s: "Combining interrupts and polling to receive packets at high rates, with hardware spreading flows across CPUs and offloads merging packets.",
    d: "At high packet rates, one interrupt per packet overwhelms a CPU. The driver instead disables its interrupt on the first packet and schedules a polling routine in softirq context that drains a bounded batch from the receive ring, re-enabling the interrupt when it runs dry. Hardware hashes flows to multiple receive queues, each with its own interrupt steered to a CPU, so one flow stays on one CPU and caches stay warm. Receive offloads merge consecutive segments of a flow before passing them up. Busy polling lets latency-sensitive applications poll directly. The balance is between latency, throughput and CPU use.",
    k: ["Interrupt then poll vs. pure interrupt: hybrid scales under load and stays low-latency when idle, pure interrupts are simplest but livelock at high rates.",
        "Flow-hash steering to CPUs vs. a single receive queue: steering gives parallel processing and cache locality, but a skewed flow mix overloads single CPUs."],
    p: ["Polling without a batch budget starves other work in the same softirq context.",
        "Merging packets that should not be combined breaks forwarding, because the merged result exceeds the outgoing link's limits."],
    v: "Drive line-rate small-packet traffic across many flows; no CPU saturates in interrupt context, per-queue counters are balanced, drops stay at zero below capacity, and latency of a ping remains low.",
    dep: ["netdev-interface", "irq-subsystem", "deferred-work", "dma-mapping"],
  },
  "bio-requests": {
    s: "The units of block I/O: descriptors for scattered memory segments mapped to device sectors, submitted by filesystems and the cache and completed asynchronously.",
    d: "A block request descriptor describes a transfer of a list of memory segments to or from a contiguous run of sectors, with direction, flags (flush, ordering, sync), and a completion callback. Filesystems and the page cache build these, and lower layers may split, merge or remap them. Submission is asynchronous: the caller continues, and completion is signaled from interrupt context, usually by waking a waiter or marking pages clean. Error status propagates upward. Request structures must carry integrity and encryption metadata where used, and they must be allocatable even under memory pressure, from reserved pools.",
    k: ["Scatter-gather segment lists vs. contiguous buffers: lists avoid copying and match direct memory access hardware, contiguous buffers are simple but force bounce copies.",
        "Mempool-backed reserves vs. plain allocation: reserves let writeback make progress under memory pressure, plain allocation can deadlock reclaim."],
    p: ["Completing a request twice, or never, corrupts accounting or leaves a waiter asleep forever.",
        "Ignoring partial failure of a split request reports success for data that did not reach the device."],
    v: "Submit random-sized reads and writes with injected device errors and timeouts; every request completes exactly once with the correct status, no memory pages leak, and reclaim under pressure continues to make progress.",
    dep: ["slab-allocator", "dma-mapping", "page-cache", "io-schedulers"],
  },
  "io-schedulers": {
    s: "Policies that reorder, merge and prioritize pending block requests to improve throughput, bound latency and share a device fairly.",
    d: "Between submission and the device, a scheduler may merge adjacent requests, sort them by sector to reduce seeks on rotating disks, and prioritize reads over writes since programs wait on reads. Deadline-style schedulers bound how long any request waits; proportional ones divide device time among groups by weight and class. For fast flash devices with deep queues, the best scheduler is often none, since reordering cost exceeds benefit. Policy interacts with group limits and with writeback. Tuning depends on device characteristics that firmware often hides.",
    k: ["Seek-minimizing sorting vs. none for flash devices: sorting helps rotating media dramatically, but only adds CPU cost and latency for devices without seek penalties.",
        "Deadline guarantees vs. proportional fairness: deadlines bound worst-case latency, proportional sharing gives groups predictable bandwidth but can delay individual requests."],
    p: ["Starvation of writes behind a stream of reads fills memory with dirty pages.",
        "Idling to wait for a likely sequential request wastes device time on devices that serve requests in parallel."],
    v: "Run mixed random and sequential streams from competing groups; read latency stays under its bound, each group's bandwidth is within a few percent of its weight, and no request exceeds the deadline.",
    dep: ["bio-requests", "multi-queue-dispatch", "control-groups"],
  },
  "multi-queue-dispatch": {
    s: "A block path with per-CPU submission queues mapped to hardware queues, letting many CPUs issue I/O to fast devices without sharing a lock.",
    d: "Single-queue designs became a bottleneck once devices handled millions of operations per second. The multi-queue layer gives each CPU (or group of CPUs) a software queue, mapped onto the device's hardware queues, so submission takes no global lock. Tags identify in-flight commands, bounding queue depth and locating the request on completion. Completion interrupts are steered back to the submitting CPU for cache locality. The layer handles timeouts, error recovery, and hotplug of CPUs, which reshuffles queue mappings. Fairness across queues and limits on shared devices are the complexity.",
    k: ["Per-CPU software queues vs. a single locked queue: per-CPU queues scale linearly with CPUs, but reordering opportunities across CPUs are lost.",
        "Completing on the submitting CPU vs. wherever the interrupt arrives: completion on the submitter keeps caches warm, but needs cross-CPU signalling when the interrupt lands elsewhere."],
    p: ["A command timeout handler racing with a late completion can complete the same command twice.",
        "Remapping queues on CPU hotplug without draining in-flight commands loses completions."],
    v: "Issue maximum-rate small random I/O from all CPUs to a fast device while hot-removing CPUs; throughput scales with CPU count, no I/O is lost, and per-queue timeouts recover cleanly under injected stalls.",
    dep: ["bio-requests", "per-cpu-data", "irq-subsystem", "smp-bringup"],
  },
  "volume-mapping": {
    s: "Stackable remapping layers that present one logical block device built from others: striping, mirroring, parity, snapshots, thin provisioning and encryption.",
    d: "A mapping layer receives requests for a virtual device and translates them to requests on underlying devices through a table. Targets implement the behaviors: linear concatenation, striping for bandwidth, mirroring and parity for redundancy, copy-on-write snapshots, thin allocation on demand, caching, and transparent encryption. Layers stack arbitrarily. Redundant targets track degraded states and rebuild in the background, throttled. The layer is metadata-intensive and must keep that metadata crash-consistent, since a bug here corrupts everything above it.",
    k: ["Logical volumes in the block layer vs. redundancy inside the filesystem: the block layer works under any filesystem, an integrated one can use file-level knowledge to repair and resize.",
        "Write-intent bitmap for mirrors vs. full resync after crash: a bitmap makes recovery quick but adds write overhead."],
    p: ["Parity update interrupted by power loss leaves a stripe that silently reconstructs wrong data (the write hole).",
        "Rebuild at full speed starves foreground I/O, so latency collapses during recovery."],
    v: "Build a mirror under a filesystem, kill one member while writing, replace it and rebuild; data verifies correctly throughout, foreground latency stays bounded during rebuild, and a power-cut test finds no inconsistent stripe.",
    dep: ["bio-requests", "partition-parsing", "multi-queue-dispatch", "keyrings-and-integrity"],
  },
  "partition-parsing": {
    s: "Reading the partition table of a disk to expose each partition as its own block device with correct offsets and bounds.",
    d: "When a disk appears, the kernel reads its first sectors and any alternate table, recognizes the partition scheme by signature, validates entries, and creates a block device per partition that remaps sector numbers by the partition offset and enforces its length. Several schemes exist: legacy tables with few primary entries and nested logical ones, and newer tables with unique identifiers and redundant copies. The parser handles untrusted data from removable media, so malformed or overlapping entries must not crash it. Rescanning on change and handling of in-use partitions during repartition are required.",
    k: ["Parsing in the kernel vs. in user space: in-kernel parsing makes root devices available early, user-space parsing shrinks the trusted base but needs an early helper.",
        "Trust tables as given vs. cross-check redundant copies: cross-checking catches corruption, but needs rules for which copy wins."],
    p: ["An entry extending past the end of the disk lets a partition's remapped I/O touch other data.",
        "Rescanning a disk while a partition is mounted can drop or renumber devices in use."],
    v: "Present disks with valid, overlapping, truncated and corrupted tables; valid ones expose exact sizes and offsets, malformed ones are rejected without faults, and I/O at partition bounds never reaches outside.",
    dep: ["bio-requests", "device-model", "bus-enumeration"],
  },
  "device-model": {
    s: "The kernel's uniform representation of devices, buses, drivers and classes, with lifetimes, parent-child relationships and attributes exported to user space.",
    d: "Every device is an object in a tree reflecting physical topology: a controller owns a bus, a bus holds devices. Drivers register with a bus; devices register and are matched. Objects are reference counted so they are freed only after the last user drops, which allows removal while open. Classes group devices by function regardless of topology. Each object exposes attributes in a pseudo-filesystem and emits events for user space. The model also provides the parent-child order used for power transitions. Lifetime rules, especially for hot-removed devices, are the hard part.",
    k: ["Reference-counted device objects vs. explicit ownership: reference counts permit safe removal with open handles, but make teardown order and leaks harder to reason about.",
        "Topology tree plus separate classes vs. one flat namespace: the tree supports power ordering and enumeration, classes let users find devices by function."],
    p: ["Freeing driver data while a user still holds an open handle causes use-after-free on the next call.",
        "Registering a device before its attributes and state are initialized exposes half-built objects to user space."],
    v: "Plug, unplug and rebind devices in a loop while programs hold them open; every operation fails cleanly after removal, object counts return to zero, and the exported tree mirrors topology at each step.",
    dep: ["slab-allocator", "pseudo-filesystems", "atomics-and-barriers"],
  },
  "bus-enumeration": {
    s: "Discovering which devices exist on each bus at boot and after changes, reading identity, capabilities and resource needs.",
    d: "Self-describing buses such as PCIe and USB report devices when probed: the enumerator walks the bus hierarchy, reads vendor and class identifiers and configuration registers, sizes address windows and assigns resources, then registers each device with the device model. Buses without discovery rely on hardware description tables. Enumeration is recursive through bridges and hubs, can be repeated at runtime when devices appear, and must handle devices that respond slowly or incorrectly. Resource assignment (address windows, interrupt lines) must avoid conflicts and respect bridge ranges, a puzzle when firmware's assignments are partial.",
    k: ["Trust firmware's resource assignment vs. reassign everything: trusting is fast and matches firmware, reassigning is flexible for hotplug but riskier early.",
        "Synchronous probing at boot vs. parallel asynchronous probing: parallel shortens boot, but makes device naming and order nondeterministic."],
    p: ["A misbehaving device that never completes a configuration read can hang the walk without timeouts.",
        "Overlapping address windows assigned by bridge errors make two devices answer for the same address."],
    v: "Boot on machines with deep bridge hierarchies and hot-add devices at runtime; every device is found with correct identity and non-overlapping resources, and slow or absent devices cause bounded delay.",
    dep: ["device-model", "hardware-description", "pcie-bus", "driver-binding"],
  },
  "driver-binding": {
    s: "Matching discovered devices to drivers by identifier tables, then probing, attaching and later detaching them.",
    d: "Each driver publishes the identifiers it supports. When a device appears or a driver loads, the bus core compares identifiers, calls the driver's probe routine, which claims resources, initializes the hardware, and registers with its subsystem. If probe fails or defers because a needed resource such as a clock or regulator is not yet ready, the core retries later. Unbind calls remove, which must stop the hardware and release everything, even if the device is gone. Drivers can be bound or rebound from user space, and loading modules is triggered by identifier aliases from device events.",
    k: ["Probe deferral with retry vs. explicit ordering of drivers: deferral handles dependencies automatically, but obscures why a device never appeared.",
        "Automatic binding vs. manual choice per device: automatic is convenient, manual lets virtualization hand devices to a guest-facing driver."],
    p: ["A probe error path that forgets to release a resource leaks it on each failed attempt.",
        "A remove routine that assumes the hardware still responds hangs when the device was physically unplugged."],
    v: "Load, unload, bind and unbind a driver in a loop with fault injection in every probe step; resources balance after each cycle, deferred devices eventually bind, and no remove path touches missing hardware.",
    dep: ["device-model", "bus-enumeration", "module-loader", "hotplug-events"],
  },
  "hardware-description": {
    s: "Firmware-provided or bundled tables describing hardware that cannot be discovered by probing: devices, addresses, interrupts, clocks and power domains.",
    d: "Platforms with non-discoverable devices pass a machine-readable description at boot: a tree of nodes with addresses, interrupt wiring, clocks, regulators, and properties, or a set of firmware tables with an interpreted control language for methods. The kernel parses it early to find memory, CPUs and interrupt controllers, then creates platform devices that drivers bind to by compatible-string. The same driver then works across boards that differ only in description. Overlays modify it at runtime. Correct interpretation of ambiguous or buggy descriptions is a long-lived source of quirks.",
    k: ["Static description tree vs. interpreted firmware methods: a tree is declarative and inspectable, methods allow firmware to hide hardware differences but run opaque code in the kernel.",
        "Description shipped with the kernel vs. supplied by firmware: bundling is controlled and testable, firmware-supplied lets one kernel image boot many machines."],
    p: ["Trusting a description's address ranges without bounds checks lets a bad table map over kernel memory.",
        "Interpreting firmware methods that sleep or loop forever at the wrong moment hangs boot."],
    v: "Boot with deliberately malformed and reordered descriptions; invalid entries are rejected with a log message, valid nodes create exactly the expected devices, and the same driver binds on two differing descriptions.",
    dep: ["firmware-handoff", "early-init", "device-model"],
  },
  "irq-subsystem": {
    s: "Routing hardware interrupts to handlers: controllers, vector allocation, masking, CPU affinity and the rules for what handler code may do.",
    d: "Devices raise interrupts to controllers that prioritize and deliver them to CPUs. The kernel abstracts controllers behind domains that translate hardware numbers into virtual interrupt numbers, supports edge and level triggering, message-signaled interrupts that are writes to memory addresses, and per-CPU interrupts. Handlers register with flags for sharing, and the core runs them with the line masked or acknowledged, then performs end-of-interrupt. Affinity steers interrupts to chosen CPUs, balancing load. Handlers must be short and must not sleep, so real work is deferred. Spurious and stuck interrupts must be detected and quelled.",
    k: ["Threaded handlers vs. hard-interrupt only: threaded handlers can sleep and be scheduled by priority, but add latency; hard handlers are fastest and tightly constrained.",
        "Shared vs. dedicated interrupt lines: sharing conserves lines on legacy hardware but forces each handler to check whether its device fired."],
    p: ["Failing to acknowledge a level-triggered interrupt leaves the line asserted and locks the CPU in an interrupt storm.",
        "Taking a sleeping lock in a hard handler deadlocks or triggers a scheduling-while-atomic crash."],
    v: "Generate high-rate interrupts from several devices while changing CPU affinity and offlining CPUs; none are lost or duplicated, interrupt counters per CPU follow affinity, and a stuck line is detected and disabled with a log message.",
    dep: ["interrupt-controller", "trap-entry", "deferred-work", "spinlocks"],
  },
  "deferred-work": {
    s: "Mechanisms for postponing the longer part of interrupt handling: softirqs, tasklets, and queued work run by kernel threads that may sleep.",
    d: "A hard interrupt handler does the minimum, then schedules the rest. Softirqs run right after the interrupt on the same CPU with interrupts enabled but preemption off, used for networking and block completion. Work queues hand a function to a pool of kernel threads, running in process context where sleeping and locks are allowed. Threaded timers and completion callbacks follow similar patterns. Choosing the right context matters: each has different latency, concurrency and sleep rules. The harder parts are bounding softirq time so it cannot starve user threads and ensuring work is flushed before teardown.",
    k: ["Softirq context vs. work queue threads: softirqs have minimal latency but cannot sleep, work queues can block but pay a context switch.",
        "Per-CPU bound workers vs. unbound workers: bound workers keep cache locality, unbound workers let the scheduler place long jobs on idle CPUs."],
    p: ["Freeing an object while queued work still references it runs the callback on freed memory.",
        "Softirq work that never yields starves ordinary threads on that CPU."],
    v: "Queue millions of deferred items from interrupts while unloading the owning driver; all items run or are cancelled before teardown, softirq time per CPU stays within its limit, and no callback touches freed memory.",
    dep: ["irq-subsystem", "per-cpu-data", "run-queues", "spinlocks"],
  },
  "dma-mapping": {
    s: "Preparing memory for transfers that devices perform directly: addresses the device can reach, cache coherence, bounce buffers and scatter-gather lists.",
    d: "Devices read and write memory without the CPU, using bus addresses that may differ from physical addresses and may be limited in range. The mapping interface allocates coherent buffers visible to both, or maps existing buffers for one transfer, producing addresses the device can use; where hardware cannot reach the memory, it uses a bounce buffer and copies. On systems without hardware coherence it flushes or invalidates caches around transfers. It also builds scatter-gather lists. With an IOMMU, mappings go through it. Direction hints let the implementation do only the necessary maintenance.",
    k: ["Streaming mappings per transfer vs. long-lived coherent buffers: streaming suits data buffers and lets caches work, coherent buffers suit descriptor rings that both sides touch constantly.",
        "Bounce buffering vs. restricting allocation zones: bouncing supports any memory but costs copies, allocating from reachable zones avoids copies but narrows choices."],
    p: ["Touching a buffer from the CPU while the device owns it produces stale or torn data.",
        "Forgetting to unmap a buffer leaks mappings and, with an IOMMU, leaves the device with access to freed memory."],
    v: "Run storage and network loads with a debug layer that tracks every mapping; no buffer is accessed in the wrong ownership state, all mappings are unmapped at teardown, and data verifies across bounce and direct paths.",
    dep: ["physical-allocator", "iommu", "device-model"],
  },
  "iommu": {
    s: "Hardware that translates and restricts device memory accesses, which the kernel programs to isolate devices and to remap addresses for virtualization.",
    d: "An input-output memory management unit sits between devices and memory and applies page tables per device or group, so a device can reach only buffers mapped for it. The kernel creates a domain per isolation unit, maps and unmaps buffers on request from the DMA layer, handles faults when a device accesses unmapped addresses, and invalidates cached translations when mappings change. It enables assigning a device directly to a guest, protects against buggy or malicious devices and DMA-capable ports, and lets devices use contiguous bus addresses over scattered memory. Costs are mapping overhead on hot I/O paths and isolation groups defined by bridge topology.",
    k: ["Strict per-transfer unmapping vs. deferred batch invalidation: strict closes the access window immediately, deferred invalidation is faster but leaves a brief window of stale access.",
        "Identity or pass-through mapping vs. full translation: pass-through avoids overhead for trusted devices, full translation gives isolation."],
    p: ["Devices behind the same bridge that cannot be isolated from each other must share a group; assigning one separately breaks isolation.",
        "Delaying invalidation lets a device keep writing to a page already given to another owner."],
    v: "Assign a device to an isolated domain and make it issue DMA outside its mappings; every access faults and is logged, legitimate transfers complete, and teardown leaves no mapping that remains reachable.",
    dep: ["dma-mapping", "page-tables", "pcie-bus", "irq-subsystem"],
  },
  "pcie-bus": {
    s: "Support for the dominant high-speed peripheral bus: configuration space, resource windows, message-signaled interrupts, link management and error reporting.",
    d: "Each device exposes a configuration space with identity, capabilities and base address registers the kernel sizes and programs. The bus is a tree of bridges and switches; the kernel assigns address windows through each and enables features such as message-signaled interrupts, extended capabilities, virtual functions that let one device appear as many, and peer-to-peer. It manages link speed and width, power states, and advanced error reporting including recovery of failed links, hot removal and reset sequences. Complexity comes from the number of optional capabilities and from quirks of devices that violate the specification.",
    k: ["Virtual functions for sharing devices vs. fully emulated devices: virtual functions give near-native performance with isolation, emulation is hardware-independent but slow.",
        "Native hotplug and error handling by the kernel vs. firmware-owned: kernel handling is flexible and uniform, firmware ownership is simple but opaque to the kernel."],
    p: ["Resetting a function that shares state with siblings disrupts them unless the whole group is reset.",
        "Enabling bus mastering before the device is configured lets it write to arbitrary memory."],
    v: "Hot-plug, reset and error-inject devices under load across a bridge tree; devices re-enumerate with correct resources, affected drivers recover or detach cleanly, and unaffected devices see no interruption.",
    dep: ["bus-enumeration", "irq-subsystem", "dma-mapping", "runtime-pm"],
  },
  "hotplug-events": {
    s: "Notifying user space when devices appear, change or disappear, so it can create device nodes, load modules and apply policy.",
    d: "On device registration, removal or state change, the kernel emits an event over a socket-like channel carrying the action and device attributes. A user-space device manager receives it, creates or removes device nodes, sets ownership and permissions, loads modules by alias, and runs rules. Early boot coldplug replays events for devices already present. Events are asynchronous and can arrive out of order or in bursts, so handlers must tolerate reordering; sequence numbers help. Kernel code must also handle removal of a device while it is being used, independent of any user-space action.",
    k: ["Kernel-emitted events with user-space policy vs. in-kernel node management: user-space policy is flexible and keeps naming out of the kernel, but needs a running manager early in boot.",
        "Ordered delivery vs. best effort: ordering simplifies handlers but serializes them, best effort is fast but demands idempotent handlers."],
    p: ["A burst of events overflows the channel's buffer and loses removals, leaving stale device nodes.",
        "Acting on an event for a device that has already gone away races with its replacement under the same name."],
    v: "Plug and unplug many devices rapidly during boot and runtime; device nodes exactly match present devices afterward, coldplug rebuilds the same set, and no event is lost under a burst.",
    dep: ["device-model", "driver-binding", "socket-layer"],
  },
  "system-suspend": {
    s: "Putting the whole machine into a low-power state and restoring it exactly: freezing tasks, quiescing devices, saving CPU state and resuming in reverse.",
    d: "Suspend freezes user tasks so none run during the transition, then walks the device tree in reverse dependency order calling each driver's suspend hook to stop activity and save state. Non-boot CPUs are taken offline, interrupts are disabled, final state is saved, and firmware enters the sleep state; memory stays powered or is written to storage for deeper hibernation. Resume reverses all of it, with wakeup sources able to abort an in-progress suspend. Any driver that fails to save or restore its hardware state breaks the whole transition, and errors appear only after resume.",
    k: ["Suspend to memory vs. to storage: memory resumes in a second and holds state powered, storage uses no power but is slow and needs space for the image.",
        "Freeze all tasks vs. quiesce only devices: freezing gives drivers a quiet system and simple reasoning, but a task that cannot be frozen aborts suspend."],
    p: ["A device suspended before one that depends on it hangs when the dependent tries a final transfer.",
        "A wakeup event arriving during suspend entry is lost unless the sequence checks pending wakeups late."],
    v: "Suspend and resume a thousand times with devices active and wakeups injected at random; every device works after resume, time continues correctly, and no data in flight is lost or duplicated.",
    dep: ["device-model", "smp-bringup", "wall-clock-discipline", "irq-subsystem", "idle-states"],
  },
  "idle-states": {
    s: "Choosing how deeply an idle CPU sleeps, trading exit latency for power saved, by predicting how long it will stay idle.",
    d: "When a CPU has nothing to run it enters an idle state; deeper states cut more power but take longer to leave and lose more state such as cache contents. A governor predicts the next wakeup using the nearest timer and the history of recent idle durations, and picks the deepest state whose entry cost and exit latency pay off. Timer ticks are stopped on idle CPUs so they sleep undisturbed. Latency requirements from drivers and applications cap the depth. Wrong predictions waste energy or add wakeup delay, and idle behavior interacts with load balancing.",
    k: ["Predict from timers and history vs. always the shallowest state: prediction saves much energy, but a wrong guess adds wakeup latency; shallow is safe and wasteful.",
        "Per-CPU idle decisions vs. coordinated cluster states: coordination enables deeper shared states but requires all CPUs to agree."],
    p: ["Entering a deep state just before an unexpected interrupt costs more energy and latency than staying shallow.",
        "Local timers lost in deep states must be handed to another clock or wakeups are missed."],
    v: "Run a light periodic workload while measuring package power and wakeup latency; time in deep states is high, latency stays under the declared constraint, and tightening the constraint shifts residency to shallow states.",
    dep: ["tick-management", "clock-events", "run-queues", "irq-subsystem"],
  },
  "frequency-scaling": {
    s: "Adjusting CPU frequency and voltage to match demand, saving power at low load and delivering speed on demand.",
    d: "Performance states set the pair of frequency and voltage each core runs at. A governor samples utilization reported by the scheduler and requests higher states when load rises, with hysteresis to avoid oscillation, or hardware performs the selection autonomously from hints. Policies cover performance, power saving, or schedule-driven balancing, and boost states exceed sustained limits until thermal budgets run out. Frequency affects how the scheduler measures capacity, so it informs load accounting. Mismatch between governor response and workload bursts makes interactive tasks slow or wastes power.",
    k: ["Scheduler-driven selection vs. periodic sampling: scheduler hooks react at the moment load changes, sampling is simpler but lags.",
        "Kernel-controlled vs. hardware-autonomous scaling: kernel control is transparent and policy-driven, hardware is faster and knows internal limits but is opaque."],
    p: ["Ramping up too slowly after an idle period makes bursty interactive work feel sluggish.",
        "Ignoring thermal limits while boosting causes throttling that is worse than steady moderate speed."],
    v: "Apply stepped and bursty loads and record frequency over time; frequency rises within a few milliseconds of load, falls when idle, power matches the policy's target, and thermal limits are never exceeded.",
    dep: ["run-queues", "thermal-control", "clock-events", "scheduling-policies"],
  },
  "runtime-pm": {
    s: "Powering down individual devices while the system runs, when they are idle, and powering them up transparently when used.",
    d: "Each device has a reference count of active users. When it drops to zero and an idle delay passes, the driver's suspend callback is called, and the device and eventually its parent bus or power domain are turned off. Any access first resumes the device, synchronously or asynchronously, restoring state; parents must resume before children. Drivers mark regions where they touch hardware and handle wakeup signaling. Power domains group devices that share a supply. Because resume sits on the access path, it adds latency and, if wrongly nested in interrupt or locking context, creates deadlocks.",
    k: ["Autosuspend with an idle delay vs. immediate suspend: a delay avoids thrash on bursty use, immediate saves more power but pays resume cost repeatedly.",
        "Asynchronous resume vs. synchronous: asynchronous fits atomic contexts, synchronous is simple to reason about but can block."],
    p: ["Unbalanced get and put counts leave a device permanently powered or power it off while in use.",
        "Resuming a device from a context that cannot sleep, when its parent requires sleeping, deadlocks."],
    v: "Exercise every device with idle gaps and random access bursts; each powers down after its delay, resumes on first use without error or data loss, and usage counters balance at the end.",
    dep: ["device-model", "deferred-work", "high-res-timers", "pcie-bus"],
  },
  "thermal-control": {
    s: "Reading temperatures and reducing heat output, by lowering frequency, spinning fans or shutting down, before hardware is damaged.",
    d: "Thermal zones read sensors and compare against trip points, each tied to cooling devices such as fans, frequency limits, and device throttles. A governor decides how much cooling each needs, using stepwise rules or a controller that tracks a target temperature. Passive cooling reduces performance and active cooling spends power. Crossing a critical trip forces a controlled shutdown. Sensors may be remote, shared or slow, and zones can share cooling devices. The loop must remain stable; delays between a throttle and its effect on temperature make naive controllers oscillate.",
    k: ["Stepwise trip tables vs. a feedback controller: tables are predictable and simple, a controller holds the temperature near its target with less performance loss.",
        "Kernel throttling vs. firmware-only protection: kernel policy is configurable, firmware protection is the safe backstop and cannot be disabled by software bugs."],
    p: ["A controller tuned without accounting for sensor delay oscillates, causing alternating throttling and overheating.",
        "Missing sensors reported as zero degrees disable cooling at the moment it is needed."],
    v: "Heat the system with a sustained load and a blocked fan; temperature plateaus at the target trip, cooling levels rise stepwise, performance degrades gradually, and exceeding the critical trip triggers an orderly shutdown.",
    dep: ["frequency-scaling", "device-model", "high-res-timers"],
  },
});
