// Details for the Operating System Kernel plate, part 2: resource control, virtual memory, filesystems.
ATLAS.details("os-kernel", {
  "namespaces": {
    s: "Per-process views of global resources such as process ids, mounts, network stacks and hostnames, which make a group of processes appear to own a private machine.",
    d: "A namespace wraps a global resource so that members see an independent instance. Separate kinds cover process ids, mount trees, network interfaces and routes, interprocess objects, user and group id mappings, hostnames and clocks. A task belongs to one namespace of each kind, inherited at creation or changed by explicit calls. Kernel code that used global variables must instead look up state via the task's namespace. Id mappings let a privileged identity inside map to an ordinary one outside. The difficulty is retrofitting every global structure and ensuring no path leaks a handle that crosses the boundary.",
    k: ["One namespace kind per resource vs. a single container object: independent kinds can be combined freely, a single object is simpler to reason about but less flexible.",
        "Mapping ids with a translation table vs. sharing raw ids: translation allows apparent root without real privilege, but every id crossing a boundary needs conversion."],
    p: ["A global lookup left behind in some path reveals or affects objects outside the namespace.",
        "Granting privilege over a namespace without checking who owns it lets a container administrator act on the host."],
    v: "Start a process in new process, mount and network namespaces; it sees itself as id 1, an empty mount tree and no host interfaces, and no host object is reachable through any call it can make.",
    dep: ["task-structures", "credentials", "mount-table", "socket-layer"],
  },
  "control-groups": {
    s: "A hierarchy that groups processes so that resource controllers can account for and limit their combined use of CPU, memory, I/O and more.",
    d: "Control groups form a tree whose nodes hold sets of tasks. Each controller attaches state to nodes and hooks into the subsystem it governs: scheduler, memory allocator, block layer, process count. Limits and weights set on a node apply to its whole subtree, and resource usage is charged up the tree. A unified hierarchy keeps all controllers on one tree. Configuration is exposed through a pseudo-filesystem. The cost is bookkeeping on hot paths such as page allocation and a hard problem of attributing shared resources, like cached pages, to exactly one group.",
    k: ["Single unified hierarchy vs. one hierarchy per controller: unified is easier to reason about and delegate, separate hierarchies allow independent groupings but conflict.",
        "Charging at allocation time vs. periodic sampling: charging is exact and enforces limits immediately, sampling is cheaper but can overshoot."],
    p: ["Moving a task between groups without migrating its charged pages leaves old groups billed for memory they no longer use.",
        "Deleting a group with live charges leaves orphaned accounting that never drains."],
    v: "Place a memory hog and a latency-sensitive service in sibling groups with limits; the hog is throttled or killed at its limit while the service's latency stays flat, and group counters sum to system totals.",
    dep: ["task-structures", "pseudo-filesystems", "cpu-memory-limits", "resource-pressure"],
  },
  "cpu-memory-limits": {
    s: "Enforcement of hard and soft caps on a group's CPU time and memory, including throttling, reclaim pressure and group-scoped out-of-memory handling.",
    d: "CPU controllers give groups shares of the fair scheduler or bandwidth quotas per period, throttling members when a quota runs out. Memory controllers track pages charged to each group; above a soft threshold the group's own pages are reclaimed first, and at the hard limit allocation fails or the group's out-of-memory path kills a member. Protection settings shield a group's working set from reclaim caused by others. Enforcement points sit in the scheduler tick and in the page allocator, so they must be cheap. Interplay between a limit and a shared page cache is the classic hard problem.",
    k: ["Hard cap vs. proportional share: caps give predictable ceilings but waste idle capacity; shares use all capacity but offer no firm bound.",
        "Kill within the group vs. global out-of-memory selection: group-scoped kills contain damage to the offender, global selection may sacrifice an innocent group."],
    p: ["Quota throttling that holds a lock-owning thread stalls unrelated groups waiting for that lock.",
        "Charging kernel memory such as page tables and object caches to nobody lets a group exceed its limit."],
    v: "Give a group a 50 percent CPU quota and a 1 GiB memory limit, then run saturating loads; measured CPU stays near 50 percent per period and the group never exceeds its memory limit, with kills confined to it.",
    dep: ["control-groups", "run-queues", "page-reclaim", "oom-handler"],
  },
  "resource-pressure": {
    s: "Measurement of how much time work is stalled waiting for CPU, memory or I/O, plus accounting of per-group usage, so overload can be detected early.",
    d: "Utilization numbers hide contention: a full CPU may be fine, but threads waiting for one is not. Pressure tracking records, per group and per resource, the fraction of time some or all runnable tasks were stalled, using state transitions at the scheduler, reclaim and I/O wait points, averaged over windows. Users read it through pseudo-files and can register triggers that wake them past a threshold, so a manager can shed load before the kernel kills anything. Accounting also records CPU time, memory and I/O per group. The challenge is cheap, per-CPU tracking that aggregates correctly.",
    k: ["Stall-time pressure vs. utilization counters: stall time directly measures lost work and anticipates trouble, utilization is simpler and always available but ambiguous.",
        "Polling counters vs. threshold triggers: triggers give prompt response without busy reading, but need kernel timers and poll infrastructure per registrant."],
    p: ["Updating shared counters with global locks on every stall transition adds contention to the scheduler's hottest path.",
        "Averages with long windows react too slowly, so a manager acts after the system has already thrashed."],
    v: "Induce memory thrash in one group; its memory pressure reaches high values within seconds, a registered trigger fires at the threshold, and an idle sibling group's figures stay near zero.",
    dep: ["control-groups", "page-reclaim", "run-queues", "event-polling"],
  },
  "address-space-layout": {
    s: "The kernel's description of each process's virtual memory: a set of regions with their permissions, backing objects and growth rules.",
    d: "An address space is a collection of regions, each a contiguous virtual range with a backing source (file, anonymous memory, shared object), permissions and sharing mode, kept in an ordered tree for lookup by address. Page faults look up the covering region to decide how to resolve them. Calls for mapping, unmapping, protecting and growing regions split, merge and remove entries, then update page tables and flush translations. Stacks grow on demand, heaps move by brk. Placement is randomized. A reader-writer lock protects it, and contention on that lock is a notorious multithreaded bottleneck.",
    k: ["Ordered tree of regions vs. a flat array: a tree gives logarithmic lookup and cheap split and merge, an array is cache-friendly but costly to edit.",
        "One address-space lock vs. per-region locking: a single lock is simple and correct; per-region locks let faults on different regions proceed in parallel but complicate merges."],
    p: ["Faulting while another thread unmaps the same range can map a page into a region that no longer exists.",
        "Guard gaps omitted between stack and neighbors let stack growth silently overwrite other mappings."],
    v: "Run threads that map, unmap, protect and fault at random on shared ranges for an hour; no fault resolves outside a live region, region counts balance, and the sanitizing build reports no lock-order violations.",
    dep: ["page-tables", "read-copy-update", "slab-allocator", "sleeping-mutexes"],
  },
  "page-tables": {
    s: "The hardware-walked, multi-level tables translating virtual to physical addresses, with permission and status bits, that the kernel builds and maintains for every address space.",
    d: "The CPU's memory management unit walks a tree of tables, each level indexed by a slice of the virtual address, ending in an entry holding the frame number and permission, cache and status bits (present, writable, user, accessed, dirty). The kernel allocates intermediate tables on demand, fills entries on faults, clears and frees them on unmap, and copies them on process duplication. It reads the accessed and dirty bits to drive reclaim and writeback. Kernel mappings are shared across all address spaces. Large address spaces require sparse trees; locking is split across table levels.",
    k: ["Split page-table locks per table vs. one per address space: split locks allow parallel faults, a single lock is simpler but serializes multithreaded memory operations.",
        "Eager vs. lazy table population on process duplication: lazy copying makes fork cheap but defers cost to faults; eager copying is predictable and heavy."],
    p: ["Clearing an entry without flushing the translation cache leaves another CPU writing through a stale mapping to a freed frame.",
        "Freeing a table page while a concurrent hardware walk or software lookup is still reading it causes corruption."],
    v: "Map, touch and unmap random ranges in many threads while forking; page-table page counters return to baseline, no stale-translation checker triggers, and accessed and dirty bits match actual use.",
    dep: ["physical-allocator", "tlb-management", "spinlocks"],
  },
  "tlb-management": {
    s: "Keeping the CPU's cached address translations consistent with page-table changes, including invalidating other CPUs through inter-processor interrupts.",
    d: "Translation lookaside buffers cache recent mappings and are not automatically coherent with page tables. After changing or removing a mapping, the kernel must invalidate the stale entries on every CPU that may have cached them: it tracks which CPUs ran the address space, sends inter-processor interrupts to flush, and waits for acknowledgment. To reduce cost it batches invalidations, flushes ranges rather than everything, uses address-space identifiers to avoid flushing on context switch, and may defer invalidation when safe. Shootdown cost grows with CPU count, and mistakes are rare, silent, catastrophic data corruption.",
    k: ["Immediate synchronous shootdown vs. batched or lazy flush: synchronous is simple and safe, batching amortizes interrupt cost but demands proof that stale entries are harmless meanwhile.",
        "Address-space identifiers vs. full flush on switch: identifiers keep entries warm across switches but need allocation and recycling logic."],
    p: ["Freeing a physical page before every CPU has flushed its stale mapping lets another process receive memory that is still writable through the old translation.",
        "Lazy tracking of which CPUs hold an address space can skip a CPU that still has entries."],
    v: "Unmap and reuse pages in a multithreaded process while threads on every CPU touch them; a checker that poisons freed pages never observes a write through a stale entry, and flush counters show batching working.",
    dep: ["page-tables", "address-space-layout", "smp-bringup", "irq-subsystem"],
  },
  "page-fault-handler": {
    s: "The routine run when a memory access cannot be translated or violates permissions; it decides to supply a page, copy one, deliver a signal or fail.",
    d: "On a fault the trap entry passes the address and cause. The handler finds the covering region, checks permissions, and resolves: allocate and zero a page for first touch of anonymous memory, read from the file via the page cache, bring back a swapped page, or copy a shared page on first write. If no region covers the address or access is forbidden, the thread receives a fault signal, or the kernel takes its recovery path if it faulted on a user copy. Many faults are resolved without sleeping; others wait for I/O. Concurrency with other faults and unmaps on the same range makes this the most intricate code in memory management.",
    k: ["Copy on write for private mappings vs. eager copying: lazily copying makes fork and shared data cheap, but each first write takes a fault.",
        "Fault-around mapping neighboring file pages vs. one page per fault: mapping several cuts fault counts for sequential access but wastes work on sparse access."],
    p: ["Faulting in an interrupt or while holding a lock the handler needs deadlocks the kernel.",
        "Racing a copy-on-write fault with a concurrent write through a pinned mapping can lose writes."],
    v: "Touch a large sparse mapping, fork, write in parent and child, then swap under pressure; contents always match expectations, fault counters by type match the workload, and invalid accesses produce exactly one fault signal.",
    dep: ["trap-entry", "address-space-layout", "page-tables", "physical-allocator", "page-cache", "swap"],
  },
  "memory-mapping": {
    s: "The interface to place files, shared objects or anonymous memory into an address space, with permissions, sharing mode and advice about expected use.",
    d: "A map call creates a region backed by a file range, anonymous memory or a device, either shared (writes reach the object) or private (copy on write). Pages are not read until first touched, so mapping a huge file costs nothing up front. Related calls change protections, release ranges, lock pages in memory, synchronize dirty data and give advice on access patterns. Executables and shared libraries are loaded this way. The kernel must handle files shrinking under a mapping, keep mappings coherent with ordinary reads and writes through the page cache, and bound total mapped memory.",
    k: ["Mapped access vs. read and write calls: mapping avoids a copy and a call per access, but faults are expensive and I/O errors arrive as signals.",
        "Overcommit allowed vs. strict accounting: overcommit supports sparse use cheaply but may need to kill later; strict accounting fails early and wastes reserved memory."],
    p: ["A file truncated while mapped leaves pages beyond the end, so touching them must raise an error rather than reading freed storage.",
        "Writable shared mappings of files can dirty pages faster than writeback can keep pace."],
    v: "Map a file, write through the mapping, truncate from another process and read via ordinary calls; contents agree, access past the new end faults cleanly, and data reaches storage after synchronization.",
    dep: ["address-space-layout", "page-cache", "page-fault-handler", "vfs-layer"],
  },
  "physical-allocator": {
    s: "The manager of physical page frames, handing out contiguous blocks by size, per memory node and zone, while fighting fragmentation.",
    d: "Physical memory is divided into frames tracked by a descriptor array. A buddy allocator keeps free lists per power-of-two block size, splitting larger blocks on demand and merging freed neighbors. Memory is organized in zones reflecting device addressing limits, and in nodes reflecting hardware locality. Per-CPU lists of single pages avoid lock contention on the common path. Watermarks trigger background reclaim before memory runs out. Requests carry flags saying whether they may sleep, reclaim or dip into reserves. Long-lived unmovable allocations scatter and make large contiguous blocks unobtainable, a persistent problem.",
    k: ["Buddy blocks vs. a simpler bitmap: buddy gives fast splitting and merging of aligned blocks but internal fragmentation, a bitmap is compact but slow for large requests.",
        "Grouping pages by mobility vs. ignoring it: grouping keeps movable and unmovable pages apart so compaction can work, at added complexity."],
    p: ["Allocating with a flag that may sleep from interrupt context hangs the machine.",
        "Memory reserves drained by ordinary requests leave no frames for reclaim itself, so the system deadlocks trying to free memory."],
    v: "Allocate and free random block sizes from all CPUs for hours; free-list counts return to baseline, a final large contiguous allocation succeeds after compaction, and no frame appears in two owners.",
    dep: ["early-allocator", "per-cpu-data", "spinlocks", "page-reclaim"],
  },
  "slab-allocator": {
    s: "The allocator for small, frequently created kernel objects, caching initialized objects per type and per CPU to be fast and compact.",
    d: "Kernel code constantly allocates structures of a few dozen to a few thousand bytes. A slab allocator keeps a cache per object type, carving pages into fixed-size slots. Each CPU has a current slab and a local free list, so most allocations and frees are lock-free pointer operations. Partial slabs are shared, and fully empty ones are returned to the page allocator under pressure. Debug builds add redzones and poisoning. Hardening may randomize freelists. Concerns are fragmentation, cache and node locality, memory charged to groups, and use-after-free bugs, which this allocator's reuse makes exploitable.",
    k: ["Per-type caches vs. general size-class buckets: per-type caches pack tightly and keep objects initialized, buckets are simpler and serve unpredictable sizes.",
        "Per-CPU free lists vs. a shared list: per-CPU lists avoid locks and bounce, but memory freed on another CPU needs a slower return path."],
    p: ["Freeing an object to the wrong cache or twice corrupts the free list and shows up much later in unrelated code.",
        "Allocating large buffers from small-object caches fragments memory and prevents slabs from being returned."],
    v: "Allocate and free millions of objects from all CPUs with poisoning and redzone checks enabled; no corruption report appears, memory held by the caches shrinks after load stops, and leak checks report zero.",
    dep: ["physical-allocator", "per-cpu-data", "atomics-and-barriers"],
  },
  "page-cache": {
    s: "Memory holding recently used file contents, shared by file reads, writes and mappings, so repeated access avoids storage.",
    d: "File data is cached in page-sized units indexed by file and offset. Reads check the cache first and on a miss allocate a page and ask the filesystem to fill it, often reading ahead when access looks sequential. Writes modify cached pages and mark them dirty for later writeback. Memory mappings use the same pages, so all access paths see one copy. The cache uses nearly all free memory and shrinks under pressure through reclaim. It also caches metadata and device blocks. Hard problems include eviction policy quality, readahead tuning, and keeping dirty data bounded.",
    k: ["Unified page cache for mappings and reads vs. separate buffers: unified avoids double caching and coherence bugs, separate buffers are simpler per layer but waste memory.",
        "Write-back vs. write-through: write-back absorbs bursts and merges writes, but loses recent data on power failure; write-through is safe and slow."],
    p: ["Readahead on a random-access workload floods the cache with useless pages and evicts the working set.",
        "Letting dirty pages grow unbounded stalls the whole system once memory fills with data that cannot be freed quickly."],
    v: "Read a large file twice; the second pass runs at memory speed and issues no device reads. Under a memory-limited run the working set stays resident while streamed data is evicted first.",
    dep: ["physical-allocator", "vfs-layer", "writeback", "page-reclaim"],
  },
  "page-reclaim": {
    s: "Background and direct work that frees memory by evicting cold cache pages, writing out dirty ones and swapping anonymous memory, guided by recency estimates.",
    d: "When free memory falls below a watermark a reclaim thread scans lists of pages ordered by approximate recency, using the accessed bit in page tables, and frees the coldest. Clean file pages are dropped, dirty ones are written first, and anonymous pages go to swap if available. Allocations that cannot wait perform direct reclaim themselves, stalling the caller. Separate lists for file and anonymous pages let the kernel prefer cheaper victims. Per-group limits scope the scan. Reverse mappings find all page tables referencing a frame. Policy errors cause thrashing: evicting what is about to be used.",
    k: ["Approximate recency lists vs. exact least-recently-used: approximation is cheap with the accessed bit, exact tracking would require instrumenting every access.",
        "Prefer dropping file pages vs. swapping anonymous memory: files are cheap to rebuild, but over-favoring them evicts hot program code and data."],
    p: ["Scanning too slowly lets allocations stall in direct reclaim, producing multi-second freezes under load.",
        "Reclaim that needs memory to write pages out can deadlock without reserved resources for the I/O path."],
    v: "Run a workload with a working set slightly under memory size plus a streaming reader; hot pages stay resident, major-fault rate stays low, and direct-reclaim stall time stays near zero.",
    dep: ["page-cache", "swap", "writeback", "page-tables", "physical-allocator"],
  },
  "swap": {
    s: "Using storage as a backing store for anonymous memory, so rarely used pages can leave RAM and return on demand.",
    d: "Anonymous pages have no file, so when reclaimed they are written to a swap area on a device or file, and the page-table entry is replaced with a marker recording where. A later fault reads the page back. Swap slots are allocated with attention to locality, and a swap cache avoids duplicate I/O while a page is in flight. Compressed in-memory swap trades CPU for avoiding storage. Swapping allows overcommit and moves idle memory out, but heavy swapping makes latency collapse. Encrypting swap protects secrets written to disk, and the system must bound swap exhaustion.",
    k: ["Disk swap vs. compressed memory swap: disk gives large capacity at high latency, compression is fast but consumes RAM and holds less.",
        "Eager vs. lazy swap slot allocation: eager reserves guarantee space but waste it, lazy defers decisions and risks running out during reclaim."],
    p: ["A page-table marker misread after process duplication or remap returns another page's data.",
        "Unencrypted swap on persistent storage leaves keys and passwords on disk after power off."],
    v: "Force a process far past RAM size, then verify every page's contents on re-read; no mismatches occur, swap-slot counts return to zero after the process exits, and latency stays bounded by device speed.",
    dep: ["page-reclaim", "page-tables", "bio-requests", "page-fault-handler"],
  },
  "huge-pages": {
    s: "Mapping memory in much larger units than the base page, to cut translation cache misses and page-table overhead for big working sets.",
    d: "A large page covers megabytes instead of kilobytes with one translation entry, so far fewer cache entries cover the same memory and page walks are shorter. Applications can request them explicitly from a reserved pool, or the kernel can transparently promote runs of base pages when contiguous frames are available and demote them when partial operations such as protection changes need it. Benefits are largest for databases and virtual machines. Costs include fragmentation, zeroing latency on first touch, memory bloat from sparse use, and compaction work to create contiguous blocks.",
    k: ["Reserved pool vs. transparent promotion: reserved pools are predictable and cannot fragment away, transparent promotion needs no application changes but its latency and availability vary.",
        "Splitting large mappings on partial operations vs. forbidding them: splitting keeps semantics identical, forbidding is simpler but breaks ordinary calls."],
    p: ["Compaction running in the allocation path produces unpredictable latency spikes for the requesting thread.",
        "Promoting sparsely used regions inflates resident memory several-fold with zero-filled pages."],
    v: "Run a large random-access benchmark with and without large pages; translation-miss counters drop substantially and run time improves, while resident memory for a sparse test stays within a small factor of use.",
    dep: ["page-tables", "physical-allocator", "tlb-management", "page-fault-handler"],
  },
  "oom-handler": {
    s: "The last-resort path when reclaim cannot free enough memory: select and kill a process to restore forward progress.",
    d: "When an allocation cannot be satisfied despite reclaim, the kernel either fails it or invokes a victim selection routine. It scores each candidate by memory use adjusted by priority hints and protections, kills the worst offender and its sharing relatives, and lets the freed memory satisfy waiters. The selection must itself run with almost no memory, avoid picking essential system processes, and ensure the victim actually exits and releases memory, even if blocked in uninterruptible wait. Group-scoped variants confine the choice. User-space daemons can act earlier using pressure signals.",
    k: ["Kernel-selected victim vs. earlier user-space policy: kernel selection is always available and fast, user-space policy knows which services matter but may itself be starved.",
        "Kill largest vs. kill by priority hint: largest frees most memory quickly, hints protect critical services but may require more kills."],
    p: ["Killing a process stuck in an uninterruptible wait frees nothing, so the system hangs while memory is still short.",
        "Repeated kills of unrelated small processes that do not hold the memory leave the real hog running."],
    v: "Run a memory hog with a protected critical service present; the hog is chosen within seconds, the service survives, the log records the scoring, and the system returns to normal free memory.",
    dep: ["page-reclaim", "task-structures", "signals", "control-groups"],
  },
  "vfs-layer": {
    s: "The common abstraction every filesystem plugs into: uniform objects and operations for files, directories and mounts, so programs see one namespace.",
    d: "The virtual file system defines generic objects (superblock, inode, directory entry, open file) and tables of operations each concrete filesystem fills in. System calls for open, read, write, rename and list go through it: it resolves paths, performs permission checks, manages caches, and calls the filesystem only for what it cannot answer. It owns locking order across directories, which is critical for rename. Features such as mounting, access control lists and extended attributes are expressed generically. Its job is hard because filesystems have wildly different semantics yet must obey one contract.",
    k: ["Rich generic layer vs. thin passthrough: a rich layer shares caching and locking logic, a thin one lets each filesystem optimize but duplicates complex code.",
        "Object tables of function pointers vs. a fixed feature set: tables allow new filesystems without core changes but make semantics depend on every implementation."],
    p: ["Inconsistent lock ordering between rename and lookup causes rare directory-tree deadlocks.",
        "A filesystem returning a partial result without errors breaks callers that assume the layer enforces the contract."],
    v: "Run a conformance suite against every mounted filesystem type covering open, rename, link, unlink races and permission cases; results match the specified semantics and a concurrent stress run produces no lock warnings.",
    dep: ["path-lookup", "dentry-inode-caches", "permission-checks", "page-cache", "mount-table"],
  },
  "path-lookup": {
    s: "Turning a path string into a file object by walking components through directories, mounts and symbolic links, with permissions checked at each step.",
    d: "Resolution starts at the root or working directory and processes one component at a time: check search permission, find the child in the directory cache (or ask the filesystem on a miss), follow symbolic links up to a depth limit, and cross into a mounted filesystem when reaching a mount point. The common case runs without locks or reference counts, using sequence counters to detect concurrent changes and fall back to a slower careful walk. Options restrict following of links or leaving a subtree. It is performance critical, as every file operation begins here, and subject to races with rename.",
    k: ["Lockless walk with fallback vs. always taking references: lockless is much faster for hot paths but needs retry logic, reference walking is simple but contends on shared counters.",
        "Following symbolic links in the kernel vs. leaving it to user code: kernel following is atomic and compatible, but adds loops and limits to guard."],
    p: ["A directory renamed during a walk can redirect it outside the intended subtree unless the walk detects the change.",
        "Unbounded link chains or loops exhaust stack or time without a depth limit."],
    v: "Resolve millions of paths from all CPUs while renaming directories and swapping links; results are always one of the valid states, never an error from a race, and a sandboxed-root test cannot escape its subtree.",
    dep: ["dentry-inode-caches", "permission-checks", "mount-table", "read-copy-update"],
  },
  "dentry-inode-caches": {
    s: "In-memory caches of directory entries and file metadata that make name lookups and attribute queries fast, including negative entries for names that do not exist.",
    d: "A directory entry cache maps a parent and name to a child object and remembers failed lookups as negative entries. An inode cache holds file metadata and links to its cached data pages. Both are hash-indexed, reference counted, and kept on least-recently-used lists so reclaim can shrink them when memory is tight; pruning must preserve entries that are in use. They are the working set of any file-heavy system. Dropping a directory entry and its inode interacts with open files, hard links and deletion: storage is released only after the last name and last open reference are gone.",
    k: ["Caching negative lookups vs. not: negative entries speed repeated misses such as library search, but unbounded misses on random names can consume memory.",
        "Separate size limits vs. shrinking under global pressure: fixed limits are predictable, pressure-driven shrinking uses idle memory but can evict hot entries abruptly."],
    p: ["Reclaiming an entry that a concurrent lookup just obtained causes use-after-free unless reference counts or sequence checks guard it.",
        "Delete on last close mishandled leaks storage for unlinked-but-open files after a crash."],
    v: "Create and remove millions of files and probe names that do not exist under memory pressure; cache sizes stay bounded, hit rates are high for hot paths, and unlinked-open files free space on close.",
    dep: ["vfs-layer", "slab-allocator", "page-reclaim", "read-copy-update"],
  },
  "mount-table": {
    s: "The graph of attached filesystems and where each appears in the namespace, with options, propagation rules and per-namespace views.",
    d: "Mounting attaches a filesystem instance at a directory of another so that path walks cross into it. The mount table records each attachment with options (read-only, no execution of programs, no device nodes), supports bind mounts that expose a subtree elsewhere, and moves or detaches mounts. Propagation settings control whether mounts made in one place appear in copies of that tree, which containers rely on. Each mount namespace has its own tree. Unmounting must wait for users, with a lazy mode that detaches immediately. It also is where pivoting to a new root during boot happens.",
    k: ["Shared propagation of mount events vs. fully private mounts: sharing keeps related trees consistent automatically, private mounts isolate but need explicit setup.",
        "Immediate vs. lazy unmount: immediate fails if busy and is predictable, lazy always detaches but leaves running users on an unreachable tree."],
    p: ["Mounting over a directory that open files or working directories reference creates confusing hidden-state behavior.",
        "Propagation loops between peer groups can recurse or leak mounts into containers."],
    v: "Build nested bind mounts with different propagation modes across two namespaces; mount events appear exactly where specified, read-only flags are honored on every path to the data, and unmount succeeds once users close.",
    dep: ["vfs-layer", "namespaces", "dentry-inode-caches", "init-sequence"],
  },
  "disk-filesystem": {
    s: "A concrete on-storage format: how files, directories, free space and metadata are laid out in blocks, and the code that reads, writes and allocates them.",
    d: "A filesystem organizes a block device into metadata (superblock, allocation maps, inode tables, directory structures) and file data, commonly mapped by extents rather than block lists. It implements the operation tables the VFS expects: lookup in a directory, create, allocate blocks for growth, truncate, and read or write pages through the cache. Allocation policy matters: keeping a file contiguous and near its directory reduces seeks, delayed allocation batches decisions. Hard are scaling to billions of files, concurrent updates, free space fragmentation, and keeping all structures consistent through crashes.",
    k: ["Extent mapping vs. per-block pointers: extents are compact and fast for large files, pointer lists are simple but costly for big sequential data.",
        "Delayed allocation vs. immediate: delaying yields better layout and fewer fragments, but data in the cache has no storage promised and can fail later when the space is gone."],
    p: ["Allocating from free-space maps without locking per region serializes all writers on one lock.",
        "Metadata that references blocks before their contents are durable exposes stale data after a crash."],
    v: "Create, grow, truncate and delete random files from many threads, then run the filesystem's offline checker; it reports no inconsistency, free space matches the sum of files, and read-back contents are identical.",
    dep: ["vfs-layer", "page-cache", "bio-requests", "journaling-recovery", "writeback"],
  },
  "journaling-recovery": {
    s: "Making filesystem updates survive crashes by logging intended changes first, or by never overwriting live data, so recovery is quick and consistent.",
    d: "A multi-step update such as creating a file touches several structures; a crash in between would leave them inconsistent. A journal records the changes in a log region first and commits them as a transaction with a barrier, applying them in place afterward. After a crash, replay completes committed transactions and discards partial ones. Modes differ in whether file data is also logged. Copy-on-write designs avoid the log by writing new versions and switching a root pointer atomically. Both depend on storage honoring flush ordering and bound recovery time.",
    k: ["Metadata-only journaling vs. full data journaling: metadata-only is fast and keeps structure consistent, but file contents may be stale after a crash; full journaling writes everything twice.",
        "Journal vs. copy-on-write: a journal updates in place and keeps layout stable, copy-on-write gives snapshots and checksums but fragments over time."],
    p: ["A device that reorders or acknowledges writes before they are durable breaks commit ordering and corrupts after power loss.",
        "A journal that fills faster than it drains stalls every update in the system."],
    v: "Cut power or kill the virtual machine at random points during a heavy metadata workload, a thousand times; every mount recovers within bounded time, the checker finds no damage, and committed files are intact.",
    dep: ["disk-filesystem", "bio-requests", "writeback", "page-cache"],
  },
  "writeback": {
    s: "The background flushing of dirty cached data to storage, pacing writers so memory is not flooded and data reaches disk within a bounded time.",
    d: "Dirty pages and metadata accumulate in the page cache. Flusher threads wake periodically and when dirty thresholds are crossed, selecting the oldest dirty files, asking the filesystem to write them, and marking pages clean on completion. Writers that dirty memory faster than storage can absorb are throttled in proportion to the share they produce, so one heavy writer cannot starve others. Sync calls force specific files out and wait. Per-device tracking avoids a slow disk stalling writers to a fast one. Getting the balance wrong yields either lost data on crash or latency storms.",
    k: ["Background flushing at thresholds vs. synchronous write-through: thresholds let writes complete at memory speed and batch for efficiency, at the cost of a data-loss window.",
        "Throttling writers by device bandwidth vs. a global dirty limit: per-device pacing is fair, but needs bandwidth estimates that can lag changes."],
    p: ["Throttling a thread while it holds a filesystem lock blocks all other users of that lock.",
        "Ignoring failed writes marks pages clean so the application never learns its data was lost."],
    v: "Run a fast and a slow device with concurrent heavy writers; each is throttled to its device's speed, the dirty page count stays under the limit, and an injected write error is reported on the next sync.",
    dep: ["page-cache", "bio-requests", "tick-management", "disk-filesystem"],
  },
  "pseudo-filesystems": {
    s: "Filesystems with no storage, which present kernel state and controls as files and directories, or hold data purely in memory.",
    d: "Some filesystems generate their contents when read. A process-information tree shows each task's state, memory maps and descriptors; a device-information tree shows the device model; a control tree configures control groups. Others are memory-backed: a temporary filesystem keeps files in the page cache and swap, with no disk. Text is produced by callbacks on read and parsed on write, so these files become the kernel's wide, scriptable control surface. Because they are interfaces, their formats become ABI, and their read paths must be safe against objects that vanish mid-read.",
    k: ["Text files for state vs. binary structures: text is easy to script and inspect, binary is compact and precise but needs tools and versioning.",
        "Per-open snapshot vs. generating on demand per read: snapshots give consistent reads of large listings, on-demand generation uses less memory but may tear."],
    p: ["Dumping kernel pointers or secrets through a world-readable file leaks information that defeats hardening.",
        "A listing generated while objects are removed can dereference freed entries unless iteration holds the right references."],
    v: "Read the process tree thousands of times while creating and killing processes; no read fails or crashes, listings are consistent per read, and an unprivileged user cannot read restricted entries.",
    dep: ["vfs-layer", "page-cache", "swap", "permission-checks"],
  },
  "file-locking": {
    s: "Advisory and mandatory-style locks on files and byte ranges that let cooperating programs coordinate access, with deadlock detection and ownership by process or open file.",
    d: "Programs coordinate access to shared files with locks. Whole-file locks are tied to open file objects; byte-range locks are owned by process and are released when the process closes any descriptor to the file, a notorious surprise. Newer open-file-description locks fix that. Locks may be shared or exclusive, are normally advisory, and blocked requests sleep with deadlock detection by walking wait-for chains. Leases notify holders when someone else wants the file. The kernel keeps lock lists per inode and must release locks on close and exit, including across network filesystems.",
    k: ["Process-owned vs. open-file-owned locks: process ownership matches old standards, open-file ownership behaves predictably across threads and descriptor duplication.",
        "Advisory only vs. enforced by read and write: advisory is cheap and universal, enforcement protects against ill-behaved programs but burdens every I/O call."],
    p: ["Closing an unrelated descriptor to the same file silently drops a process's range locks.",
        "Deadlock detection that misses cycles across multiple files leaves processes asleep forever."],
    v: "Run many processes taking overlapping shared and exclusive ranges in random order; no two exclusive holders overlap, a constructed cycle returns a deadlock error to one waiter, and killed holders release their locks.",
    dep: ["vfs-layer", "dentry-inode-caches", "futex-wait-queues", "task-structures"],
  },
});
