// Details for the Operating System Kernel plate, part 4: synchronization, time, observability, modules.
ATLAS.details("os-kernel", {
  "atomics-and-barriers": {
    s: "Indivisible read-modify-write operations and ordering fences, the primitives from which every lock and lock-free structure is built.",
    d: "Hardware offers atomic operations such as compare-and-swap, fetch-and-add and load-linked/store-conditional, plus barriers that constrain how loads and stores may be reordered by the compiler and CPU. The kernel wraps them in a portable API with ordering variants: relaxed, acquire, release and full. Reference counts, flags, lock words and sequence counters rest on them. Correct use requires reasoning under a weak memory model where one CPU may observe another's writes out of order. Bugs are timing dependent, appear only on some hardware, and are nearly impossible to reproduce on demand.",
    k: ["Weakest sufficient ordering vs. full barriers everywhere: weaker ordering is faster on many CPUs but demands precise reasoning, full barriers are safe and costly on hot paths.",
        "Lock-free algorithms vs. locked code: lock-free avoids blocking and priority problems, but is much harder to prove correct and to extend."],
    p: ["A missing barrier between publishing a pointer and initializing its target lets another CPU read uninitialized fields.",
        "Compare-and-swap loops without handling the ABA problem succeed on a recycled object that has changed meaning."],
    v: "Run litmus tests for each primitive on every supported CPU family under a memory-model checker and stress them for hours; no forbidden outcome ever appears and reference counts never go negative.",
    dep: [],
  },
  "spinlocks": {
    s: "Locks that busy-wait for ownership, usable in interrupt context, for short critical sections that must never sleep.",
    d: "A spinlock is a word that a CPU acquires atomically and releases with a store; contenders loop until free. Because holders may not sleep, acquiring one disables preemption, and if interrupt handlers also take it, interrupts too. Fairness designs, such as ticket or queue locks, prevent starvation and reduce cache-line bouncing under contention. Critical sections must be short and cannot call anything that sleeps. On a single CPU build they reduce to disabling preemption. Excess contention on one lock is the classic scalability wall, answered by splitting locks or avoiding them.",
    k: ["Ticket or queued locks vs. simple test-and-set: queued locks give fairness and local spinning at modest cost, test-and-set is smallest and collapses under contention.",
        "Disable interrupts while held vs. not: required when handlers share the lock, otherwise wasteful since it delays interrupts."],
    p: ["Taking a lock in thread context with interrupts enabled that an interrupt handler also takes deadlocks when the interrupt arrives on the same CPU.",
        "Holding a spinlock across anything that may sleep lets another CPU spin forever."],
    v: "Hammer a lock from all CPUs with interrupts also contending; the lock validator reports no inversion, mutual exclusion holds in a checked counter test, and the worst wait time stays bounded.",
    dep: ["atomics-and-barriers"],
  },
  "sleeping-mutexes": {
    s: "Locks that put the waiting thread to sleep, suited to longer critical sections in process context, with optimistic spinning and priority inheritance.",
    d: "When a thread fails to take a mutex it queues and sleeps until the holder releases and wakes it, letting the CPU run other work. Because holders may themselves sleep, critical sections can include allocation and I/O. Optimistic spinning briefly polls if the holder is running on another CPU, avoiding sleeps for short holds. Real-time variants implement priority inheritance: a low-priority holder is boosted to the priority of the highest waiter. Mutexes cannot be used in interrupt context and must be released by their owner. Fairness versus throughput on handoff is the tuning issue.",
    k: ["Spin briefly then sleep vs. sleep immediately: spinning wins when holds are short and the holder is running, sleeping saves CPU when holders block.",
        "Priority inheritance vs. none: inheritance bounds inversion for real-time tasks at the cost of chain tracking, none is simpler but allows unbounded delay."],
    p: ["Acquiring a sleeping lock in a context that cannot sleep triggers a scheduling-while-atomic bug.",
        "Two locks taken in opposite orders on two paths deadlock rarely and unrepeatably."],
    v: "Run threads at differing priorities contending on mutexes with a medium-priority CPU hog; the high-priority thread's wait is bounded by the hold time, and the lock validator reports no cycles.",
    dep: ["atomics-and-barriers", "futex-wait-queues", "run-queues"],
  },
  "rw-locks-seqlocks": {
    s: "Locks optimized for read-mostly data: reader-writer locks admit many readers, and sequence locks let readers proceed without writing and retry if a writer intervened.",
    d: "A reader-writer lock lets any number of readers hold it together but excludes writers; the cost is that every reader still modifies the shared lock word, bouncing a cache line. A sequence lock gives writers a counter that is odd while writing; readers read the data and the counter before and after, retrying if it changed or was odd. Readers take no lock and never block writers, so writers cannot starve, but readers may loop and cannot follow pointers safely. Suited to small, simple, frequently read data like the time of day.",
    k: ["Sequence lock vs. reader-writer lock: sequence locks scale perfectly for readers but suit only small copyable data, reader-writer locks protect arbitrary structures at a bouncing cost.",
        "Reader preference vs. writer preference: reader preference maximizes throughput but can starve writers, writer preference bounds update latency."],
    p: ["A reader following a pointer inside a sequence-lock section may dereference memory the writer just freed.",
        "Upgrading from reader to writer while holding read access deadlocks when two readers try at once."],
    v: "Run writers updating a multiword value while many readers read it; no reader ever observes a torn combination, writers make progress under maximum reader load, and retry counts stay low.",
    dep: ["atomics-and-barriers", "spinlocks"],
  },
  "read-copy-update": {
    s: "A scheme where readers take no locks and writers publish new versions, then free the old one only after every pre-existing reader has finished.",
    d: "Readers access a structure through a pointer inside a read-side section that costs almost nothing. A writer builds a modified copy, publishes it with a single pointer store, then waits for a grace period, a time by which every CPU has passed through a quiescent state such as a context switch, before freeing the old version. It can wait synchronously or register a callback. The result is near-zero read overhead for lists, route tables and directory caches. It requires that readers never sleep inside the section (or use a variant that allows it), and tracking grace periods across many CPUs is intricate.",
    k: ["Deferred callbacks vs. waiting for the grace period: callbacks keep writers fast but accumulate pending memory, waiting is simple but blocks the writer.",
        "Non-preemptible read sections vs. preemptible ones: non-preemptible is cheapest, preemptible permits long sections and real-time use but needs per-task tracking."],
    p: ["A reader that sleeps in a non-sleepable section stalls grace periods and the memory they hold back grows without bound.",
        "A writer updating in place instead of publishing a copy exposes readers to half-modified data."],
    v: "Run readers walking a list while writers replace and free nodes at high rates, with poisoning of freed memory; readers never see poison, callback backlog stays bounded, and grace periods complete within expected time.",
    dep: ["atomics-and-barriers", "per-cpu-data", "context-switch", "tick-management"],
  },
  "per-cpu-data": {
    s: "Variables with a separate instance per CPU, so the common case needs no lock and no cache-line sharing.",
    d: "Counters, free lists, run queues and statistics are allocated one copy per CPU, reached through a base register or table, so code touches only its own copy. Access is safe only while the thread cannot be preempted or migrated, so users disable preemption briefly or use operations that are atomic with respect to the local CPU. Aggregation sums copies on demand and tolerates slight inconsistency. Dynamic allocation and CPU hotplug require creating and freeing copies. The tradeoffs are memory multiplied by CPU count and the effort of merging results for global views.",
    k: ["Per-CPU copies vs. one atomic shared counter: per-CPU copies avoid all contention but memory scales with CPU count and exact reads are costly.",
        "Preemption disable around access vs. restartable sequences: disabling is simple but hurts latency, restartable sequences allow preemption with retry."],
    p: ["Being migrated to another CPU between getting the address and using it modifies the wrong CPU's copy.",
        "Reading an aggregated total as if exact produces wrong decisions, such as exceeding a limit."],
    v: "Update per-CPU counters from all CPUs while hot-plugging CPUs; the final sum equals the number of increments performed, there are no preemption-related warnings, and offlined CPUs' counts are preserved.",
    dep: ["atomics-and-barriers", "early-init"],
  },
  "futex-wait-queues": {
    s: "The kernel waiting machinery: queues where threads sleep until a condition holds, plus the fast user-space lock primitive that enters the kernel only on contention.",
    d: "A wait queue holds sleeping threads for an event; waker code walks the list and makes them runnable. The standard pattern marks the thread as sleeping, rechecks the condition, then yields, so a wakeup between check and sleep is not lost. The fast user-space mutex builds on this: the lock word lives in user memory, uncontended acquire and release use atomics without a call, and only a contended waiter asks the kernel to sleep on the address, or a releaser asks to wake it. Kernel hash buckets keyed by address hold waiters. Supports timeouts, priority inheritance and requeueing to avoid herds.",
    k: ["User-space lock word with kernel assistance vs. kernel-only locks: user-space words make the uncontended case free, kernel-only locks are simpler but cost a call on every use.",
        "Wake one vs. wake all: waking one avoids a thundering herd, waking all is simpler but wasteful."],
    p: ["Checking the condition after joining the queue in the wrong order loses a wakeup and sleeps forever.",
        "Sleeping on an address in memory that is unmapped or remapped by another thread wakes the wrong waiters."],
    v: "Run a lock contention benchmark with thousands of threads and random timeouts; no thread is stuck forever, uncontended acquisitions show zero kernel entries in a trace, and wake counts match waits.",
    dep: ["atomics-and-barriers", "run-queues", "user-memory-access", "task-structures"],
  },
  "lock-validator": {
    s: "A debugging engine that records lock acquisition order and context, and reports potential deadlocks from a single run, before they actually happen.",
    d: "The validator maps every lock to a class and records the dependency graph of which classes were taken while holding others, along with interrupt and preemption contexts. When a new acquisition would close a cycle, or take a lock in a context that conflicts with how it was used elsewhere, it reports the chain with stack traces, even though no deadlock occurred. Because it checks orders rather than timing, one run covers all interleavings of the paths exercised. The cost makes it a development and testing tool. Annotations are needed for legitimate nested use of locks in the same class.",
    k: ["Class-based checking vs. per-instance checking: classes scale to millions of locks and generalize, but need annotations for legitimate same-class nesting.",
        "Enabled in test builds only vs. production: it is far too slow for production, but disabling means rare ordering bugs ship."],
    p: ["Tests that never exercise a path never teach the validator its lock order, so that path's bugs stay hidden.",
        "Suppressing reports with blanket annotations hides genuine cycles."],
    v: "Run the full test and stress suite on a validator-enabled build; zero reports remain, and a deliberately introduced reversed-order bug is reported with both stack traces on its first execution.",
    dep: ["spinlocks", "sleeping-mutexes", "kernel-log"],
  },
  "clocksources": {
    s: "Free-running counters the kernel reads to measure elapsed time, ranked by resolution, speed and reliability, with fallback when one proves unstable.",
    d: "A clock source is a monotonic counter, such as a per-CPU cycle counter or a platform timer, with a known frequency and read cost. The kernel scales raw counts into nanoseconds with a multiplier and shift, reads it on every time query, and chooses the best available source. Cycle counters are cheap but may differ between CPUs or change with frequency; the kernel validates them against a slower reliable source and falls back if they drift. Paravirtualized sources serve guests. Handling counter wraparound and consistent reads across CPUs defines correctness.",
    k: ["Fast per-CPU counter vs. slower shared platform timer: counters are nanoseconds to read, but need synchronization proof across CPUs and power states.",
        "Continuous watchdog verification vs. trusting hardware flags: verification catches broken counters, at the cost of periodic work."],
    p: ["A counter not synchronized between CPUs makes time go backwards when a thread migrates.",
        "Counter wraparound arithmetic done in too few bits produces huge forward jumps."],
    v: "Read the clock from every CPU continuously across migrations, frequency changes and suspend; readings never decrease, cross-CPU skew stays below the specified bound, and an injected unstable source triggers fallback.",
    dep: ["early-init", "per-cpu-data", "smp-bringup"],
  },
  "clock-events": {
    s: "Programmable timer hardware that interrupts at a requested future time, abstracted so the same code drives periodic and one-shot modes.",
    d: "Timer devices, usually one per CPU, can be programmed to fire after a given delta or periodically. The clock event layer hides the device behind a common interface, chooses the best per CPU, and multiplexes it: the next event is the earliest of the pending timers. It handles devices that stop in deep idle states by delegating to a broadcast device on another CPU, and handles minimum and maximum programmable deltas. The interrupt it generates drives the tick and the high-resolution timer queue. Programming races with the current time, and missed deadlines must still fire.",
    k: ["One-shot programming vs. periodic ticks: one-shot lets idle CPUs sleep arbitrarily long and gives precise timers, periodic is simple but wakes the CPU constantly.",
        "Per-CPU local timer vs. a global broadcast: local timers scale and are precise, broadcast covers CPUs whose local timer stops in deep sleep."],
    p: ["Programming a deadline already in the past without handling it never fires the timer.",
        "Deep sleep stopping the local timer with no broadcast fallback loses all wakeups for that CPU."],
    v: "Schedule timers at random microsecond to second offsets on every CPU while entering deep idle states; each fires within the device's resolution of its deadline, and none are lost across sleep.",
    dep: ["clocksources", "irq-subsystem", "per-cpu-data"],
  },
  "tick-management": {
    s: "The regular timer interrupt that drives time slices and housekeeping, and the logic that stops it on idle or single-task CPUs.",
    d: "On each tick the kernel updates time, charges the running task, checks whether its slice has expired, runs expired timers and triggers deferred processing such as grace-period tracking and load accounting. A fixed frequency is a trade of latency against overhead. Dynamic ticks stop the tick when a CPU is idle, and full tickless modes stop it even when a single task runs, so dedicated CPUs run undisturbed. Stopping the tick requires that all duties are handed off or deferred and that it restarts correctly when needed. Housekeeping then concentrates on designated CPUs.",
    k: ["Periodic fixed tick vs. dynamic tickless: fixed ticks are simple and predictable, tickless saves power and avoids jitter but needs careful handoff of every tick duty.",
        "High vs. low tick frequency: high frequency improves timer granularity and responsiveness, low frequency reduces overhead and wakeups."],
    p: ["Stopping the tick while a pending timer or grace period needs it leaves work undone until something else wakes the CPU.",
        "Restarting a stopped tick late makes the time slice accounting wildly wrong."],
    v: "Run an idle system and a single-thread isolated CPU for minutes; interrupt counters show the tick almost entirely absent there, while time, timers and scheduling remain correct on the busy CPUs.",
    dep: ["clock-events", "high-res-timers", "per-cpu-data", "irq-subsystem"],
  },
  "high-res-timers": {
    s: "Timers keyed by exact time rather than tick count, kept in an ordered structure and driven directly by the timer hardware.",
    d: "Timers that expire on a coarse tick are too imprecise for sleeps of microseconds, media pacing and network pacing. High-resolution timers hold pending expirations in a time-ordered tree per CPU, and the hardware is programmed for the earliest. When it fires, expired timers run in interrupt context and may re-arm themselves. Sleep calls, interval timers and the scheduler's deadline tracking use them. Coarse timers, in a hierarchical wheel with cheap insertion and cancellation, still serve the vast majority of uses, such as network timeouts that rarely fire. Slack allowances let nearby expirations coalesce to save wakeups.",
    k: ["Ordered tree for exact timers vs. a hashed wheel for coarse ones: the tree gives precision and cheap earliest lookup, the wheel gives constant-time insert and cancel for timeouts.",
        "Coalescing within a slack window vs. exact firing: slack saves power by batching, exactness serves real-time use."],
    p: ["Running long callbacks in the timer interrupt delays every other timer and adds latency to the CPU.",
        "Cancelling a timer whose callback is running on another CPU without waiting leaves it using freed data."],
    v: "Arm thousands of timers at randomized microsecond deadlines under load; each fires within the measured latency bound, cancellation under concurrent firing never runs a callback afterward, and coalesced wakeups lower interrupt counts.",
    dep: ["clock-events", "clocksources", "per-cpu-data", "spinlocks"],
  },
  "wall-clock-discipline": {
    s: "Maintaining the calendar time of day, and steering it toward a reference with small rate adjustments rather than jumps.",
    d: "The kernel combines a monotonic count from the active clock source with an offset to produce several clocks: monotonic time that never steps, real time that tracks civil time, and boot time that includes suspension. A synchronization daemon measures offset against a reference and asks the kernel to slew the rate by tiny amounts, or step the clock when far off. The kernel handles leap seconds, which insert or delete a second. Time zone and civil conversion belong in user space. Users of real time must expect it to jump, which is why durations use monotonic time.",
    k: ["Slewing the clock rate vs. stepping it: slewing keeps time monotonic and smooth but corrects slowly, stepping corrects instantly and breaks code that assumed continuity.",
        "Smearing a leap second over hours vs. inserting it abruptly: smearing avoids a repeated second but differs from standard time during the smear."],
    p: ["Measuring a duration with the real-time clock yields negative or huge values when the clock is stepped.",
        "Not accounting for time spent suspended makes timeouts fire late or early after resume."],
    v: "Step and slew the clock while threads measure intervals on the monotonic clock; intervals never go negative, the slew converges within the configured rate limit, and a simulated leap second passes without a stall.",
    dep: ["clocksources", "tick-management", "fast-user-paths"],
  },
  "kernel-log": {
    s: "A fixed-size ring buffer of kernel messages, written from any context including interrupts and crashes, and read by user space and consoles.",
    d: "Kernel code emits diagnostic messages with a severity into a lock-free ring buffer that records the text, timestamp, and CPU or task context. Writers can be in any context, including a non-maskable interrupt or a failing panic path, so writing never blocks and never allocates. Consoles drain the buffer asynchronously to serial ports and screens, and user space reads it through an interface. Rate limiting prevents a repeated message from flooding. Early boot buffers messages before consoles exist. Logs are often the only evidence of a failure, so they must survive until the crash is captured.",
    k: ["Lock-free ring with asynchronous consoles vs. synchronous printing: asynchronous never delays the caller, but messages near a crash may not reach a slow console.",
        "Rate limiting vs. keeping every message: limiting protects against floods but may drop the one useful line."],
    p: ["Printing from within a console driver that itself logs can recurse forever.",
        "Writing messages containing kernel pointers or user secrets exposes them to anyone who can read the log."],
    v: "Log from all CPUs and from interrupt and panic contexts at once; records never interleave within a line, order follows timestamps, a flood is rate limited, and the final messages appear on the console after a panic.",
    dep: ["early-init", "atomics-and-barriers", "per-cpu-data"],
  },
  "tracepoints": {
    s: "Static hooks compiled into kernel paths, and a function-tracing facility, that can be enabled at runtime to record events with almost no cost when disabled.",
    d: "Developers place named tracepoints at interesting events: scheduler switches, page faults, block requests. Each is patched at runtime between a no-op and a call, so disabled tracepoints cost virtually nothing. When enabled, they write structured records into per-CPU ring buffers with timestamps, which user tools merge and decode. A function tracer can instrument entry and exit of nearly every kernel function using compiler-inserted call sites that are likewise patched. Filters, triggers and histograms reduce volume in the kernel. Design challenges include overhead, safe tracing from any context, and keeping event formats stable enough for tools.",
    k: ["Static tracepoints vs. dynamic probes only: static points have stable names and cheap cost, dynamic probes need no code changes but depend on internals that change.",
        "Per-CPU buffers merged later vs. a single ordered stream: per-CPU buffers avoid contention, merging by timestamp requires well-synchronized clocks."],
    p: ["Tracing code that itself calls traced functions recurses until the stack overflows.",
        "A full buffer silently overwriting oldest events loses the crucial early part of a failure unless sized or stopped on trigger."],
    v: "Enable scheduler and block tracepoints under heavy load; events appear in correct order with plausible timestamps, throughput drops by a small bounded amount, and disabling returns performance to baseline.",
    dep: ["per-cpu-data", "clocksources", "kernel-log", "pseudo-filesystems"],
  },
  "perf-events": {
    s: "Access to hardware performance counters and software events, for sampling where time goes and counting what the processor does.",
    d: "CPUs include counters of cycles, instructions, cache misses and branch mispredictions. The kernel virtualizes them per task or per CPU, multiplexing when events outnumber counters, and exposes them as descriptors. Counting mode reads totals; sampling mode configures an overflow interrupt, typically non-maskable, recording the instruction pointer and call chain to build profiles. Software events cover faults, context switches and tracepoints. Hardware support varies widely, and virtualized guests may have none. Stack unwinding in interrupt context must be safe, and sampling interrupts must not cause deadlocks.",
    k: ["Sampling interrupts vs. precise hardware-assisted sampling: interrupts are portable but skid past the true instruction, hardware-assisted records exact addresses where supported.",
        "Per-task counters saved on context switch vs. system-wide only: per-task attributes cost to workloads precisely, at the price of work on every switch."],
    p: ["Taking ordinary locks in the sampling interrupt deadlocks when it hits code holding them.",
        "Allowing unprivileged use without restriction leaks timing information usable in side-channel attacks."],
    v: "Profile a workload with a known hot function; sampling attributes the expected share of cycles to it, counter totals match an independent calculation, and multiplexed counts scale within a small error.",
    dep: ["irq-subsystem", "context-switch", "tracepoints", "credentials"],
  },
  "dynamic-probes": {
    s: "Placing breakpoints on running kernel code to run handlers at arbitrary instructions or function entries and exits, without rebuilding.",
    d: "A probe replaces an instruction with a breakpoint; when hit, the trap handler runs registered callbacks with access to registers and arguments, then executes the displaced instruction out of line or emulates it and resumes. Return probes hijack the saved return address to catch exits. Optimized variants jump directly instead of trapping. Probing is forbidden in sensitive areas such as the probing code itself, trap entry and non-reentrant paths, using a blacklist. Probes allow ad hoc investigation of production systems, and in-kernel programs often attach to them, but safety rests on handlers being short and non-sleeping.",
    k: ["Breakpoint-based vs. jump-optimized probes: breakpoints work anywhere but cost a trap, jumps are faster but only fit certain instruction sequences.",
        "Open probing vs. blacklist of unsafe regions: open probing is more useful, but any unlisted fragile spot can crash the machine."],
    p: ["Probing a function used by the probe handler recurses infinitely or deadlocks.",
        "Copying an instruction that has position-dependent semantics, like a relative jump, and running it elsewhere corrupts execution."],
    v: "Attach probes to thousands of random functions under load, then remove them; the machine stays stable, handlers see correct arguments and return values, and kernel code text returns to its original bytes.",
    dep: ["trap-entry", "tracepoints", "kernel-hardening", "sandboxed-bytecode"],
  },
  "sandboxed-bytecode": {
    s: "Small programs supplied from user space, checked by a verifier for safety and then run inside the kernel for filtering, tracing and policy.",
    d: "A user program is submitted as bytecode for a restricted virtual machine. A verifier explores every path, proving that it terminates, accesses only permitted memory with proper bounds, handles pointers by type, and calls only allowed helper functions; then it is compiled to native code. Programs attach to hook points such as packets, tracepoints, scheduling events and security hooks, and share data with user space through typed maps. This extends the kernel without modules, giving speed and safety. The verifier is large and complex, so bugs in it are kernel vulnerabilities, and expressiveness is limited by what can be proven.",
    k: ["Verified bytecode vs. loadable native modules: verification gives safety by construction and live replacement, modules are unrestricted but can crash the machine.",
        "Strict static verification vs. runtime checks: static proof gives zero overhead but rejects some valid programs, runtime checks accept more at the cost of speed."],
    p: ["A verifier bug that accepts an unsafe program gives user space an arbitrary kernel read or write.",
        "Unprivileged loading enables speculative-execution side channels unless the compiler mitigates."],
    v: "Load adversarial programs with unbounded loops, out-of-range accesses and forged pointers; each is rejected, valid programs attach and run with expected output, and a verifier fuzzer finds no accepted unsafe program.",
    dep: ["kernel-hardening", "credentials", "capabilities", "tracepoints"],
  },
  "panic-and-oops": {
    s: "What the kernel does on an unrecoverable internal error: print diagnostics, taint itself, and either halt, reboot or continue depending on severity and policy.",
    d: "On an invalid access, failed assertion or unrecoverable hardware error, the kernel reports an oops with registers, a stack trace and the faulting instruction, kills the offending task if it can, and marks itself tainted so later reports note that state may be inconsistent. If the failure is in a critical context or the policy says so, it escalates to a panic: stop other CPUs, flush logs, optionally start a crash dump, and halt or reboot after a timeout. Watchdogs detect hangs where no oops occurs. Running after an oops risks corrupted locks and leaked resources, so policy matters.",
    k: ["Continue after an oops vs. panic at once: continuing may keep a service available, but runs on possibly corrupted state; panicking is safe and loses uptime.",
        "Automatic reboot vs. halt for inspection: reboot restores service quickly, halting preserves the machine for debugging."],
    p: ["Panicking while holding the lock needed to print the report hangs without any message.",
        "Killing a task that died holding kernel locks leaves them held forever and cascades into more hangs."],
    v: "Inject faults in process context, interrupt context and while holding locks; each produces a complete report with a usable stack trace, the policy outcome occurs as configured, and the taint flag is set afterwards.",
    dep: ["trap-entry", "kernel-log", "crash-dump", "task-structures"],
  },
  "crash-dump": {
    s: "Capturing a full image of memory at the moment of failure, via a second pre-loaded kernel, so the cause can be analyzed offline.",
    d: "At boot the system reserves memory and loads a small secondary kernel into it. When the primary panics, it does the minimum, saves CPU registers, and jumps into the secondary kernel without a firmware reset so memory contents survive. The secondary boots in its small reserved region and exposes the crashed kernel's memory as a readable image, which user tools filter and write to storage or the network. Analysts load the image with the matching symbols to inspect structures and stacks. The crashed state is untrusted, device state is unknown, and drivers must tolerate being reinitialized after an abrupt stop.",
    k: ["Second kernel capturing the dump vs. dumping from the crashed kernel: a fresh kernel is not affected by corruption, but needs reserved memory and drivers that reset cleanly.",
        "Filtering pages before saving vs. dumping everything: filtering shrinks dumps from terabytes to manageable sizes, at the risk of omitting needed pages."],
    p: ["Devices left running DMA after the crash write over the secondary kernel's memory.",
        "Reserved memory sized too small makes the dump kernel run out of memory while capturing."],
    v: "Trigger panics repeatedly under load and while idle; each produces a complete dump that loads in the analysis tool with correct stacks, device resets succeed, and the system returns to service.",
    dep: ["panic-and-oops", "early-init", "firmware-handoff", "smp-bringup"],
  },
  "module-loader": {
    s: "Linking object code into the running kernel on demand: allocating memory, applying relocations, resolving symbols and running initialization.",
    d: "Loading reads a relocatable image, allocates executable and data regions, copies sections, resolves references to exported kernel symbols and other modules' symbols, applies architecture-specific relocations, sets page protections so code is read-only and executable, and calls the init routine; failure at any step must unwind. A reference count prevents unloading while in use, and unload runs the exit routine and frees memory. Dependencies load automatically through aliases tied to device identifiers. Loading and unloading concurrently with other kernel activity is hard to make safe, which is why many deployments never unload.",
    k: ["Modules vs. everything built in: modules keep the base image small and drivers optional, built-in code is simpler, faster to boot and cannot be tampered with after boot.",
        "Support unloading vs. load-only: unloading frees memory and aids development, but needs reference tracking for every callback that points into the module."],
    p: ["Unloading while a timer, work item or callback still points into the module jumps into freed code.",
        "Loading a module compiled for a different kernel configuration silently corrupts structures with changed layouts."],
    v: "Load and unload each module in a loop with concurrent use and injected init failures; memory returns to baseline, dependent modules are refused while in use, and no stale callback fires after unload.",
    dep: ["symbol-versioning", "module-signing", "slab-allocator", "page-tables"],
  },
  "symbol-versioning": {
    s: "Checks that tie a module to the exact kernel interfaces it was built against, by exporting symbols explicitly and comparing interface checksums.",
    d: "Only symbols deliberately exported are visible to modules, with some restricted to modules with compatible licenses. Each export carries a checksum computed from the type signatures it exposes. At load, the loader compares the checksums the module expects against the running kernel's and refuses mismatches, preventing a module built against an older structure layout from corrupting memory. Version tags in the module identify the kernel release. There is deliberately no stability guarantee for in-kernel interfaces, in contrast to the system call ABI, which makes out-of-tree drivers a recurring maintenance cost.",
    k: ["Unstable internal interfaces vs. frozen driver API: free internal change lets the kernel evolve and clean up quickly, but out-of-tree code must follow each release.",
        "Checksum on type signature vs. version number only: checksums catch real layout changes automatically, version numbers are coarse and miss silent changes."],
    p: ["A change to a structure layout without the checksum covering it lets mismatched modules load and corrupt memory.",
        "Exporting an internal helper broadly turns it into an interface that cannot be changed."],
    v: "Build a module against a slightly altered structure and attempt to load it; the loader refuses with a mismatch message, and a correctly built module loads and uses every exported symbol it needs.",
    dep: ["module-loader"],
  },
  "module-signing": {
    s: "Verifying a cryptographic signature on each module before loading, so only code from a trusted key becomes part of the kernel.",
    d: "At build time modules are signed with a private key whose public half is embedded in the kernel or stored in a protected keyring. At load the kernel verifies the signature against the module's contents, then refuses unsigned or incorrectly signed modules when enforcement is on. Combined with lockdown policies that block other ways of changing kernel memory (direct memory writes, unsigned boot parameters), it keeps the running kernel within the trusted boot chain. Key management, revocation and the handling of out-of-tree driver builds are the operational difficulties.",
    k: ["Enforce signatures vs. warn only: enforcement blocks untrusted code, but breaks custom drivers and needs a signing workflow.",
        "Build-time ephemeral key vs. long-lived organizational key: ephemeral keys limit exposure but break external module builds, organizational keys are practical but valuable targets."],
    p: ["Leaving another route to load code, such as a raw memory interface, makes signature enforcement meaningless.",
        "Signing keys kept on build machines become a path to arbitrary kernel code if stolen."],
    v: "Attempt loading unsigned, tampered and correctly signed modules with enforcement on; only the valid one loads, the failures are logged with reasons, and no alternate path loads code.",
    dep: ["module-loader", "keyrings-and-integrity", "kernel-hardening"],
  },
  "live-patching": {
    s: "Replacing kernel functions in a running system, to apply fixes without a reboot, while keeping in-flight calls consistent.",
    d: "A patch module supplies replacement functions; tracing hooks at function entry redirect calls to the new version. The hard part is consistency: threads may be sleeping inside the old function, and calls to a patched function from partly transformed callers must not see mixed assumptions. The kernel tracks each task's patch state, transitions it when it crosses a safe point such as returning to user mode or when its stack shows no patched function, and completes when every task has switched. Data structure changes require shadow data or transformations. Patches must be written with care, and rollback has to be possible.",
    k: ["Per-task consistency model vs. patching functions immediately: per-task transitions prevent mixed old and new behavior but take time and can stall on sleeping tasks.",
        "Function replacement only vs. supporting data changes: function-only patches are safe and small, data changes are possible with shadow variables but difficult."],
    p: ["A task sleeping forever inside an old function prevents the transition from ever finishing.",
        "Patching a function whose callers inline it has no effect on those callers."],
    v: "Apply a patch to a function under heavy concurrent use; every call after completion uses the new behavior, no call observes mixed state, the transition completes, and reverting restores the original behavior.",
    dep: ["module-loader", "tracepoints", "task-structures", "module-signing"],
  },
});
