// Details for the Operating System Kernel plate, part 5: boot and architecture support, cross-cutting concerns.
ATLAS.details("os-kernel", {
  "firmware-handoff": {
    s: "The contract by which firmware or a bootloader loads the kernel image, passes a memory map, hardware description and command line, and transfers control.",
    d: "Firmware initializes the memory controller and basic devices, then a bootloader or the firmware itself loads the kernel image and optional initial root image into memory and jumps to a defined entry with the CPU in a known state. It passes a memory map, a pointer to the hardware description, the command line, and any boot-time measurements. The kernel must trust none of it blindly. Secure boot verifies each stage's signature before it runs, and the kernel continues the chain. Runtime services provided by firmware, such as variable storage and clock access, remain callable afterward through a defined interface.",
    k: ["Kernel entered directly by firmware vs. through a separate bootloader: direct entry removes a component, a bootloader adds menus, fallback and flexible loading.",
        "Trusting firmware services after boot vs. avoiding them: using them is convenient, but they are opaque code that can hang or misbehave at runtime."],
    p: ["Believing the firmware memory map without sanity checks lets overlapping or reserved regions be handed to the allocator.",
        "Skipping verification of the initial root image breaks the measured chain at its last link."],
    v: "Boot from several firmware variants with secure boot on; a modified kernel or root image is refused, a valid one boots, the memory map the kernel reports matches the firmware's, and measurements appear in the log.",
    dep: [],
  },
  "early-init": {
    s: "The first machine-specific code to run: set up a stack, enable the MMU, parse the memory map and prepare enough state to run general kernel code.",
    d: "The entry code runs with minimal assumptions: possibly physical addressing, no stack, one CPU. It sets up a temporary stack, clears uninitialized data, builds initial page tables to map the kernel at its final virtual address (possibly randomized), switches the MMU on, detects CPU features and patches code to match, parses the memory description and command line, and calls the architecture-independent start. Anything that fails here has no console to report to, so early debug output uses a raw serial write. Code in this phase must avoid features such as dynamic allocation and locking that are not yet available.",
    k: ["Randomized kernel placement vs. fixed addresses: randomization hardens against exploitation, but complicates early code and symbol-based debugging.",
        "Boot with a minimal mapping and refine later vs. building the full mapping up front: minimal is simple to get right, refinement needs allocators ready."],
    p: ["Using a facility such as a lock, a per-CPU variable or a log call before it is initialized crashes with no output.",
        "Feature patching that selects code for the wrong CPU model produces illegal instructions at some later point."],
    v: "Boot with early debug output on a simulated machine and several real ones with different memory layouts and feature sets; each reaches the generic start with the MMU enabled and an accurate memory map.",
    dep: ["firmware-handoff", "hardware-description"],
  },
  "early-allocator": {
    s: "A simple, boot-time memory allocator used before the real page allocator exists, from which the real allocator is bootstrapped.",
    d: "Before the buddy allocator can run, the kernel needs memory for its own page descriptors, per-CPU areas and early tables. A simple region-based allocator hands out ranges from the firmware-provided map, tracking reserved areas for the kernel image, the initial root image and firmware tables. Once the descriptor arrays are built, the remaining free ranges are handed to the page allocator in bulk and the early allocator retires. Its constraints are simplicity and correctness with unusual memory layouts: holes, multiple nodes, memory that is hot-added later, and ranges that must stay untouched.",
    k: ["Simple bump allocation vs. a full early allocator with freeing: bump allocation is trivial and enough for boot, freeing lets early code recycle memory but costs complexity.",
        "Initializing all page descriptors up front vs. deferred parallel initialization: up front is simple, deferred shortens boot on very large memory but needs care."],
    p: ["Releasing memory to the page allocator that still holds firmware tables or the root image corrupts them later.",
        "Ignoring holes in the map puts nonexistent addresses in the free lists."],
    v: "Boot machines with unusual layouts, multiple nodes and reserved holes; page counts reported by the allocator match the firmware map minus reservations, and no allocation falls in a reserved or missing range.",
    dep: ["early-init", "firmware-handoff", "physical-allocator"],
  },
  "init-sequence": {
    s: "The ordered bring-up of kernel subsystems, from memory and scheduler to drivers and root filesystem, ending by launching the first user process.",
    d: "The generic start function initializes subsystems in dependency order: memory, scheduler, interrupts, timers, then multiple CPUs, then the driver model, networking, filesystems, security modules. Later stages register initialization calls at declared levels, run in order. Slow device probing can run in parallel. Memory used only during boot is freed at the end. The kernel mounts the root filesystem, from the initial root image or directly, and starts the first user process, which carries on from there. Order is the difficulty: a subsystem that is used before it is initialized fails strangely, and dependencies change over time.",
    k: ["Declared init levels vs. explicit dependency graph: levels are simple and compact, but order within a level is implicit and fragile.",
        "Sequential vs. parallel initialization: parallel cuts boot time, but device ordering and names become nondeterministic unless pinned."],
    p: ["A call made before its subsystem is ready works on some machines and crashes on others, depending on timing.",
        "Freeing boot-only memory while something still references it corrupts memory long after boot."],
    v: "Boot a thousand times on varied hardware with randomized probe timing; all reach the first user process, the log shows every initialization level in order, and freed boot memory is never touched.",
    dep: ["early-allocator", "interrupt-controller", "smp-bringup", "mount-table", "initramfs"],
  },
  "initramfs": {
    s: "A compressed, memory-resident root image loaded by the bootloader, containing the early user-space tools and drivers needed to find the real root.",
    d: "The real root filesystem may be on a device needing a driver, a network, a logical volume, or an encrypted disk, whose setup needs user-space tools. The bootloader loads a small archive into memory; the kernel unpacks it into a memory filesystem and runs its init program, which loads modules, assembles volumes, asks for keys, mounts the real root, and switches to it, freeing the temporary image. It keeps the kernel generic: one image supports every machine because machine-specific pieces are in this archive. The archive is part of the trusted boot chain and must be verified.",
    k: ["Generic kernel plus initial image vs. a custom kernel with everything built in: the image allows one kernel for all hardware, built-in is simpler and boots faster for fixed hardware.",
        "Build the image per machine vs. generic: per machine is small and fast, generic is large but works everywhere."],
    p: ["A missing driver in the image leaves the machine unable to find its root, with only a minimal shell to debug.",
        "Unverified initial images let an attacker with disk access run code before any user-space protections."],
    v: "Boot with the root on an encrypted logical volume over a network block device; the image assembles it, switches root, frees its own memory, and a tampered image is rejected under secure boot.",
    dep: ["firmware-handoff", "pseudo-filesystems", "mount-table", "module-loader"],
  },
  "trap-entry": {
    s: "The architecture code that catches every transition into the kernel, whether interrupt, fault or system call, and saves and restores CPU state around it.",
    d: "Vector tables map each trap cause to an entry routine. The entry code, tiny and delicate, switches to a kernel stack, saves registers into a frame, possibly switches to kernel page tables, and calls the generic handler for faults, interrupts or system calls. On return it checks for pending work (rescheduling, signal delivery) and restores state. Nested traps, non-maskable interrupts that can arrive anywhere, and traps taken during entry itself require careful ordering. Mitigations for speculative-execution attacks add work at each transition. A single instruction in the wrong order here can corrupt privilege state.",
    k: ["Separate kernel and user page tables on entry vs. one shared set: separation closes information leaks from speculative execution, but adds cost to every transition.",
        "Saving all registers eagerly vs. only the needed ones: saving all is simple and uniform, selective saving is faster but fragile."],
    p: ["A non-maskable interrupt arriving mid-entry, while the stack or state is half switched, corrupts the frame if not specially handled.",
        "Leaving user-controlled register values live into kernel code makes speculative attacks easier."],
    v: "Run an entry stress test mixing system calls, faults and interrupts, including non-maskable ones, at high rate across all CPUs; no state is corrupted, return values are right, and every transition preserves user registers exactly.",
    dep: ["early-init", "interrupt-controller"],
  },
  "interrupt-controller": {
    s: "The driver for the hardware that collects interrupt lines and messages, prioritizes them and delivers them to CPUs, including inter-processor signals.",
    d: "Interrupts from devices reach one or more interrupt controllers, which can mask, prioritize, route to specific CPUs, and acknowledge. The driver initializes the controller, translates hardware interrupt numbers into the kernel's numbering, implements mask, unmask, acknowledge and end-of-interrupt operations per trigger type, sets affinity, and delivers inter-processor interrupts used for rescheduling, remote function calls and TLB shootdown. Message-signaled interrupts use a per-device message address. Controllers are often cascaded or virtualized, and their programming model differs across platforms, so the architecture layer hides it behind an interface.",
    k: ["Local per-CPU controller plus a distributing controller vs. a single one: split designs scale to many CPUs, a single controller is simpler on small systems.",
        "Priority-based interrupt masking vs. all-or-nothing disabling: priorities let urgent interrupts preempt, all-or-nothing is simpler to reason about."],
    p: ["Forgetting end-of-interrupt for one trigger type leaves the line blocked and a device silent.",
        "Retargeting an interrupt to another CPU while it fires can run the handler on two CPUs at once."],
    v: "Generate interrupts from every source, send inter-processor signals between all CPU pairs and change affinities continuously; none are lost or duplicated, handlers never run concurrently on the same line, and counts match.",
    dep: ["early-init", "hardware-description"],
  },
  "context-switch": {
    s: "Saving one thread's execution state and loading another's, including registers, stack, address space and extended CPU state.",
    d: "Switching threads saves the callee-saved registers and stack pointer of the outgoing one into its task record and loads the incoming one's, so execution resumes where the incoming thread last left off. If the incoming thread belongs to another process, the address space switches by loading new page-table roots, using address-space identifiers to avoid flushing. Extended state such as vector and floating-point registers is large and saved lazily or on demand. Thread-local base registers and debug state are swapped too. A switch is among the hottest, subtlest paths: it runs partly on one stack and partly on another, with interrupts off, and must update accounting.",
    k: ["Eager vs. lazy extended-register save: lazy saves work for threads that never use those registers, eager is simpler and avoids security leaks across switches.",
        "Switching address space always vs. skipping for kernel threads: skipping for kernel threads saves a flush, but needs borrowed address space handling."],
    p: ["Forgetting to save or restore one piece of state, such as thread-local base, makes threads corrupt each other, only under particular scheduling.",
        "Another CPU waking the outgoing thread before its state is fully saved runs it on a half-saved stack."],
    v: "Switch between threads using every register class and vector state in a tight loop across CPUs for hours; each thread's computed checksum stays correct, and context switch time measured by tracing is within its budget.",
    dep: ["trap-entry", "page-tables", "tlb-management"],
  },
  "smp-bringup": {
    s: "Starting the secondary CPUs, giving each its stacks, tables and per-CPU state, and later taking CPUs online and offline at runtime.",
    d: "Boot starts on one CPU. It prepares per-CPU areas and an entry point and signals each other CPU through firmware or inter-processor interrupts; each sets up its MMU, trap vectors, local timer and interrupt controller interface, announces readiness, and enters the scheduler's idle loop. CPU hotplug reverses this for power saving or fault isolation: the kernel migrates tasks, interrupts and timers off the CPU, runs registered callbacks in order so subsystems drop per-CPU state, and powers it down. Every per-CPU structure in the kernel needs to handle appearance and disappearance, a source of rare, load-dependent bugs.",
    k: ["Bring CPUs up serially vs. in parallel: serial is simple and deterministic, parallel shortens boot on machines with hundreds of CPUs.",
        "Staged hotplug callbacks with ordering vs. ad hoc notifications: staged callbacks make the order of teardown explicit and symmetric, ad hoc notifications are easy to get subtly wrong."],
    p: ["A subsystem not notified of CPU removal keeps scheduling work, timers or interrupts on a dead CPU.",
        "A secondary CPU that runs kernel code before its trap vectors and stack are ready crashes silently with nothing to report it."],
    v: "Offline and online random CPUs thousands of times under heavy load; no tasks, timers or interrupts are lost, per-CPU resources balance, and total throughput scales back after each online.",
    dep: ["early-init", "interrupt-controller", "per-cpu-data", "clock-events", "run-queues"],
  },
  "concurrency-discipline": {
    s: "The rules that say which lock protects which data, in what order locks may be taken, and which structures are lock-free, enforced everywhere.",
    d: "Every CPU runs kernel code at once, and interrupts cut into it, so every shared structure needs a documented protector. The discipline defines a global lock order, which locks may be held in interrupt context, which may be held across sleeps, how reference counts and read-copy-update protect lifetimes, and where data is per-CPU or per-thread instead. Locks too coarse limit scaling, too fine multiply deadlock risk and cost. As CPU counts grew, the kernel kept replacing global locks with finer ones. Rules that are written down and checked by tools stay true; rules known only to developers erode.",
    k: ["Coarse global lock first, refine under measurement vs. fine-grained from the start: coarse is correct and simple, but must be split as scaling needs appear.",
        "Locks vs. lock-free structures and per-CPU data: locks are easy to reason about, avoiding them removes contention at the price of proof difficulty."],
    p: ["Two paths taking the same pair of locks in opposite order deadlock only in rare interleavings, long after release.",
        "Protecting data by convention without annotation lets new code access it unlocked."],
    v: "Run the full stress suite on a build with the lock validator, race detector and preemption-randomization enabled; no report is produced, and scaling tests on high CPU counts show throughput growing near linearly.",
    dep: ["spinlocks", "sleeping-mutexes", "read-copy-update", "lock-validator", "per-cpu-data"],
  },
  "execution-contexts": {
    s: "The kernel's distinct contexts (thread, softirq, hard interrupt, non-maskable interrupt), each with different rules on sleeping, locking and allocation.",
    d: "Code runs in one of several contexts, and what is allowed depends on which. Process context belongs to a thread and may sleep, take mutexes and fault on user memory. Softirq and deferred contexts cannot sleep. Hard interrupt context also cannot, and must be short. Non-maskable interrupt context can interrupt anything, even interrupt handlers, so it may use almost nothing. Memory allocation flags must say whether the caller may sleep or reclaim. Calls are annotated, and debug builds check them. Violations such as sleeping with a spinlock held are among the most frequent kernel bugs.",
    k: ["Many restricted contexts vs. making almost everything threaded: restricted contexts give the lowest latency, threading simplifies rules at the cost of added scheduling latency.",
        "Compile-time and runtime context assertions vs. documentation alone: assertions catch violations early at some cost, documentation is free and ignored."],
    p: ["Calling a function that can sleep from interrupt context works in testing and hangs in production when the sleep path is taken.",
        "Using ordinary allocation flags in a reclaim path recurses into reclaim and deadlocks."],
    v: "Run with sleep-in-atomic checks, context-tracking assertions and fault injection that forces slow paths; no violation is reported across the test suite, and each documented context rule has a test triggering it.",
    dep: ["irq-subsystem", "deferred-work", "spinlocks", "sleeping-mutexes", "physical-allocator"],
  },
  "trust-boundary": {
    s: "The principle that everything crossing from user space into the kernel is hostile until validated, shaping every interface, copy and parse in the kernel.",
    d: "Programs may be buggy or malicious, and the kernel must remain correct regardless. Every pointer, length, flag, file name and descriptor from user space is validated; every value is copied before use; every structure returned to user space is fully initialized. The same suspicion applies to data from devices, which can misbehave, and from network and removable media. Capabilities and mandatory policy limit what validated requests may do. The boundary also covers side channels: speculation and timing can leak data even when no check fails. Defense is layered because one validation will eventually be missed.",
    k: ["Validate at each entry point vs. a central validation layer: central layers make rules uniform, but interfaces differ enough that entry-specific checks remain necessary.",
        "Trusting hardware vs. treating devices as hostile: trust is simple and fast, hostility protects against malicious peripherals, and needs an IOMMU and careful parsing."],
    p: ["Validating a value and then re-reading it from user memory lets it change in between.",
        "Returning uninitialized padding or freed data leaks kernel memory to users."],
    v: "Run continuous interface fuzzing with sanitizers and uninitialized-memory detection across every call, file format and network input; no kernel fault, no kernel data in returned buffers, and fuzzing coverage counters keep growing.",
    dep: ["syscall-dispatch", "user-memory-access", "permission-checks", "kernel-hardening", "iommu"],
  },
  "kernel-structure": {
    s: "Whether services run as one privileged program sharing an address space (monolithic) or as isolated processes talking by messages (microkernel).",
    d: "A monolithic kernel runs filesystems, networking, drivers and policy together in privileged mode, calling each other directly: fast, and a bug anywhere can corrupt anything. A microkernel keeps only scheduling, address spaces, IPC and interrupt forwarding in privileged mode, and runs drivers and services as unprivileged processes: small trusted base and fault isolation, at the cost of message overhead and harder coordination. Hybrids exist. Modules, user-space drivers, and verified in-kernel programs move the line over time. The choice shapes performance, security, reliability and how drivers are written.",
    k: ["Direct calls in one address space vs. message passing between isolated servers: direct calls are fastest and simplest, messages contain faults and shrink the trusted base but cost context switches.",
        "Drivers in kernel vs. in user space: in-kernel drivers run fast with full access, user-space drivers cannot crash or compromise the kernel and cost transitions."],
    p: ["A monolithic design with no internal boundaries means one driver bug can corrupt any subsystem.",
        "Fine-grained message-passing servers with synchronous chains of calls multiply latency and risk deadlock."],
    v: "Inject faults into a driver and a filesystem service; measure the blast radius: in a monolithic build it is the whole system, in an isolated design it is that component restart, and note throughput on a standard benchmark for both.",
    dep: ["syscall-dispatch", "pipes-and-queues", "module-loader", "driver-binding"],
  },
  "failure-policy": {
    s: "What the kernel does when allocation fails, hardware errors, drivers misbehave or invariants break: return an error, retry, isolate, or stop.",
    d: "Every subsystem must decide how to fail. Allocation failures should propagate as error returns and be handled by every caller, or be guaranteed not to fail through reserves. Hardware errors, such as memory errors or device timeouts, call for isolation and recovery: retire a bad page, reset a device, fail the one request. Broken invariants may justify panic. Resource exhaustion calls for limits and graceful degradation rather than collapse. The policy also covers what to tell user space: precise error codes, not silent success. Error paths are rarely tested, so they hide the worst bugs.",
    k: ["Fail fast and stop vs. contain and continue: stopping avoids running on corrupt state, containing keeps services up but risks compounding damage.",
        "Allocation that never fails vs. every caller handles failure: never-fail simplifies callers but can deadlock, handling failure is robust but needs testing of rare paths."],
    p: ["Error paths that free resources in the wrong order or twice cause crashes that appear only under memory pressure.",
        "Swallowing a storage error and reporting success loses data silently."],
    v: "Run the test suite with systematic fault injection into allocation, I/O, and device operations; every injected failure produces an error return or defined recovery, with no leak, crash or silent success.",
    dep: ["panic-and-oops", "oom-handler", "bio-requests", "driver-binding", "slab-allocator"],
  },
  "portability": {
    s: "Keeping machine-specific code behind narrow interfaces, so most of the kernel is shared across CPU families, platforms and devices.",
    d: "A kernel supports many CPU families, memory models and boards. The generic code assumes abstractions: page-table operations, atomic operations, memory barriers, context switch, trap entry, timers, interrupt controllers, DMA. Each architecture implements these in a small layer, and platform differences within an architecture are described by data tables and per-board drivers. Good abstractions let a new port reuse everything above. Poor ones leak: assumptions of byte order, word size, cache coherence or page size creep into generic code and break when a port arrives. Testing on diverse hardware and simulators is the only reliable check.",
    k: ["Narrow architecture interface vs. rich per-architecture optimization: a narrow interface keeps ports small, rich hooks let each architecture exploit hardware but fragment the code.",
        "Description tables for platform variety vs. board-specific code: tables share one driver across many boards, board code can be simpler for a single product."],
    p: ["Assuming a particular word size, endianness or cache coherence in generic code breaks the next port in subtle ways.",
        "Architecture code copied between ports drifts and fixes reach only one copy."],
    v: "Build and boot the generic test suite on every supported architecture and a simulator with unusual parameters (page size, byte order, word size); all tests pass, and a new port needs only the documented interface functions.",
    dep: ["early-init", "trap-entry", "context-switch", "hardware-description", "atomics-and-barriers"],
  },
});
