// Map data for the game engine. Items are "Label|detail shown on hover". Colors index --c1..--c15 in style.css.
window.ATLAS_MAP = {
  title: "Game Engine",
  lede: "Every component of a complete game engine, arranged by layer. A small 2D engine keeps the core and drops most of the optional systems; a large 3D engine has all of them.",
  ground: ["Hardware", "Operating system", "Drivers", "Graphics APIs", "Third-party middleware"],
  bands: [
    { label: "Tools & services", groups: ["tools", "debug", "plat"],
      intro: "What surrounds the running game: the editor people build it in, the tools that show what it is doing, and the services that ship and operate it." },
    { label: "Gameplay layer", groups: ["script", "ai", "ui"],
      intro: "Where the game itself lives. These systems turn the engine's capabilities into rules, characters and screens, and are mostly written or configured by designers." },
    { label: "Engine subsystems", groups: ["render", "anim", "phys", "audio", "input", "net"],
      intro: "Independent specialists. Each reads the world model, does one job well, and should not need to know the others exist." },
    { label: "World model", groups: ["world"],
      intro: "The shared truth of the game: what exists, where it is, and how time advances. Every subsystem above reads or writes it." },
    { label: "Resources", groups: ["asset"],
      intro: "How content gets from an artist's file to memory at the right moment, in the right format, without stalling the frame." },
    { label: "Foundation", groups: ["found"],
      intro: "Everything that is not about games at all: the plumbing that lets the rest of the engine run on many platforms, quickly, in parallel." },
  ],
  crossIntro: "Some decisions are not components. Which thread owns which data, how objects refer to each other, whether a simulation is deterministic, and what each system may spend per frame all have to be decided before the components are built, because every one of them depends on the answer.",
  cross: [
    "Threading model|Which systems run on which threads, and how data crosses them",
    "Data ownership & lifetimes|Handles versus pointers; who frees what",
    "Determinism|Replays, networking and testing depend on it",
    "Dependencies & layering|Subsystems decoupled enough to replace or omit",
    "Hardware scalability|LOD, quality tiers, platform-specific paths",
    "Performance budgets|Frame time, memory and load time per system",
  ],
  groups: {
    tools: { title: "Tools & editor", color: 13, optional: true,
      about: "The editor is often larger than the runtime. It is built on the same reflection system as serialization, so a property added in code appears in the inspector, saves to disk and can be undone without extra work.",
      items: ["Editor shell|Docking panels, selection, gizmos", "Undo / redo", "Level editor", "Material & shader graphs",
        "Animation graph editor", "Asset browser", "Property inspector|Driven by the reflection system", "Play-in-editor",
        "Terrain & spline tools", "Build / cook / deploy", "Automated tests & CI", "Plugins & public SDK", "Multi-user editing"] },
    debug: { title: "Debugging & diagnostics", color: 14,
      about: "A game runs sixty times a second and fails in ways that last a single frame. Consoles, visual debuggers, frame capture and deterministic replay exist to make those moments inspectable.",
      items: ["Console & cheats", "Runtime inspectors|Physics, AI, rendering and network visualizers", "Profilers|CPU and GPU",
        "Frame capture", "Memory & GPU analyzers", "Crash dumps", "Telemetry & analytics", "Deterministic replay"] },
    plat: { title: "Platform services & release", color: 15, optional: true,
      about: "Each store and console has its own accounts, achievements, entitlements and certification rules. A thin service layer keeps those differences out of gameplay code.",
      items: ["Platform SDKs|Achievements, friends, presence, entitlements", "Store & DLC", "Cloud saves", "Accounts & leaderboards",
        "Live ops & remote config", "Patching", "Mod distribution", "Console certification", "Ratings & parental controls"] },
    script: { title: "Scripting & gameplay logic", color: 9,
      about: "Gameplay changes far more often than the engine, so it is kept in a faster-to-iterate layer: a scripting language, visual graphs or plain data tables, with reusable frameworks for common game features.",
      items: ["Scripting VM & bindings|Interpreted or compiled; sandboxed", "Visual scripting", "Data tables & curves|Data-driven design for designers",
        "Coroutines & async", "Timers", "State machines", "Behavior trees", "Ability system", "Inventory", "Quests & dialogue"] },
    ai: { title: "Artificial intelligence", color: 10, optional: true,
      about: "Game AI is about believable behaviour on a budget: finding paths through the world, choosing what to do next, and sensing only what a character could plausibly know.",
      items: ["Navmesh generation", "Pathfinding", "Steering & crowds", "Decision making|Behavior trees, utility AI, GOAP, FSMs",
        "Perception|Sight, hearing, memory", "Environment queries", "AI debugger"] },
    ui: { title: "User interface", color: 12,
      about: "Menus and HUDs need layout, styling, data binding and gamepad navigation, and must work in every language the game ships in, including right-to-left scripts.",
      items: ["Widget framework|Layout, styling, data binding", "Focus & gamepad nav", "Localization", "Text shaping & RTL",
        "Accessibility", "HUD & menus", "In-world UI"] },
    render: { title: "Rendering", color: 4,
      about: "The largest subsystem. A hardware interface hides the graphics API; above it a frame graph schedules passes for culling, lighting, shadows, effects and post-processing within a fixed time per frame.",
      items: ["Render hardware interface|Graphics API abstraction, command buffers, pipeline state", "Shader system|Language, permutations, hot compilation",
        "Materials & PBR", "Renderer architecture|Forward, deferred, clustered, visibility buffer", "Render / frame graph",
        "Visibility & culling|Frustum, occlusion, LOD selection", "Lighting", "Shadows", "Global illumination & reflections",
        "Meshes & instancing|Skinned, instanced, meshlets, procedural", "Terrain & foliage", "Particles & VFX",
        "Post-processing|Tone mapping, bloom, anti-aliasing, depth of field, grading", "2D sprites & tilemaps",
        "Text & UI rendering", "Debug drawing|Lines, gizmos, overlays", "Cameras & viewports|Split-screen, render-to-texture, cinematics"] },
    anim: { title: "Animation", color: 5, optional: true,
      about: "Animation turns stored motion into poses: sampling clips, blending between them, correcting feet and hands with inverse kinematics, and handing the final skeleton to the renderer.",
      items: ["Skeletons & skinning", "Blend trees & state machines", "Inverse kinematics", "Procedural animation",
        "Retargeting", "Animation compression", "Morph targets", "Cloth & hair hooks", "Sequencer & cutscenes"] },
    phys: { title: "Physics & collision", color: 6, optional: true,
      about: "Collision answers \"what touches what\"; dynamics answers \"what happens next\". Both run at a fixed step so results do not depend on frame rate.",
      items: ["Broadphase", "Narrowphase & shapes", "Scene queries|Raycasts, sweeps, overlaps", "Rigid body solver|Constraints, joints, sleeping",
        "Continuous collision", "Character controller", "Vehicles", "Soft body, cloth, fluids", "Destruction", "Fixed step & determinism"] },
    audio: { title: "Audio", color: 7,
      about: "Audio runs on its own real-time thread and must never miss a deadline. It mixes many voices, places them in 3D space and reacts to the world's geometry.",
      items: ["Device & mixer|Buses, voices, sample rates", "Decoding & streaming", "3D spatialization|Attenuation, panning, HRTF",
        "Occlusion & reverb zones", "DSP effects", "Adaptive music", "Middleware integration"] },
    input: { title: "Input", color: 8,
      about: "Input separates devices from intent: raw keys and sticks become actions such as \"jump\", which players can rebind and which work the same on every device.",
      items: ["Device layer|Keyboard, mouse, gamepad, touch, motion, VR", "Action mapping|Contexts, dead zones, combos",
        "Rebinding", "Gestures & text input", "Haptics"] },
    net: { title: "Networking", color: 11, optional: true,
      about: "Multiplayer means several copies of the world that must agree. Replication decides what each player needs to know; prediction and rollback hide the time it takes to learn it.",
      items: ["Transport|Sockets, reliability, encryption, NAT traversal", "Replication|State sync and delta serialization",
        "Interest management|Relevancy: who needs to know what", "Prediction & reconciliation", "Lag comp. & rollback",
        "Sessions & matchmaking|Lobbies, voice chat", "Authority & anti-cheat", "Dedicated / headless server"] },
    world: { title: "World & simulation model", color: 3,
      about: "The game loop and the object model are the engine's spine. How objects are represented, whether as entities with components or as class hierarchies, shapes the performance and flexibility of everything above.",
      items: ["Game loop|Input → simulate → render; fixed and variable steps", "Game object model|Entity-component-system, components or inheritance",
        "Scene graph & transforms|Hierarchy, levels, prefabs", "Spatial partitioning|Grids, octrees, BVHs, portals",
        "Level streaming", "Save / load|Snapshots, checkpoints, cloud saves", "Gameplay framework|Game modes, rules, controllers, spawning"] },
    asset: { title: "Resource & asset management", color: 2,
      about: "Source files are converted offline into formats the runtime can load in one step. At runtime, a resource manager tracks what is loaded and streams in what will be needed next.",
      items: ["Offline asset pipeline|Importers, converters, texture compression, mesh optimization", "Cooking & packaging",
        "Asset database|IDs, metadata, dependency tracking", "Runtime resource manager|Loading, ref counting, caching, unloading",
        "Streaming|Async loading; texture, world and LOD streaming", "Virtual file system|Archives, compression, patching, mods", "Hot reloading|Assets and code"] },
    found: { title: "Platform & foundation", color: 1,
      about: "Custom allocators, a job system and a reflection layer do more for an engine's speed and tooling than any single feature above them, and every other layer is built on them.",
      items: ["Platform abstraction|Windowing, OS services, files, threads, timers", "App lifecycle|Startup, shutdown, suspend/resume, crashes",
        "Memory allocators|Linear, pool, stack, frame; budgets, leak tracking", "Containers & utilities|Arrays, hash maps, strings, handles",
        "Math library|Vectors, matrices, quaternions, transforms, curves, RNG", "Logging & assertions", "Config & console variables",
        "Time system|Real time, game time, fixed step, scaling, pause", "Job system|Worker threads, task graphs, parallel-for",
        "Reflection & types|Property metadata for serialization, editor, scripting", "Serialization|Binary and text, versioning, compatibility",
        "Events & messaging", "Profiling hooks|CPU/GPU timers, memory tracking"] },
  },
};
