// Plate: Game engine. Structure only; per-component entries live in details-*.js.
ATLAS.register({
  slug: "game-engine",
  title: "Game Engine",
  lede: "Every component of a complete game engine, arranged by layer. A small 2D engine keeps the core and drops most of the optional systems; a large 3D engine has all of them.",
  ground: ["Hardware","Operating system","Drivers","Graphics APIs","Third-party middleware"],
  crossIntro: "Some decisions are not components. Which thread owns which data, how objects refer to each other, whether a simulation is deterministic, and what each system may spend per frame all have to be decided before the components are built, because every one of them depends on the answer.",
  cross: [
    { id: "threading-model", n: "Threading model" },
    { id: "data-ownership-and-lifetimes", n: "Data ownership & lifetimes" },
    { id: "determinism", n: "Determinism" },
    { id: "dependencies-and-layering", n: "Dependencies & layering" },
    { id: "hardware-scalability", n: "Hardware scalability" },
    { id: "performance-budgets", n: "Performance budgets" },
  ],
  bands: [
    { label: "Tools & services", groups: ["tools","debug","plat"],
      intro: "What surrounds the running game: the editor people build it in, the tools that show what it is doing, and the services that ship and operate it." },
    { label: "Gameplay layer", groups: ["script","ai","ui"],
      intro: "Where the game itself lives. These systems turn the engine's capabilities into rules, characters and screens, and are mostly written or configured by designers." },
    { label: "Engine subsystems", groups: ["render","anim","phys","audio","input","net"],
      intro: "Independent specialists. Each reads the world model, does one job well, and should not need to know the others exist." },
    { label: "World model", groups: ["world"],
      intro: "The shared truth of the game: what exists, where it is, and how time advances. Every subsystem above reads or writes it." },
    { label: "Resources", groups: ["asset"],
      intro: "How content gets from an artist's file to memory at the right moment, in the right format, without stalling the frame." },
    { label: "Foundation", groups: ["found"],
      intro: "Everything that is not about games at all: the plumbing that lets the rest of the engine run on many platforms, quickly, in parallel." },
  ],
  groups: {
    tools: { title: "Tools & editor", color: 13, optional: true,
      about: "The editor is often larger than the runtime. It is built on the same reflection system as serialization, so a property added in code appears in the inspector, saves to disk and can be undone without extra work.",
      items: [
        { id: "editor-shell", n: "Editor shell" },
        { id: "undo-redo", n: "Undo / redo" },
        { id: "level-editor", n: "Level editor" },
        { id: "material-and-shader-graphs", n: "Material & shader graphs" },
        { id: "animation-graph-editor", n: "Animation graph editor" },
        { id: "asset-browser", n: "Asset browser" },
        { id: "property-inspector", n: "Property inspector" },
        { id: "play-in-editor", n: "Play-in-editor" },
        { id: "terrain-and-spline-tools", n: "Terrain & spline tools" },
        { id: "build-cook-deploy", n: "Build / cook / deploy" },
        { id: "automated-tests-and-ci", n: "Automated tests & CI" },
        { id: "plugins-and-public-sdk", n: "Plugins & public SDK" },
        { id: "multi-user-editing", n: "Multi-user editing" },
      ] },
    debug: { title: "Debugging & diagnostics", color: 14,
      about: "A game runs sixty times a second and fails in ways that last a single frame. Consoles, visual debuggers, frame capture and deterministic replay exist to make those moments inspectable.",
      items: [
        { id: "console-and-cheats", n: "Console & cheats" },
        { id: "runtime-inspectors", n: "Runtime inspectors" },
        { id: "profilers", n: "Profilers" },
        { id: "frame-capture", n: "Frame capture" },
        { id: "memory-and-gpu-analyzers", n: "Memory & GPU analyzers" },
        { id: "crash-dumps", n: "Crash dumps" },
        { id: "telemetry-and-analytics", n: "Telemetry & analytics" },
        { id: "deterministic-replay", n: "Deterministic replay" },
      ] },
    plat: { title: "Platform services & release", color: 15, optional: true,
      about: "Each store and console has its own accounts, achievements, entitlements and certification rules. A thin service layer keeps those differences out of gameplay code.",
      items: [
        { id: "platform-sdks", n: "Platform SDKs" },
        { id: "store-and-dlc", n: "Store & DLC" },
        { id: "cloud-saves", n: "Cloud saves" },
        { id: "accounts-and-leaderboards", n: "Accounts & leaderboards" },
        { id: "live-ops-and-remote-config", n: "Live ops & remote config" },
        { id: "patching", n: "Patching" },
        { id: "mod-distribution", n: "Mod distribution" },
        { id: "console-certification", n: "Console certification" },
        { id: "ratings-and-parental-controls", n: "Ratings & parental controls" },
      ] },
    script: { title: "Scripting & gameplay logic", color: 9,
      about: "Gameplay changes far more often than the engine, so it is kept in a faster-to-iterate layer: a scripting language, visual graphs or plain data tables, with reusable frameworks for common game features.",
      items: [
        { id: "scripting-vm-and-bindings", n: "Scripting VM & bindings" },
        { id: "visual-scripting", n: "Visual scripting" },
        { id: "data-tables-and-curves", n: "Data tables & curves" },
        { id: "coroutines-and-async", n: "Coroutines & async" },
        { id: "timers", n: "Timers" },
        { id: "state-machines", n: "State machines" },
        { id: "behavior-trees", n: "Behavior trees" },
        { id: "ability-system", n: "Ability system" },
        { id: "inventory", n: "Inventory" },
        { id: "quests-and-dialogue", n: "Quests & dialogue" },
      ] },
    ai: { title: "Artificial intelligence", color: 10, optional: true,
      about: "Game AI is about believable behavior on a budget: finding paths through the world, choosing what to do next, and sensing only what a character could plausibly know.",
      items: [
        { id: "navmesh-generation", n: "Navmesh generation" },
        { id: "pathfinding", n: "Pathfinding" },
        { id: "steering-and-crowds", n: "Steering & crowds" },
        { id: "decision-making", n: "Decision making" },
        { id: "perception", n: "Perception" },
        { id: "environment-queries", n: "Environment queries" },
        { id: "ai-debugger", n: "AI debugger" },
      ] },
    ui: { title: "User interface", color: 12,
      about: "Menus and HUDs need layout, styling, data binding and gamepad navigation, and must work in every language the game ships in, including right-to-left scripts.",
      items: [
        { id: "widget-framework", n: "Widget framework" },
        { id: "focus-and-gamepad-nav", n: "Focus & gamepad nav" },
        { id: "localization", n: "Localization" },
        { id: "text-shaping-and-rtl", n: "Text shaping & RTL" },
        { id: "accessibility", n: "Accessibility" },
        { id: "hud-and-menus", n: "HUD & menus" },
        { id: "in-world-ui", n: "In-world UI" },
      ] },
    render: { title: "Rendering", color: 4,
      about: "The largest subsystem. A hardware interface hides the graphics API; above it a frame graph schedules passes for culling, lighting, shadows, effects and post-processing within a fixed time per frame.",
      items: [
        { id: "render-hardware-interface", n: "Render hardware interface" },
        { id: "shader-system", n: "Shader system" },
        { id: "materials-and-pbr", n: "Materials & PBR" },
        { id: "renderer-architecture", n: "Renderer architecture" },
        { id: "render-frame-graph", n: "Render / frame graph" },
        { id: "visibility-and-culling", n: "Visibility & culling" },
        { id: "lighting", n: "Lighting" },
        { id: "shadows", n: "Shadows" },
        { id: "global-illumination", n: "Global illumination & reflection" },
        { id: "meshes-and-instancing", n: "Meshes & instancing" },
        { id: "terrain-and-foliage", n: "Terrain & foliage" },
        { id: "particles-and-vfx", n: "Particles & VFX" },
        { id: "post-processing", n: "Post-processing" },
        { id: "2d-sprites-and-tilemaps", n: "2D sprites & tilemaps" },
        { id: "text-and-ui-rendering", n: "Text & UI rendering" },
        { id: "debug-drawing", n: "Debug drawing" },
        { id: "cameras-and-viewports", n: "Cameras & viewports" },
      ] },
    anim: { title: "Animation", color: 5, optional: true,
      about: "Animation turns stored motion into poses: sampling clips, blending between them, correcting feet and hands with inverse kinematics, and handing the final skeleton to the renderer.",
      items: [
        { id: "skeletons-and-skinning", n: "Skeletons & skinning" },
        { id: "blend-trees-and-state-machines", n: "Blend trees & state machines" },
        { id: "inverse-kinematics", n: "Inverse kinematics" },
        { id: "procedural-animation", n: "Procedural animation" },
        { id: "retargeting", n: "Retargeting" },
        { id: "animation-compression", n: "Animation compression" },
        { id: "morph-targets", n: "Morph targets" },
        { id: "cloth-and-hair-hooks", n: "Cloth & hair hooks" },
        { id: "sequencer-and-cutscenes", n: "Sequencer & cutscenes" },
      ] },
    phys: { title: "Physics & collision", color: 6, optional: true,
      about: "Collision answers \"what touches what\"; dynamics answers \"what happens next\". Both run at a fixed step so results do not depend on frame rate.",
      items: [
        { id: "broadphase", n: "Broadphase" },
        { id: "narrowphase-and-shapes", n: "Narrowphase & shapes" },
        { id: "scene-queries", n: "Scene queries" },
        { id: "rigid-body-solver", n: "Rigid body solver" },
        { id: "continuous-collision", n: "Continuous collision" },
        { id: "character-controller", n: "Character controller" },
        { id: "vehicles", n: "Vehicles" },
        { id: "soft-body-cloth-fluids", n: "Soft body, cloth, fluids" },
        { id: "destruction", n: "Destruction" },
        { id: "fixed-step-and-determinism", n: "Fixed step & determinism" },
      ] },
    audio: { title: "Audio", color: 7,
      about: "Audio runs on its own real-time thread and must never miss a deadline. It mixes many voices, places them in 3D space and reacts to the world's geometry.",
      items: [
        { id: "device-and-mixer", n: "Device & mixer" },
        { id: "decoding-and-streaming", n: "Decoding & streaming" },
        { id: "3d-spatialization", n: "3D spatialization" },
        { id: "occlusion-and-reverb-zones", n: "Occlusion & reverb zones" },
        { id: "dsp-effects", n: "DSP effects" },
        { id: "adaptive-music", n: "Adaptive music" },
        { id: "middleware-integration", n: "Middleware integration" },
      ] },
    input: { title: "Input", color: 8,
      about: "Input separates devices from intent: raw keys and sticks become actions such as \"jump\", which players can rebind and which work the same on every device.",
      items: [
        { id: "device-layer", n: "Device layer" },
        { id: "action-mapping", n: "Action mapping" },
        { id: "rebinding", n: "Rebinding" },
        { id: "gestures-and-text-input", n: "Gestures & text input" },
        { id: "haptics", n: "Haptics" },
      ] },
    net: { title: "Networking", color: 11, optional: true,
      about: "Multiplayer means several copies of the world that must agree. Replication decides what each player needs to know; prediction and rollback hide the time it takes to learn it.",
      items: [
        { id: "transport", n: "Transport" },
        { id: "replication", n: "Replication" },
        { id: "interest-management", n: "Interest management" },
        { id: "prediction-and-reconciliation", n: "Prediction & reconciliation" },
        { id: "lag-comp-and-rollback", n: "Lag comp. & rollback" },
        { id: "sessions-and-matchmaking", n: "Sessions & matchmaking" },
        { id: "authority-and-anti-cheat", n: "Authority & anti-cheat" },
        { id: "dedicated-headless-server", n: "Dedicated / headless server" },
      ] },
    world: { title: "World & simulation model", color: 3,
      about: "The game loop and the object model are the engine's spine. How objects are represented, whether as entities with components or as class hierarchies, shapes the performance and flexibility of everything above.",
      items: [
        { id: "game-loop", n: "Game loop" },
        { id: "game-object-model", n: "Game object model" },
        { id: "scene-graph-and-transforms", n: "Scene graph & transforms" },
        { id: "spatial-partitioning", n: "Spatial partitioning" },
        { id: "level-streaming", n: "Level streaming" },
        { id: "save-load", n: "Save / load" },
        { id: "gameplay-framework", n: "Gameplay framework" },
      ] },
    asset: { title: "Resource & asset management", color: 2,
      about: "Source files are converted offline into formats the runtime can load in one step. At runtime, a resource manager tracks what is loaded and streams in what will be needed next.",
      items: [
        { id: "offline-asset-pipeline", n: "Offline asset pipeline" },
        { id: "cooking-and-packaging", n: "Cooking & packaging" },
        { id: "asset-database", n: "Asset database" },
        { id: "runtime-resource-manager", n: "Runtime resource manager" },
        { id: "streaming", n: "Streaming" },
        { id: "virtual-file-system", n: "Virtual file system" },
        { id: "hot-reloading", n: "Hot reloading" },
      ] },
    found: { title: "Platform & foundation", color: 1,
      about: "Custom allocators, a job system and a reflection layer do more for an engine's speed and tooling than any single feature above them, and every other layer is built on them.",
      items: [
        { id: "platform-abstraction", n: "Platform abstraction" },
        { id: "app-lifecycle", n: "App lifecycle" },
        { id: "memory-allocators", n: "Memory allocators" },
        { id: "containers-and-utilities", n: "Containers & utilities" },
        { id: "math-library", n: "Math library" },
        { id: "logging-and-assertions", n: "Logging & assertions" },
        { id: "config-and-console-variables", n: "Config & console variables" },
        { id: "time-system", n: "Time system" },
        { id: "job-system", n: "Job system" },
        { id: "reflection-and-types", n: "Reflection & types" },
        { id: "serialization", n: "Serialization" },
        { id: "events-and-messaging", n: "Events & messaging" },
        { id: "profiling-hooks", n: "Profiling hooks" },
      ] },
  },
});
