// Game engine details: input, networking, world model, resources, foundation.
ATLAS.details("game-engine", {
  "device-layer": {
    s: "Normalizes keyboards, mice, gamepads, touch surfaces and motion sensors into a uniform stream of timestamped raw events, hiding platform differences, hot-plugging and per-device quirks from everything above it.",
    d: "The device layer talks to each platform's input interface and turns whatever it reports into a small set of device classes: buttons, axes, pointers and touch contacts. Events are timestamped at the moment of arrival, not when the frame consumes them, and queued so the game loop can drain them once per tick. It tracks connection and disconnection, assigns devices to players, applies dead zones and calibration, and distinguishes physical key position from the character a key produces. The hard parts are the long tail of controllers that misreport their layout, and keeping latency low without losing events when the frame rate dips.",
    k: [
      "Poll vs event delivery: polling gives one consistent snapshot per frame and is simple; events preserve exact ordering and sub-frame timing but need a queue and more careful threading.",
      "Physical key positions vs produced characters: positions keep layouts like WASD usable on every keyboard, while characters are required for text entry and shortcuts shown to the player.",
      "Dead zones applied here vs later: filtering at the device level keeps every consumer consistent, but a fixed value cannot be tuned per game or per player without exposing settings.",
    ],
    p: [
      "Reading input only at the start of the frame, so a button pressed and released between two samples is lost entirely.",
      "Assuming a controller layout from its name, then mapping triggers or sticks wrongly on third-party devices that report differently.",
      "Ignoring hot-plug, so unplugging a pad leaves a stuck axis or crashes when its handle is reused.",
    ],
    v: "Plug and unplug each supported device class mid-session while logging raw events. Verify every press and release arrives once with a timestamp, no axis stays stuck after disconnect, and a tap shorter than one frame still registers.",
    dep: ["platform-abstraction", "time-system"],
  },
  "action-mapping": {
    s: "Translates raw device events into named game actions and axes such as jump or move, so gameplay code reads intent and works identically across keyboard, gamepad and touch.",
    d: "Gameplay never asks whether a particular key is down; it asks whether the jump action started this frame. A mapping table binds device inputs to actions, with triggers that decide when the action fires: pressed, released, held, tapped, double-tapped or past a threshold. Modifiers shape values, for example inverting an axis or normalizing a diagonal. Mappings are organized into contexts that stack, so a menu context can swallow input before the gameplay context sees it. The system also tracks which device the player last used, which drives on-screen prompts. Getting consumption order and context priority right is where most bugs live.",
    k: [
      "Digital actions vs typed values: a single value type with button, one-axis and two-axis forms covers more devices, but costs a conversion rule whenever a button feeds an axis.",
      "Stacked contexts with consumption vs one flat map: stacking lets menus and vehicles cleanly take over, but makes the active bindings harder to reason about and to debug.",
      "Evaluate on the frame vs on the fixed simulation step: fixed-step evaluation keeps deterministic replays exact, while per-frame evaluation feels more responsive at high frame rates.",
    ],
    p: [
      "Two contexts both consuming the same input, so closing a menu also fires a jump, or a button stays dead after a context pops.",
      "Treating a held trigger as a repeated press, causing duplicate actions on frame-rate changes.",
      "Showing button prompts from the default device instead of the device the player is actually using.",
    ],
    v: "Open a menu over gameplay and press the shared confirm button: only the menu reacts. Close it and the character responds on the same frame. Record the inputs and replay them; the action sequence must match exactly.",
    dep: ["device-layer", "events-and-messaging"],
  },
  "rebinding": {
    s: "Lets players reassign actions to different inputs, validates conflicts, and saves the result per profile and per device so custom controls persist across sessions and platforms.",
    d: "Rebinding sits on top of action mapping and stores user overrides as a diff against the shipped defaults, so later updates to the defaults still reach players who changed only a few keys. A capture mode listens for the next input, rejects reserved keys, and detects conflicts within the same context, offering to swap or unbind. Overrides are serialized into the profile, which may sync through cloud saves. The user interface must display the current binding as a glyph or label appropriate to the active device. Accessibility depends heavily on this system: remapping, toggle instead of hold, and one-handed layouts.",
    k: [
      "Store overrides as a diff vs a full copy: diffs survive default changes and stay small, but make it harder to see the final effective map without resolving it.",
      "Conflicts allowed vs forbidden: permitting duplicate bindings across contexts is flexible and natural, while forbidding them inside one context prevents silent double actions.",
      "Rebind actions vs raw inputs: binding to actions keeps the model clean; binding raw inputs to raw inputs lets players fix odd hardware but bypasses all context logic.",
    ],
    p: [
      "Letting a player unbind the only way to open the menu, leaving the game impossible to control without deleting the profile.",
      "Saving bindings with device-specific identifiers, so a replaced controller silently loses every custom mapping.",
      "Updating default bindings in a patch and overwriting the player's overrides because they were stored as a full copy.",
    ],
    v: "Rebind jump to another key, restart, and confirm it persists. Then ship a patch changing an unrelated default and confirm the override survives. Try to bind a reserved key and a conflicting key and check both are handled.",
    dep: ["action-mapping", "serialization", "config-and-console-variables"],
  },
  "gestures-and-text-input": {
    s: "Recognizes multi-touch gestures such as tap, swipe and pinch, and handles text entry including on-screen keyboards and composition methods for languages that build characters from several keystrokes.",
    d: "Gesture recognition consumes raw touch contacts over time and runs state machines that decide whether a pair of fingers is a pinch, a rotation or two unrelated drags, resolving conflicts between competing recognizers. Text input is a separate path from key presses: the platform delivers composed characters, including partial composition that must be displayed and then committed or cancelled. On touch devices an on-screen keyboard resizes the viewport and must not hide the field being edited. Correctness here means supporting input method editors, paste, selection and cursor movement across all scripts, not just Latin typing.",
    k: [
      "Recognizers in the engine vs the platform: platform gestures match user expectations and accessibility settings, while engine-side recognition behaves the same everywhere and can be tuned for the game.",
      "Raw key events vs a text input channel: using key events for text is simpler but breaks composition, dead keys and mobile keyboards, so a dedicated channel is nearly always necessary.",
      "Gesture arbitration by priority vs first-to-claim: priority is predictable; first-to-claim feels more natural but makes behavior depend on finger timing.",
    ],
    p: [
      "Building text fields from key-down events, which makes Chinese, Japanese and Korean input and emoji pickers impossible.",
      "Hard-coded pixel thresholds for swipe distance that behave very differently on high-density phones and large tablets.",
      "Not routing text input into the focused field, so shortcuts fire while the player is typing.",
    ],
    v: "On a touch device, perform a pinch while a drag is active and confirm only the intended gesture fires. In a text field, enter text with an input method editor that uses composition and confirm preview, commit and cancel all behave.",
    dep: ["device-layer", "action-mapping"],
  },
  "haptics": {
    s: "Drives vibration motors, adaptive triggers and tactile actuators from authored patterns, so impacts, engines and surfaces can be felt with consistent intensity across different controllers.",
    d: "Haptics turns gameplay events into waveforms or motor intensities and sends them to the device through the device layer. Simple controllers have two rumble motors with different frequency response; newer hardware has high-bandwidth actuators and triggers with resistance profiles. Authored patterns are played, layered, scaled by a master intensity setting and faded out, with priorities so a minor effect never cancels an important one. Effects must stop cleanly on pause, disconnect and death. Because devices differ widely, a thin abstraction maps a generic effect onto whatever the connected hardware can express.",
    k: [
      "Authored waveforms vs two-motor intensity values: waveforms give rich feel on capable hardware, while simple intensities work everywhere but cannot convey texture.",
      "Derive haptics from audio vs author separately: deriving is cheap and syncs automatically, but authored patterns feel more deliberate and avoid buzzing on every sound.",
      "Global intensity setting vs per-effect scaling: a global slider is expected for comfort and accessibility, while per-effect scaling lets the designer keep important cues perceptible.",
    ],
    p: [
      "A looping rumble that is never stopped when the game pauses or the controller disconnects, leaving the device vibrating.",
      "Authoring on one controller and shipping unchanged, so the effect is too strong or imperceptible on another.",
      "Stacking many simultaneous effects without a limit, which saturates the motor and feels like noise.",
    ],
    v: "Trigger a sustained effect, then pause, disconnect the controller and die in separate runs; vibration stops each time. Play the same impact on two different controller types and confirm intensity is comparable and the master setting scales it.",
    dep: ["device-layer", "action-mapping"],
  },

  "transport": {
    s: "Moves packets between machines over unreliable or reliable channels, adding connection handling, fragmentation, ordering options, congestion awareness and encryption on top of the operating system's datagram sockets.",
    d: "Games usually build on datagrams because a lost position update should be superseded, not retransmitted late. The transport adds a connection handshake, sequence numbers and acknowledgments, and offers per-message reliability and ordering choices so state snapshots, voice and critical commands can share a connection. It fragments large messages, estimates round-trip time and bandwidth, throttles sending, detects timeouts and encrypts traffic against tampering. It must also cross network address translation, which often requires a relay. Everything above it is shaped by what it guarantees, so its contract must be explicit.",
    k: [
      "Datagrams with a custom reliability layer vs a stream connection: custom layers avoid head-of-line blocking and allow mixed reliability, while streams are simpler and less error-prone but stall everything behind one lost packet.",
      "Direct peer connections vs relays: direct links minimize latency and cost, but expose player addresses and fail behind restrictive network address translation.",
      "Encrypt everything vs authenticate only: full encryption protects privacy and blocks injection, while authentication alone is cheaper and enough to reject forged packets.",
    ],
    p: [
      "Sending more than the path can carry, so queues grow, latency climbs and a burst of loss collapses the connection.",
      "Trusting the sender address of unauthenticated packets, enabling spoofed connections and amplification attacks.",
      "Retransmitting stale state reliably, so old positions arrive after newer ones and are applied.",
    ],
    v: "Run a client and server through a link emulator with 150 ms latency, 2 percent loss and reordering. Reliable messages arrive once and in order, unreliable ones may drop, and throughput stays below the configured send budget.",
    dep: ["platform-abstraction", "time-system", "memory-allocators"],
  },
  "replication": {
    s: "Keeps copies of the world on many machines in agreement by sending state changes from the authoritative owner to others, using property deltas, remote procedure calls and object lifecycle messages.",
    d: "Replication marks which properties of which objects are shared, then each tick the owner compares current values with what each client last acknowledged and sends only the difference. Reflection usually generates the serializers. Besides state, it carries object creation and destruction, ownership changes and one-shot events or remote calls that must not be lost. Bandwidth is bounded by quantizing values, prioritizing important objects and sending less often for distant ones. The central difficulty is consistency: references to other objects must be translated to network identifiers, and state that arrives out of order must not corrupt the receiver.",
    k: [
      "State replication vs sending inputs only: state is robust to late joiners and divergence but costs bandwidth, while input-only is cheap but needs perfect determinism.",
      "Per-property delta compression vs full snapshots: deltas save bandwidth at scale, but need per-client acknowledgment tracking and more server memory.",
      "Reliable events vs reliable state: events capture one-off actions but can be missed by late joiners, while replicated state is always recoverable but cannot express instantaneous occurrences.",
    ],
    p: [
      "Replicating references by memory address or index, which breaks when objects are created in a different order on each machine.",
      "Sending an event as a state change, so a client that joins later replays an explosion that happened a minute ago.",
      "Forgetting to quantize floating point values, burning bandwidth on precision nobody can perceive.",
    ],
    v: "Spawn, modify and destroy objects on the server while a client joins mid-session. The late client reaches an identical world, measured bandwidth per client stays under budget, and destroyed objects do not linger.",
    dep: ["transport", "reflection-and-types", "serialization", "game-object-model"],
  },
  "interest-management": {
    s: "Decides which objects each client needs to hear about, so bandwidth and server work scale with what a player can plausibly see or affect rather than with the whole world.",
    d: "For each client the server computes a relevance set, typically from spatial proximity, team membership, line of sight or explicit ownership. It uses a spatial structure to find nearby objects cheaply, then ranks them by priority and distance to fit the bandwidth budget. Objects entering the set are created on the client; those leaving are removed or frozen. Update frequency is scaled by relevance. Interest management is also a security boundary: data never sent cannot be read by a cheating client. The hard part is hysteresis and edge cases, such as objects that matter because of a remote effect.",
    k: [
      "Radius-based relevance vs grid or region cells: radius is precise per player, while cells are cheaper to compute for many players but include objects slightly outside view.",
      "Visibility-based filtering vs distance only: visibility sends far less and hides hidden enemies from cheaters, but costs server computation and can cause objects to pop in late.",
      "Drop out of the set immediately vs with hysteresis: hysteresis avoids thrash at boundaries, but holds some objects slightly longer than needed.",
    ],
    p: [
      "Objects flickering in and out at the relevance boundary, repeatedly creating and destroying them on the client.",
      "Omitting something relevant only through a remote effect, such as a sniper outside the radius who is still shooting at the player.",
      "Computing relevance per client per object every tick with no spatial structure, so server cost grows with the square of player count.",
    ],
    v: "With 100 simulated players in a large world, record bytes sent per client. Confirm bandwidth stays flat as total world size grows, a client receives no data for objects beyond its set, and nothing flickers while walking along the boundary.",
    dep: ["replication", "spatial-partitioning"],
  },
  "prediction-and-reconciliation": {
    s: "Applies the local player's input immediately without waiting for the server, then corrects the result when authoritative state arrives, so controls feel instant despite network delay.",
    d: "The client simulates its own character with the same movement code as the server and tags each input with a sequence number, keeping unacknowledged inputs in a buffer. When a server state arrives for a past input, the client rewinds to it, replays the remaining buffered inputs and compares the result with its prediction. Small differences are smoothed visually; large ones snap. Other players are not predicted the same way and are shown interpolated slightly in the past. This demands movement code that is deterministic and shared, with state cleanly separable so it can be reset and replayed.",
    k: [
      "Smooth error correction vs snapping: smoothing hides corrections and looks natural, but briefly leaves the visual position wrong, which matters in precision platforming or aiming.",
      "Predict only the local player vs everything: local-only is cheap and rarely wrong, while predicting others reduces perceived lag but produces visible corrections when guesses fail.",
      "Replay from state vs reconcile by offset: replaying is accurate but costs CPU for long buffers, while offsetting is cheap and drifts when forces differ.",
    ],
    p: [
      "Predicting with a variable time step so replay produces different results than the server, causing constant small corrections.",
      "Predicting actions that depend on state the client cannot know, like another player's door, and then rolling back visibly.",
      "Letting the input buffer grow without bound after a stall, producing a long replay that hitches the frame.",
    ],
    v: "Run a client at 150 ms latency and 2 percent loss with scripted input. Compare predicted and server positions: the mean error stays near zero, corrections remain below a visible threshold, and a recorded session shows no rubber-banding.",
    dep: ["replication", "fixed-step-and-determinism", "character-controller", "action-mapping"],
  },
  "lag-comp-and-rollback": {
    s: "Compensates for latency in shared outcomes: lag compensation rewinds the server to judge shots as the shooter saw them, and rollback resimulates the whole game after late inputs.",
    d: "Lag compensation keeps a short history of object positions on the server. When a hit request arrives, the server rewinds targets to the time the shooter's client displayed, runs the query, and restores the present. Rollback networking goes further: every machine simulates locally, predicts remote inputs, and when the real input arrives, restores a saved state and resimulates forward to the present. It requires a fast, fully deterministic, serializable simulation. Both approaches trade fairness between players for visible corrections, and both need a cap on how far back they will go.",
    k: [
      "Server-side rewind vs rollback of the whole simulation: rewinding is local to hit tests and works with authoritative servers, while rollback gives instant responsiveness for fighting-style games but needs determinism.",
      "Rewind limit: a generous limit helps high-latency players but lets them hit targets that already took cover, so a cap near 200 ms is common.",
      "Save full state each frame vs deltas: full snapshots are simple and fast to restore, while deltas use less memory but make restoration more complex.",
    ],
    p: [
      "Simulation containing nondeterminism, such as unordered iteration or uninitialized memory, so rollback clients silently drift apart.",
      "Rewinding positions but not animation state or hitboxes, so shots hit where the character visually was not.",
      "Resimulation that is slower than real time, so each rollback causes a stall that triggers another.",
    ],
    v: "Fire at a moving target from a client with 120 ms delay: the server registers the hit when the shooter's screen showed it. For rollback, run two builds with injected delay and compare per-frame state hashes; they must match.",
    dep: ["prediction-and-reconciliation", "scene-queries", "fixed-step-and-determinism", "replication"],
  },
  "sessions-and-matchmaking": {
    s: "Creates, finds and joins multiplayer sessions: lobbies, party handling, skill and latency based matchmaking, server allocation and migration or reconnection when someone drops.",
    d: "A session service tracks groups of players and the game instance they are headed to. Matchmaking collects waiting players, scores candidate groups by skill, region, latency and party composition, relaxes constraints the longer they wait, and then requests a server and hands out connection tokens. Lobbies handle readiness, settings and chat. Once playing, the system must handle disconnects, late joins and host migration if there is no dedicated server. It usually talks to platform services for identity and invitations. The real challenge is balancing queue time against match quality.",
    k: [
      "Relax constraints over time vs fixed quality: relaxing keeps queue times bounded at the price of some lopsided matches, while strict rules guarantee quality but can leave players waiting indefinitely.",
      "Dedicated servers vs peer hosting: dedicated servers are fair and secure but cost money, while host players are free but give the host an advantage and fail when they leave.",
      "Rating system: simple Elo-style ratings are easy to explain, while uncertainty-aware ratings converge faster for new players but are harder to tune.",
    ],
    p: [
      "Matching on skill alone and ignoring region, putting players with high ping into the same match.",
      "Handing out join tokens that never expire or are not bound to a player, allowing session hijacking.",
      "No reconnect path, so a brief network drop permanently removes a player from a match.",
    ],
    v: "Queue several hundred simulated players with varied skill and regions. Measure the median wait and rating spread of matches, kill a client mid-match and confirm it can rejoin, and confirm an expired token is rejected.",
    dep: ["transport", "accounts-and-leaderboards", "dedicated-headless-server"],
  },
  "authority-and-anti-cheat": {
    s: "Decides which machine owns the truth about each piece of state and validates everything clients claim, so modified or malicious clients cannot grant themselves advantages.",
    d: "In a server-authoritative design, clients send intent and the server decides outcomes. Every client message is validated: rates, ranges, line of sight, cooldowns and resource costs are all checked against server state. Sensitive data, such as the position of unseen opponents, is withheld through interest management. Detection layers add statistical analysis of behavior, integrity checks on client code and reporting. Authority can be split, giving clients ownership of cosmetic or low-risk state for responsiveness. No design is perfect; the aim is to make cheating expensive and to limit what a cheater can break for others.",
    k: [
      "Full server authority vs client authority for movement: server authority prevents speed and teleport hacks but needs prediction to feel responsive, while client authority is smooth but trivially exploitable.",
      "Withhold hidden data vs rely on detection: not sending it defeats wall hacks outright, while detection only catches known methods after the fact.",
      "Client-side integrity checks vs server-side analysis: client checks raise the cost of tampering but can be bypassed, while server analysis cannot be bypassed but needs time and good signals.",
    ],
    p: [
      "Trusting a client-reported hit, damage value or position because it was convenient to implement.",
      "Validating messages for correctness but not for rate, allowing a flood of valid actions to overwhelm the server.",
      "Shipping server-only secrets or debug commands in the client build.",
    ],
    v: "Run a test client that sends out-of-range hits, teleports, impossible fire rates and malformed packets. The server rejects each, logs the violation, and no other player's state is changed.",
    dep: ["replication", "interest-management", "transport"],
  },
  "dedicated-headless-server": {
    s: "Runs the authoritative simulation without graphics, audio or window, hosting many matches efficiently from the same game code as the client.",
    d: "A headless build compiles out or stubs rendering, audio, input and presentation, keeping simulation, physics, networking and gameplay. Because it shares code with the client, the module boundaries must keep gameplay free of rendering dependencies. The server runs a fixed tick, often at lower cost per match so many instances share a machine, and exposes health checks, metrics and a way to be started, drained and stopped by an orchestrator. It loads only the data it needs, such as collision rather than visual meshes. Logging, crash capture and scaling are operational concerns as important as the game logic.",
    k: [
      "One codebase with stubs vs a separate server program: sharing guarantees identical rules, while a separate program is leaner but risks divergence.",
      "One process per match vs many matches per process: isolation is simpler and contains crashes, while multiplexing uses memory and CPU more efficiently.",
      "Fixed tick rate: higher rates reduce latency and improve hit detection but increase cost per match and bandwidth.",
    ],
    p: [
      "Gameplay code that quietly calls into rendering or audio, so the server crashes or loads huge assets it never needs.",
      "Processes that never exit cleanly after a match, leaking memory until the machine is lost.",
      "Tick time spikes from garbage or loading during play, which every connected client feels at once.",
    ],
    v: "Start the server with no display or audio device and connect scripted clients. Confirm tick time stays under budget for a full match, memory is flat across repeated matches, and the process exits cleanly on drain.",
    dep: ["game-loop", "transport", "platform-abstraction", "logging-and-assertions"],
  },

  "game-loop": {
    s: "The central cycle that reads input, advances the simulation by a fixed step, updates the world and presents a frame, defining the order in which every subsystem runs.",
    d: "Each iteration measures elapsed real time, drains input, runs zero or more fixed simulation steps to catch up, and then performs a variable-rate update and render with an interpolation factor. Subsystems are given explicit phases, for example pre-physics, physics, post-physics and late update, so ordering is deliberate. The loop also decides how to pace itself: syncing to the display, sleeping, or running uncapped. A maximum catch-up limit stops long frames from causing a spiral where simulation can never keep up. Its structure is the engine's most important contract, because scheduling bugs surface as subtle one-frame-late behavior.",
    k: [
      "Fixed step with interpolation vs variable step: fixed gives stable physics and deterministic replay, while variable is simpler but makes results depend on frame rate.",
      "Single-threaded phases vs parallel task graph: phases are easy to reason about, while a task graph uses more cores but requires explicit dependencies between systems.",
      "Catch-up limit: bounding steps per frame prevents a death spiral but lets simulation time fall behind real time.",
    ],
    p: [
      "Using the frame delta for gameplay values such as movement, so behavior changes with frame rate.",
      "Reading transforms before the system that updates them has run, creating a consistent one-frame lag.",
      "Allowing unbounded catch-up after a hitch, producing seconds of repeated steps and a stall.",
    ],
    v: "Run the same scripted scenario at 30, 60 and 144 frames per second and with an artificial 500 ms hitch. Final world state is identical, no spiral occurs, and a logged phase order matches the documented one every frame.",
    dep: ["time-system", "job-system", "app-lifecycle", "events-and-messaging"],
  },
  "game-object-model": {
    s: "Defines how things in the world are represented and composed: entities with components, class hierarchies, or a mix, and how behavior and data are attached to them.",
    d: "The object model determines how a designer builds a door, an enemy or a light, and how the engine stores and iterates them. Entity-component designs separate identity, data and behavior, and data-oriented variants store components in contiguous arrays so systems iterate them quickly. Class hierarchies are familiar but grow rigid. The model also owns lifetimes, creation and destruction, handles that stay safe when objects die, and how objects refer to one another. It connects to reflection for editing, serialization for saving and replication for networking, so a change here ripples through all of them.",
    k: [
      "Data-oriented components in arrays vs objects holding components: arrays give cache-friendly iteration for many similar things, while objects are simpler to script and inspect.",
      "Inheritance vs composition: inheritance is quick to start with, but composition avoids the diamond of behaviors and lets designers mix capabilities freely.",
      "Handles with generation counters vs raw pointers: handles detect dead objects safely at a small lookup cost, while pointers are fast and can dangle.",
    ],
    p: [
      "Holding pointers to objects across frames, then using one after its target was destroyed by a deferred deletion.",
      "Letting component-to-component dependencies grow until every behavior needs to know about every other.",
      "Destroying objects in the middle of iteration, which invalidates the containers being walked.",
    ],
    v: "Spawn and destroy ten thousand objects of mixed composition in a stress run, including destroys during iteration. No crash occurs, stale handles report invalid, and a save and reload reproduces the same set.",
    dep: ["reflection-and-types", "memory-allocators", "containers-and-utilities", "data-ownership-and-lifetimes"],
  },
  "scene-graph-and-transforms": {
    s: "Organizes objects into a parent-child hierarchy so moving a parent moves its children, and maintains local and world transforms efficiently for every object.",
    d: "Each node stores a local transform relative to its parent; the world transform is the product up the chain, cached and recomputed only for subtrees marked dirty. Updates are ordered parent first, often in a flattened array by depth so they can run in parallel by level. The graph supports attachment to bones and sockets, reparenting while preserving world position, and handles scale and rotation composition, including the well-known problem that non-uniform scale under rotation introduces shear. Precision is a concern for large worlds, where coordinates far from the origin lose accuracy.",
    k: [
      "Dirty flags with lazy update vs recompute every frame: lazy saves work when little moves, while full recompute is simpler and parallelizes better when most things move.",
      "Deep hierarchy vs flat with explicit attachments: deep trees are intuitive for artists but cost update time, while flat layouts are fast and need extra constraints for the rare relationships.",
      "Single precision with a floating origin vs double precision positions: shifting the origin keeps rendering precise cheaply, while doubles simplify logic but cost memory and conversion.",
    ],
    p: [
      "Reading a world transform after changing the local one in the same frame without forcing an update, getting last frame's value.",
      "Non-uniform scale on a parent that rotates children, producing shear that physics and animation cannot represent.",
      "Jittering geometry far from the origin because positions are stored in single precision.",
    ],
    v: "Build a hierarchy five levels deep, rotate and scale the root, and compare each child's world position against an independently computed matrix product. Reparent while keeping world position and confirm nothing visibly moves.",
    dep: ["game-object-model", "math-library"],
  },
  "spatial-partitioning": {
    s: "Indexes objects by location in grids, trees or hashes so queries for what is near, inside or visible avoid examining everything in the world.",
    d: "A uniform grid, hash grid, quadtree, octree or bounding volume hierarchy stores object bounds so that region, ray and nearest-neighbor queries touch only a few candidates. Different consumers want different structures: culling, collision, audio and AI each query differently, so several indexes often coexist. Moving objects must update their entries cheaply, which favors loose bounds and incremental updates. Static geometry can use an expensive-to-build, fast-to-query tree built offline. The decision depends on object density, size variance and how much moves each frame, and a bad fit leaves one cell or node holding most of the world.",
    k: [
      "Grid vs hierarchy: grids update in constant time and suit uniform density, while hierarchies handle varying density and size but cost more to rebalance.",
      "Separate static and dynamic structures: static ones can be optimized offline, while dynamic ones must support cheap updates, so splitting avoids compromising either.",
      "Loose bounds vs tight bounds: loose bounds avoid reinserting on small moves, but return more false candidates to filter.",
    ],
    p: [
      "Using a uniform grid for a world with a dense town and empty wilderness, so most queries land in a few huge cells.",
      "Rebuilding the whole structure every frame because incremental updates were never implemented.",
      "Objects larger than a cell appearing in many cells, then being returned multiple times from one query.",
    ],
    v: "Insert a hundred thousand moving and static objects and run random region and ray queries, comparing results against brute force. Results match exactly and query plus update time stays well under the frame budget.",
    dep: ["math-library", "containers-and-utilities", "memory-allocators"],
  },
  "level-streaming": {
    s: "Loads and unloads parts of a large world around the player in the background, so the world appears seamless without a loading screen and memory stays bounded.",
    d: "The world is divided into cells or sublevels with declared bounds and dependencies. A streaming manager observes the player and other observers, prioritizes cells by distance and direction of travel, and requests their assets from the resource manager. Loading is asynchronous: data is read and decoded off the main thread, then objects are added to the world in small time-sliced steps to avoid hitches. Unloading must wait until nothing references the cell. Persistent state, such as a moved crate, needs to survive an unload. The hard part is predicting what is needed early enough on slow storage.",
    k: [
      "Grid cells vs hand-authored sublevels: grids partition automatically and scale to open worlds, while authored sublevels give designers precise control over what loads together.",
      "Time-sliced activation vs load everything then add at once: slicing avoids frame spikes but delays the cell becoming complete, while a bulk add is simple and hitches.",
      "Hysteresis on unload distance: a larger unload radius avoids thrash at the boundary but holds more memory.",
    ],
    p: [
      "Fast travel or a vehicle outrunning storage, so the player falls through ground that has not loaded yet.",
      "Unloading a cell that other objects still refer to, leaving dangling references.",
      "Losing runtime changes to a cell, such as destroyed objects, when it unloads and later reloads from pristine data.",
    ],
    v: "Fly a camera along the worst-case path at maximum speed on the slowest target storage. Frame time stays under budget, no collision gap is ever reached unloaded, and modified objects keep their state after leaving and returning.",
    dep: ["streaming", "spatial-partitioning", "runtime-resource-manager", "job-system", "save-load"],
  },
  "save-load": {
    s: "Captures the state of a game session to persistent storage and restores it, including versioning so older saves keep loading after the game changes.",
    d: "Save games record only what cannot be rebuilt from the shipped data: player progress, object states that differ from their defaults, and world flags. Objects mark which of their properties are saved, and the serializer writes them with stable identifiers rather than memory references so links can be resolved on load. Saves are written atomically to avoid corruption, validated with a checksum, and versioned with migration steps. Restoring means rebuilding the world and then applying saved state, in an order that respects dependencies. Platform storage limits, cloud synchronization and save-anywhere versus checkpoint design shape the system.",
    k: [
      "Snapshot the whole world vs record deltas against defaults: whole snapshots are simple and robust, while deltas are small and survive content changes but depend on stable identifiers.",
      "Save anywhere vs checkpoints: saving anywhere is player-friendly but requires everything to be serializable, while checkpoints constrain state to known safe moments.",
      "Versioned migrations vs invalidate old saves: migrations preserve player progress through patches, but every format change adds code that must be maintained and tested.",
    ],
    p: [
      "Writing directly over the only save file, so a crash or power loss mid-write destroys it.",
      "Saving references by array index or address, which resolve to the wrong objects after content changes.",
      "Never testing loading of saves from older versions, discovering the break after players report lost progress.",
    ],
    v: "Save at ten varied points, quit, reload and compare world state hashes with the pre-save state. Load saves from the previous two released versions, and kill the process mid-write to confirm the previous save still loads.",
    dep: ["serialization", "game-object-model", "reflection-and-types", "virtual-file-system"],
  },
  "gameplay-framework": {
    s: "The set of reusable game-level concepts the engine ships with, such as players, controllers, game modes, rules and match state, giving projects a structure to extend instead of inventing one.",
    d: "On top of the object model, a framework defines roles: who is a player, what possesses and controls a character, where match rules live, and what state is shared with every client versus private. It sets the lifecycle of a match, from lobby to play to results, and how spawning and respawning happen. Because it fixes who owns what, it determines how networking and saving apply to game objects. A good framework is opinionated enough to save work yet leaves clear extension points; a poor one forces every game to fight its assumptions about the genre.",
    k: [
      "Genre-shaped framework vs minimal one: a shooter-oriented set of roles saves time for that genre, while a minimal framework suits any game but leaves more to build.",
      "Separate controller from the controlled body: this lets one player switch characters, spectate or be replaced by AI, at the cost of an extra layer of indirection.",
      "Authoritative rule object on the server vs distributed rules: a single rules owner is simpler to secure and reason about, while distributed rules reduce latency.",
    ],
    p: [
      "Putting match rules in the player character, so spectators, AI and respawns each need special cases.",
      "Storing private data in state that is replicated to all clients, exposing it to anyone inspecting traffic.",
      "Hardcoding the framework for one mode, then having to rewrite it when a second mode is added.",
    ],
    v: "Run a full match lifecycle with players joining, dying, respawning, spectating and an AI taking over a disconnected player. Confirm each transition works, state visibility matches the design, and rules live in one place.",
    dep: ["game-object-model", "replication", "game-loop"],
  },

  "offline-asset-pipeline": {
    s: "Converts source files from artists and designers, such as meshes, textures and audio, into engine-ready intermediate data through importers and processors, with dependency tracking and caching.",
    d: "Source files are authored in many external formats. An importer reads each one into an engine-neutral representation, and processors transform it: generating mipmaps, compressing textures, building collision, simplifying meshes, compiling shaders. Each step records its inputs, tool versions and settings so results can be cached and only rebuilt when something relevant changes. The pipeline runs on build machines in parallel, and a shared cache lets a whole team skip repeated work. Reproducibility matters: the same inputs must always produce the same bytes, or caching and patching both break.",
    k: [
      "Content-hash caching vs timestamps: hashes are reliable across machines and checkouts, while timestamps are cheap but cause false rebuilds and missed changes.",
      "Importers in the editor process vs separate worker processes: separate workers parallelize and isolate crashes, while in-process is simpler to debug and share state with.",
      "Per-platform processing at import vs at cook time: doing it at import front-loads cost and speeds iteration, while delaying to cook avoids storing every platform variant.",
    ],
    p: [
      "Processors that embed timestamps or random seeds, making output non-reproducible and defeating caches and patches.",
      "Not tracking a tool version as an input, so upgrading a compressor leaves stale outputs in the cache.",
      "A single huge source asset that blocks the whole pipeline because its import cannot be split.",
    ],
    v: "Import the same source twice on different machines and compare output hashes; they match. Change one texture setting and confirm only that asset and its dependents rebuild, then wipe the local cache and confirm the shared cache fills it.",
    dep: ["asset-database", "job-system", "reflection-and-types", "serialization"],
  },
  "cooking-and-packaging": {
    s: "Turns processed assets into platform-specific runtime formats and bundles them into archives laid out for fast loading, patching and download.",
    d: "Cooking selects the content a build needs by following references from the shipped levels, converts each asset into the target platform's layout, such as the right texture compression and byte order, and removes editor-only data. Packaging groups the results into archives, ordered by access pattern so assets used together sit together on disk, sometimes with duplication to avoid seeks on slow media. Archives are indexed, optionally compressed and encrypted, and chunked to suit installs and patches. Because the runtime reads exactly this format, the cooker and loader must stay in lockstep, and a missing reference is a runtime crash rather than a build error.",
    k: [
      "Follow references vs explicit manifests: reference tracing includes only what is used and stays correct automatically, while manifests are predictable but go stale.",
      "Duplicate assets across archives vs share them: duplication gives sequential reads and independent chunks at the cost of size, while sharing saves space and may require extra seeks.",
      "Compress per archive vs per asset: per archive compresses better, while per asset allows random access without decompressing neighbors.",
    ],
    p: [
      "Content reachable only through a runtime string lookup that the cooker cannot see, so it is left out and fails in the shipped build.",
      "Cooking assets that differ between runs, causing every release to appear as a full-size patch.",
      "Testing only in the editor with source assets, and discovering cook failures right before release.",
    ],
    v: "Cook a clean build, install it on a target device with no source content, and play every level from a fresh start. No missing-asset errors occur, and a second cook of unchanged content produces byte-identical archives.",
    dep: ["offline-asset-pipeline", "asset-database", "virtual-file-system", "serialization"],
  },
  "asset-database": {
    s: "A registry of every asset with stable identifiers, metadata, and the references between them, so content can be found, moved and traced without breaking links.",
    d: "Each asset gets a persistent unique identifier independent of its file path, so renaming or moving it leaves references intact. The database records type, import settings, tags and the dependency graph in both directions: what an asset uses and what uses it. This answers questions such as what breaks if this is deleted, or which assets does this level need. Editors, the pipeline, the cooker and the runtime all consult it, in different forms. At scale it must be fast to query and merge-friendly under version control, since many people change content at once.",
    k: [
      "Identifier plus sidecar metadata file vs central database: sidecars merge cleanly in version control, while a central database is faster to query but conflicts when many people edit.",
      "Path-based references vs identifiers: paths are readable and need no registry, while identifiers survive moves and renames at the cost of tooling to resolve them.",
      "Hard vs soft references: hard references load dependencies automatically, while soft references defer loading and avoid pulling in large chains of content.",
    ],
    p: [
      "Duplicated identifiers after copying an asset's files outside the editor, so two assets silently collide.",
      "Dependency data that is not updated on every save, so the cooker omits something that is actually used.",
      "Merge conflicts in a single central file blocking several people from submitting content at once.",
    ],
    v: "Rename and move a heavily referenced asset, then open every referencing level and confirm nothing is missing. Query its dependents and compare against a brute-force scan of all files; the two lists match.",
    dep: ["serialization", "reflection-and-types", "virtual-file-system"],
  },
  "runtime-resource-manager": {
    s: "Loads, caches and releases assets at runtime with reference counting and handles, deciding what is in memory so the game can request content without caring where or when it loads.",
    d: "Game code requests an asset by identifier and receives a handle immediately; the manager checks the cache, otherwise schedules an asynchronous load, decode and finalization, and notifies when ready. Reference counts or ownership groups decide when an asset can be evicted, and a memory budget per type triggers eviction of least-recently-used content. It resolves dependencies, such as a material needing textures and shaders, and deduplicates concurrent requests for the same asset. Some resources need creation on specific threads, such as graphics objects, so the manager coordinates thread handoff. It must avoid both stalls and leaks.",
    k: [
      "Reference counting vs explicit scoped groups: counting frees things automatically but can leak through cycles, while groups tied to a level or feature are predictable and coarser.",
      "Synchronous load with a stall vs placeholder then swap: blocking is simple and correct, while placeholders keep the frame smooth but show lower quality briefly.",
      "Per-type memory budgets vs one shared budget: per-type budgets prevent one category starving others, while a shared pool uses memory more flexibly.",
    ],
    p: [
      "Requesting an asset in the middle of a frame with a synchronous load, causing a visible hitch the first time it appears.",
      "Cyclic references that keep each other alive, so memory grows after every level transition.",
      "Releasing an asset that the render thread is still using, because the count dropped on the game thread.",
    ],
    v: "Load and unload levels in a loop one hundred times while recording memory. Usage returns to baseline each time, no request blocks the frame beyond budget, and duplicate concurrent requests produce one load.",
    dep: ["asset-database", "virtual-file-system", "job-system", "memory-allocators"],
  },
  "streaming": {
    s: "Feeds large, high-detail content such as textures, meshes, audio and animation to memory in pieces ahead of need, using prioritized I/O so quality scales with what is actually visible.",
    d: "Instead of loading whole assets, streaming loads the portion required now: texture mip levels based on screen size, mesh levels of detail, or audio chunks just ahead of the playhead. A streaming system estimates need from camera distance, orientation and speed, ranks requests, and issues reads in an order that respects device characteristics, large sequential reads for spinning disks and many parallel small ones for flash. It enforces a memory pool, evicting what is least needed. Latency hiding relies on prediction, so a reasonable fallback, such as a low-resolution mip kept resident, must always exist.",
    k: [
      "Keep a low-resolution tier always resident vs load on demand: always-resident tiers prevent blank or missing content at a fixed memory cost, while on-demand saves memory and risks visible pop-in.",
      "Priority by screen coverage vs distance: coverage reflects what the player sees, while distance is cheaper to compute but misjudges large objects.",
      "Streaming pool of fixed size vs elastic: a fixed pool gives predictable memory, while elastic adapts to scenes but can crowd out other systems.",
    ],
    p: [
      "Fast camera cuts that outrun the streaming window, showing blurry textures for several seconds.",
      "Saturating the I/O queue with low-priority reads so an urgent request waits behind them.",
      "Thrashing: a pool that is slightly too small repeatedly loads and evicts the same content every few frames.",
    ],
    v: "Teleport the camera to a worst-case dense location on the slowest supported storage. Record time until all visible textures reach full resolution, confirm no blank placeholder shows, and the pool never exceeds its budget.",
    dep: ["runtime-resource-manager", "virtual-file-system", "job-system"],
  },
  "virtual-file-system": {
    s: "Presents one uniform namespace of paths over loose files, archives, patches and platform storage, so the rest of the engine reads data without knowing where it physically lives.",
    d: "Game code requests a logical path and the file system resolves it through a prioritized list of mounts: a patch archive overrides the base archive, which overrides loose files on disk during development. It abstracts platform-specific storage rules and asynchronous reads, supports memory mapping or direct reads, decompression and decryption on the fly, and caches directory listings. Reads go through a request queue so that I/O can be scheduled and prioritized. Mod and downloadable content simply add mounts. Correct handling of path case, separators and write locations on every platform is essential.",
    k: [
      "Mount priority overlay vs a merged manifest: overlays make patches and mods trivial to apply, while a merged manifest is faster to look up but must be rebuilt when content changes.",
      "Asynchronous request queue vs blocking reads: queued reads allow prioritization and overlap with computation, while blocking reads are simple but stall the calling thread.",
      "Decompress at read time vs at install: read-time decompression saves disk and bandwidth, while install-time expansion removes runtime CPU cost.",
    ],
    p: [
      "Case-sensitive path mismatches that work on a case-insensitive development machine and fail on another platform.",
      "Writing save or cache files into the read-only install location, which fails on consoles and sandboxed systems.",
      "Mount order mistakes so an old patch shadows newer content without any warning.",
    ],
    v: "Mount a base archive, a patch and a mod containing the same path with different contents. The highest-priority version is returned, removing the patch reverts to the base, and a case-mismatched lookup behaves identically on every platform.",
    dep: ["platform-abstraction", "memory-allocators", "job-system"],
  },
  "hot-reloading": {
    s: "Replaces changed assets, shaders, scripts or code in a running game without restarting, shortening the loop between making a change and seeing its effect.",
    d: "A file watcher detects a modified source, the pipeline reprocesses it, and the resource manager swaps the new data in place while keeping handles valid. Every dependent must be told: materials rebuild when a shader changes, instances pick up a new mesh, scripts rebind. State survives where possible, for example by serializing live objects before reloading code and restoring them afterward. It is a development feature only and must be absent from shipping builds. The difficulty is that every system must tolerate its inputs changing identity or shape mid-run, which is rarely tested otherwise.",
    k: [
      "Swap in place behind a stable handle vs recreate dependents: stable handles make reloads transparent to users, while recreation is simpler but invalidates cached state.",
      "Preserve state across code reload vs restart the level: preserving is faster for iteration but needs serialization of everything, while restarting is reliable and slower.",
      "Watch source files vs watch cooked output: watching source gives immediate feedback with the full pipeline, while watching output matches the shipped data path more closely.",
    ],
    p: [
      "Dangling pointers into old asset memory that was freed on reload, crashing the game only in development.",
      "Reloading a half-written file and loading corrupted data because the watcher fires before the save finishes.",
      "Reload behavior left enabled in shipping builds, adding file watchers and an attack surface.",
    ],
    v: "While the game runs, edit a texture, a shader and a script in turn. Each change appears within a couple of seconds without restart, live object state survives, and an intentionally broken edit reports an error and keeps the previous version.",
    dep: ["runtime-resource-manager", "asset-database", "offline-asset-pipeline", "virtual-file-system"],
  },

  "platform-abstraction": {
    s: "A thin layer over operating system services such as windows, threads, files, timers and memory, so the rest of the engine compiles and behaves the same on every target platform.",
    d: "The abstraction defines the engine's own interfaces for threads and synchronization, file and directory access, dynamic library loading, window and display management, clocks, and system queries such as core count and memory size. Each platform implements them separately, and conditional compilation is confined to this layer. It must expose differences honestly rather than hide them: guaranteed alignment, atomic behavior, path rules and permission models vary. The layer stays small, because every function added must be implemented and tested on every platform, and leaks of platform types into higher code undo the benefit.",
    k: [
      "Narrow interface that exposes lowest common denominator vs rich interface with optional capabilities: narrow is easy to port, while capability queries let the engine use better features where present.",
      "Compile-time platform selection vs runtime dispatch: compile-time has no overhead and dead code disappears, while runtime dispatch allows one binary to adapt.",
      "Wrapping third-party libraries vs using them directly: wrapping allows replacement but adds a layer to maintain.",
    ],
    p: [
      "Platform types or headers leaking into gameplay code, so each new platform requires edits throughout the codebase.",
      "Assuming behavior that differs across targets, such as thread priorities, file locking or timer resolution, and finding out late.",
      "Adding a function used by one platform only, so the others fail to build or implement it incorrectly.",
    ],
    v: "Build the engine for every supported target from the same source and run a shared conformance suite for threads, files, time and windowing. All platforms pass, and a search shows no platform headers included outside this layer.",
    dep: [],
  },
  "app-lifecycle": {
    s: "Manages startup, shutdown, suspend, resume, focus changes and orderly termination, including the system events that mobile and console platforms impose on a running game.",
    d: "At launch it initializes subsystems in dependency order, creates the window and graphics device, loads configuration, and enters the game loop; at exit it tears them down in reverse. Beyond that, platforms send lifecycle events: the app is backgrounded, the display is lost, the device is suspended, memory warnings arrive or a controller disconnects. The engine must pause simulation, release or recreate graphics resources, silence audio, save state in time and resume correctly. Console certification explicitly tests these transitions. Crashes during shutdown and failures to resume are among the most common release blockers.",
    k: [
      "Explicit ordered init and shutdown vs lazy initialization: explicit order is easy to debug and reverse, while lazy initialization starts faster but hides dependencies and surprises.",
      "Save on every suspend vs periodic autosave: saving on suspend loses nothing but may exceed the time the platform allows, while periodic saves bound the work.",
      "Release graphics resources on background vs keep them: releasing frees memory for the system but requires recreating everything on return.",
    ],
    p: [
      "Doing long work in the suspend handler and being terminated by the platform before the save completes.",
      "Resuming with a lost graphics device and continuing to draw with invalid resources, producing black frames or crashes.",
      "Shutdown order mistakes where a subsystem uses another that has already been destroyed.",
    ],
    v: "Repeatedly background and resume the app, switch focus, disconnect the display and trigger a low-memory warning in a scripted run. The game pauses, resumes to a correct frame each time, and a forced quit leaves valid saved data.",
    dep: ["platform-abstraction", "events-and-messaging", "logging-and-assertions"],
  },
  "memory-allocators": {
    s: "Custom allocation strategies such as arenas, pools and frame allocators that replace general-purpose allocation to cut fragmentation, hitches and cache misses, and to track where memory goes.",
    d: "General allocators are slow under contention and fragment over long sessions, which is unacceptable on fixed-memory hardware. Engines instead layer allocators by lifetime and size: per-frame linear arenas reset in one step, pools for fixed-size objects, stacks for scoped data, and a general heap for the rest. Every allocation is tagged with a category so budgets can be enforced and leaks attributed. Thread-local caches reduce locking. Debug builds add guard bytes, poisoning and leak reports. Choosing allocators by lifetime, not by type, is what makes the system effective and keeps cleanup trivial.",
    k: [
      "Lifetime-based arenas vs per-object allocation: arenas are extremely fast and free everything at once, but prohibit freeing individual objects early.",
      "Thread-local pools vs a shared pool with locks: thread-local avoids contention but can strand memory in idle threads, while shared pools balance memory at the cost of synchronization.",
      "Fixed memory budgets per category vs a single pool: budgets catch growth early and are required on fixed-memory hardware, while a single pool is flexible but hides who is consuming memory.",
    ],
    p: [
      "Storing a pointer into a frame allocator beyond the frame, which then reads overwritten data intermittently.",
      "Fragmentation of the general heap over hours of play, so a large allocation fails despite plenty of total free memory.",
      "Allocator statistics that are not thread-safe, giving wrong numbers exactly when debugging concurrency problems.",
    ],
    v: "Run a soak test for several hours with level changes. Per-category memory returns to baseline, largest free block does not shrink over time, and debug guard bytes report no overruns or use after reset.",
    dep: ["platform-abstraction"],
  },
  "containers-and-utilities": {
    s: "The engine's own collections, strings, handles and helper types, designed around allocator control, predictable performance, debuggability and cache-friendly layout rather than convenience.",
    d: "Standard containers often allocate unpredictably, hide costs and behave differently across platforms, so engines supply their own: dynamic arrays and hash maps that accept an allocator, fixed-capacity variants for hot paths, intrusive lists, ring buffers, small-buffer strings and interned names that compare as integers. They give stable iteration, explicit growth policies and diagnostic hooks. Utilities include smart handles, optional values, spans and bit sets. The aim is not novelty but control: knowing exactly when memory is allocated and what each operation costs, and making iteration order identical everywhere for determinism.",
    k: [
      "Own containers vs the language's standard ones: custom ones give allocator control and consistent behavior on every platform, while standard ones are familiar, maintained and well tested.",
      "Open addressing vs chained hash tables: open addressing is cache-friendly and compact, but degrades at high load and makes removal more delicate.",
      "Interned names vs raw strings for identifiers: interning makes comparison and hashing trivial, but needs a global table and careful lifetime and thread handling.",
    ],
    p: [
      "Iterating a hash map in memory-address order, which changes between runs and breaks determinism and replays.",
      "Growing a dynamic array during the frame and triggering a reallocation that invalidates pointers held elsewhere.",
      "Copying strings and containers by value in hot code because a missing move or reference type makes it implicit.",
    ],
    v: "Run randomized tests comparing each container against a trusted reference model across millions of operations, with allocation counting enabled. Results match, no operation allocates unexpectedly, and iteration order is identical across platforms and runs.",
    dep: ["memory-allocators", "platform-abstraction"],
  },
  "math-library": {
    s: "Vectors, matrices, quaternions, geometric primitives and numeric helpers with consistent conventions and vectorized implementations, used by every system that touches space.",
    d: "The library fixes the conventions everything else relies on: coordinate handedness, which axis is up, row or column vectors, rotation order and units. It provides vector and matrix types, quaternions for rotation, bounding volumes, rays, planes, interpolation and easing, random number generators and numeric tolerances. Hot operations use SIMD instructions, which requires alignment and batch-friendly layouts. Correctness subtleties include normalizing quaternions after repeated multiplication, comparing floats with tolerances, and handling degenerate inputs without producing NaN, which then spreads through the world and is hard to trace.",
    k: [
      "Fixed global conventions vs per-API conversion: one convention everywhere is simple and fast, while converting at the boundary to each graphics or physics API isolates their differences.",
      "SIMD-wide types vs scalar types with batch routines: wide types are quick to adopt but complicate layout, while batch routines over arrays vectorize better in hot loops.",
      "Quaternions vs matrices for rotation storage: quaternions interpolate well and are compact, while matrices compose with scale and translation directly.",
    ],
    p: [
      "Mixing handedness or matrix multiplication order between modules, producing mirrored or inside-out results that look nearly right.",
      "Unnormalized quaternions accumulating error over time, causing slow skew in rotations.",
      "NaN or infinity from normalizing a zero-length vector propagating through transforms and silently making objects vanish.",
    ],
    v: "Run property tests: rotation then inverse returns the original, matrix and quaternion paths agree within tolerance, SIMD and scalar results match, and degenerate inputs such as zero vectors produce defined outputs rather than NaN.",
    dep: ["platform-abstraction"],
  },
  "logging-and-assertions": {
    s: "Structured, filterable logging and assertion macros that report what the engine is doing and fail loudly and informatively when an invariant is violated.",
    d: "Logging provides severity levels, categories and sinks: console, files, an in-game overlay, a remote collector. Messages are cheap when disabled, thread-safe, timestamped and carry frame numbers so they can be correlated with captures. Assertions check invariants in development and may compile out in shipping builds, while a separate class of checks always remains and reports through crash handling. A failed assertion should capture a call stack and context, then halt, not continue in a corrupted state. The skill is choosing what to log: enough to diagnose problems without flooding output or costing frame time.",
    k: [
      "Assertions compiled out in shipping vs always on: compiling out removes cost, while always-on checks catch real-world corruption early at some performance price.",
      "Synchronous vs asynchronous log writing: synchronous logs survive a crash but add latency, while asynchronous ones are cheap and can lose the final lines before a crash.",
      "Category verbosity controlled at runtime vs compile time: runtime control allows diagnosing a live build, while compile-time removal costs nothing and cannot be enabled later.",
    ],
    p: [
      "Logging in a hot loop with string formatting performed even when the category is disabled, costing milliseconds per frame.",
      "Treating an assertion as error handling and relying on it for conditions that can occur with valid but unusual input in shipping.",
      "Logs without frame or thread information, so lines from different threads cannot be ordered.",
    ],
    v: "Trigger a deliberate assertion failure in a development build and confirm it halts with file, line, call stack and recent log context. Disable a noisy category and confirm measured frame time does not change.",
    dep: ["platform-abstraction", "time-system"],
  },
  "config-and-console-variables": {
    s: "Layered settings and named runtime variables that tune engine and game behavior from files, command lines and a live console without recompiling.",
    d: "Configuration resolves values through layers: engine defaults, platform overrides, project settings, user files and command-line arguments, with later layers winning. Console variables are typed, named values registered by code with a description, range and flags such as cheat-only, read-only or saved. They can be changed at runtime from a console, scripts or the editor, and observers react to changes. This is the primary tool for tuning, for scalability settings and for turning features off when diagnosing. Needed rigor includes validation, documented defaults and keeping debug-only variables out of shipping behavior.",
    k: [
      "Layered overrides vs a single settings file: layers allow platform and user customization without editing shared files, while a single file is easier to understand and diff.",
      "Register variables in code vs declare them in data: code registration keeps type and default next to usage, while data declaration lets tools list and validate without running the engine.",
      "Apply change immediately vs on restart: immediate application is convenient for tuning, but some settings, such as graphics device options, cannot be changed safely live.",
    ],
    p: [
      "A tuning variable left changed in a saved user file, so the player experiences unintended behavior long after developers forgot it.",
      "Cheat or debug variables writable in shipping builds, giving players a way to alter game rules.",
      "Reading a variable once at startup when the design promised live changes, so tuning silently has no effect.",
    ],
    v: "Set the same variable in defaults, platform file, user file and command line, and confirm the command-line value wins and is reported in a dump of sources. Change a live variable from the console and observe the effect on the next frame.",
    dep: ["reflection-and-types", "serialization", "virtual-file-system", "platform-abstraction"],
  },
  "time-system": {
    s: "Provides monotonic real time, game time with pause and scaling, and fixed-step accumulation, keeping simulation consistent across frame rates and clock quirks.",
    d: "Several clocks are needed: a monotonic wall clock for measuring, a game clock that stops when paused and runs faster or slower for slow motion, and a simulation clock that advances in fixed increments. Frame time is smoothed or clamped to hide spikes and debugger pauses. The system converts between units without drift by using integer ticks rather than accumulated floating point seconds. It supplies timestamps to input, networking and audio, and synchronization between them depends on a shared understanding of time. The common mistake is mixing clocks, such as using paused game time for something that should keep running.",
    k: [
      "Integer ticks vs floating point seconds: integers never drift and compare exactly, while floats are convenient but lose precision over long sessions.",
      "Clamp the frame delta vs pass it through: clamping avoids huge steps after hitches or breakpoints but makes game time fall behind real time.",
      "Separate clocks for UI, gameplay and audio: separate clocks let menus animate while paused, but increase the chance of using the wrong one.",
    ],
    p: [
      "Using wall-clock time for a cooldown that should freeze when the game is paused, so abilities recharge in the pause menu.",
      "Floating point time stored in seconds, losing millisecond precision after hours of uptime and producing jitter.",
      "Trusting a clock that can jump backward, such as the system date, to measure durations.",
    ],
    v: "Run for twelve hours of accelerated time and confirm timestamps still resolve to under a millisecond. Pause and slow the game and verify cooldowns, animation and audio each follow the clock they should, while the UI keeps animating.",
    dep: ["platform-abstraction"],
  },
  "job-system": {
    s: "A pool of worker threads that runs small tasks with declared dependencies, letting every subsystem spread its work across all cores without managing threads itself.",
    d: "Work is split into jobs, each a small function with its data, submitted to a scheduler that distributes them across a fixed number of workers, usually one per core minus reserved threads. Dependencies are expressed as counters or graph edges, and a waiting thread runs other jobs rather than blocking. Work-stealing queues balance load. Higher-level helpers provide parallel-for loops and fork-join patterns. The system defines what is safe to run concurrently, so data ownership rules must be explicit. Priorities and affinity let latency-sensitive work, such as audio, avoid being delayed by bulk work.",
    k: [
      "Work stealing vs a shared queue: stealing scales across many cores with less contention, while a single queue is simpler to reason about and to profile.",
      "Fibers or continuations vs blocking waits: fibers let a job wait without tying up a worker, but add complexity and platform-specific code, while blocking waits are simple and risk starvation.",
      "Fine-grained jobs vs coarse chunks: fine jobs balance load better but pay scheduling overhead, while coarse ones are cheaper and may leave cores idle.",
    ],
    p: [
      "Jobs that block waiting on other jobs, which deadlocks the pool once every worker is waiting.",
      "Two jobs touching the same data without a declared dependency, causing rare corruption that disappears under a debugger.",
      "Jobs so small that scheduling cost exceeds the work, making the parallel version slower than the serial one.",
    ],
    v: "Run a benchmark of parallel-for work on one to all cores: speedup scales near-linearly until memory bandwidth limits it. Run a stress test with thread sanitizer enabled and randomized scheduling; no races or deadlocks are reported.",
    dep: ["platform-abstraction", "memory-allocators", "threading-model"],
  },
  "reflection-and-types": {
    s: "Runtime description of types, fields and functions that lets generic code inspect, edit, copy, serialize and replicate objects without hand-written code for each type.",
    d: "A registry holds metadata for each type: name, base types, fields with their type, offset and attributes such as display name, range or whether it is saved or replicated, and callable functions. It is produced by code generation, macros or a build-time parser. Once available, the editor inspector, serialization, networking, scripting bindings, undo and diffing are all generic, driven by metadata. It supports creating objects by type name and safe casting. It is the keystone of tooling: adding one field in code makes it appear in the editor, save to disk and replicate. Costs are build complexity and memory for metadata.",
    k: [
      "Generated metadata vs hand-registered: generation cannot go stale and removes boilerplate, while manual registration needs no extra build step and is explicit.",
      "Reflect everything vs opt-in attributes: reflecting everything is convenient, while opt-in keeps metadata small and prevents exposing internal state to tools and the network.",
      "Stable type identifiers vs names or hashes: stable identifiers survive renames in saved data, while names are readable and need migration when types change.",
    ],
    p: [
      "Renaming a field or type without a migration, silently dropping saved data in every existing asset and save game.",
      "Metadata that disagrees with the real layout after a code change because it was not regenerated.",
      "Reflecting pointers and references without lifetime information, so generic copy code creates shared ownership bugs.",
    ],
    v: "Add a field with attributes to a type, rebuild, and confirm it appears in the inspector, round-trips through save and load, replicates, and undoes. Rename it with a migration and check old data still loads.",
    dep: ["memory-allocators", "containers-and-utilities"],
  },
  "serialization": {
    s: "Converts objects to bytes and back for assets, saves, networking and undo, using type metadata and a versioned format that tolerates added, removed and renamed fields.",
    d: "A serializer walks an object's reflected fields and writes them to a stream, with the same code path used for reading, to prevent the two diverging. Formats range from human-readable text for diffable source assets to compact binary for cooked data and the network. Version tags and field identifiers allow old data to load after fields change; unknown fields are skipped or preserved. References are written as stable identifiers and patched after loading. Binary formats consider alignment, endianness and zero-copy loading, where data can be used directly from the loaded buffer without parsing, which is the fastest option.",
    k: [
      "Text for source and binary for cooked data: text is mergeable and diffable under version control, while binary is smaller and loads faster.",
      "Tagged fields vs positional layout: tagged fields tolerate change in both directions, while positional layouts are smaller and faster but break on any layout change.",
      "Zero-copy loading vs parse into objects: zero-copy is near-instant and memory-efficient, but ties the data layout to the in-memory layout and pointer fixups.",
    ],
    p: [
      "Separate read and write functions that drift apart, so a field added to one is missing from the other and data silently corrupts.",
      "Platform-dependent layout such as struct padding or byte order leaking into files and breaking cross-platform builds.",
      "Deserializing untrusted data, such as a save or a network message, without bounds checks, enabling crashes and exploits.",
    ],
    v: "Round-trip a large corpus of objects through each format and compare results field by field. Load files written by three previous format versions, and feed truncated and fuzzed input; the loader rejects it without crashing.",
    dep: ["reflection-and-types", "memory-allocators", "containers-and-utilities"],
  },
  "events-and-messaging": {
    s: "Decoupled communication between systems through events, delegates and message queues, so one component can announce something without knowing who listens.",
    d: "Mechanisms include immediate callbacks, queued events delivered at a defined point in the frame, and broadcast channels that subscribers join by topic or type. Immediate delivery is simple but can reenter code in the middle of an update; queued delivery is predictable and thread-friendly but adds latency of a frame. Subscriptions need explicit lifetimes so a destroyed listener is never called. The system fixes ordering guarantees and what happens when a handler raises more events. Used well it keeps subsystems independent; used carelessly it becomes hidden control flow that is hard to trace and debug.",
    k: [
      "Immediate callbacks vs queued delivery: immediate is simple and has no delay but allows reentrancy, while queued gives deterministic ordering and thread safety at the cost of a frame of latency.",
      "Typed channels vs string-named events: typed channels catch mistakes at build time and are fast, while string names allow loose coupling and scripting at the cost of runtime errors.",
      "Subscriptions with automatic lifetime vs manual unsubscribe: automatic cleanup prevents calling dead listeners, while manual is cheaper and a common source of leaks.",
    ],
    p: [
      "A listener destroyed without unsubscribing, so the next event calls freed memory.",
      "An event handler that raises another event that comes back to it, producing infinite recursion or reordering.",
      "Using events for everything, until nobody can answer which code runs when something happens.",
    ],
    v: "Subscribe and destroy a thousand listeners in random order while events fire. No dead listener is called, ordering matches the documented guarantee, and a trace of a single event lists every handler it reached.",
    dep: ["memory-allocators", "containers-and-utilities"],
  },
  "profiling-hooks": {
    s: "Lightweight instrumentation points in engine and game code that record timing, counters and memory events with negligible cost, feeding the profilers that display them.",
    d: "Scoped markers mark the start and end of regions, with names, categories and optional data. Each thread writes to its own preallocated buffer with a cheap timestamp, so recording does not synchronize threads or allocate. Counters track values such as draw calls or active objects per frame; markers can also appear on the graphics and audio side. Data is exported live over a socket or to a capture file for offline analysis. Hooks can be compiled out, filtered by category or enabled at runtime. The key requirement is that measuring must not change what is measured.",
    k: [
      "Instrumentation vs sampling: instrumentation gives exact scopes and call counts but costs time per marker, while sampling is nearly free and gives statistical, less precise results.",
      "Always compiled in vs build option: always-on lets you profile real shipping builds, at a small constant cost, while a build option has zero cost and requires a special build.",
      "Per-thread buffers vs a shared ring: per-thread buffers avoid contention but need merging by timestamp, while a shared ring is simple and becomes a bottleneck.",
    ],
    p: [
      "Markers placed inside tiny functions called millions of times, so the overhead dominates and distorts the profile.",
      "Timestamps from different threads or the graphics device that are not aligned, so the timeline shows impossible orderings.",
      "Allocating memory to store samples, adding the very costs and stalls being investigated.",
    ],
    v: "Measure frame time with hooks compiled out, on but idle, and actively recording. Overhead when idle is negligible and recording stays within a stated budget. Capture a known sleep of 5 ms and confirm it shows as 5 ms.",
    dep: ["time-system", "platform-abstraction", "memory-allocators"],
  },
});
