// Writes a page for every plate in the catalog and the manifest of which plates are drawn.
// Run after adding or removing a plate's files: node tools/build.mjs
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const root = path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/, "$1")), "..");
const ctx = vm.createContext({ window: {} });
vm.runInContext(fs.readFileSync(path.join(root, "assets/catalog.js"), "utf8"), ctx);
const catalog = ctx.window.ATLAS_CATALOG;

const FONTS = "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT@0,9..144,300..700,0..100;1,9..144,300..600,0..100&family=Geist:wght@400..600&family=Geist+Mono:wght@400..500&display=swap";
const esc = s => s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const head = (title, desc, rel) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<script>try{var t=localStorage.getItem("atlas-theme");if(t)document.documentElement.dataset.theme=t}catch(e){}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="${FONTS}">
<link rel="stylesheet" href="${rel}assets/atlas.css">
<link rel="icon" href="${rel}assets/favicon.svg" type="image/svg+xml">
</head>
<body>
<div id="app"></div>
<script src="${rel}assets/atlas.js"></script>
<script src="${rel}assets/catalog.js"></script>
<script src="${rel}assets/manifest.js"></script>
<script src="${rel}assets/chart.js"></script>
<script src="${rel}assets/site.js"></script>
`;

const manifest = {};
let pages = 0;
for (const d of catalog) for (const [slug, name, blurb] of d.entries) {
  const dir = path.join(root, "atlas", slug);
  fs.mkdirSync(dir, { recursive: true });
  const files = fs.readdirSync(dir).filter(f => /^(data|details.*)\.js$/.test(f))
    .sort((a, b) => (a === "data.js" ? -1 : b === "data.js" ? 1 : a.localeCompare(b)));
  if (files.includes("data.js")) manifest[slug] = files;
  fs.writeFileSync(path.join(dir, "index.html"),
    head(`${name} · Architecture Atlas`, `${name}: ${blurb}. A layered architecture map.`, "../../") +
    `<script>AtlasPlate.boot(${JSON.stringify(slug)}, "../../")</script>\n</body>\n</html>\n`);
  pages++;
}
fs.writeFileSync(path.join(root, "index.html"),
  head("Architecture Atlas", "Plates of how software is built: layered architecture maps of operating systems, compilers, browsers, databases, game engines and more, for agentic engineers.", "") +
  `<script>AtlasHome.boot("")</script>\n</body>\n</html>\n`);
fs.writeFileSync(path.join(root, "assets/manifest.js"),
  "// Generated by tools/build.mjs: the data files of every drawn plate.\nwindow.ATLAS_MANIFEST = " + JSON.stringify(manifest, null, 2) + ";\n");
console.log(`${pages} plate pages, ${Object.keys(manifest).length} drawn: ${Object.keys(manifest).join(", ")}`);
