// Plate: Web browser. Structure only; per-component entries live in details*.js.
ATLAS.register({
  slug: "web-browser",
  title: "Web Browser",
  lede: "Every component of a complete modern multi-process web browser, arranged by layer. A minimal browser keeps navigation, networking, the page runtime and the process model, and can drop sync, extensions, DRM and most of the tooling.",
  ground: ["Operating system","Graphics drivers","Network stack & sockets","Audio and video hardware","Platform accessibility services"],
  crossIntro: "A browser runs code from strangers next to the user's bank session, so several decisions cut across every layer. Where the trust boundary sits, what keeps input responsive, how memory is reclaimed and how old pages keep working constrain each component, and none of them lives in a single box.",
  cross: [
    { id: "security-boundaries", n: "Security boundaries" },
    { id: "responsiveness", n: "Responsiveness" },
    { id: "memory-pressure", n: "Memory pressure" },
    { id: "web-compatibility", n: "Web compatibility" },
    { id: "privacy", n: "Privacy" },
    { id: "power-efficiency", n: "Power efficiency" },
  ],
  bands: [
    { label: "Browser product", groups: ["shell","services","ext","devtools"],
      intro: "Everything the user sees around the page and everything that keeps the browser alive between sessions: the chrome, accounts, updates, extensions and the tools developers use to inspect pages." },
    { label: "Navigation & presentation", groups: ["nav","access"],
      intro: "How a typed address becomes a committed page and a history entry, and how that page is made usable through assistive technology, find, printing and documents." },
    { label: "Page runtime", groups: ["render","script","webapi","media"],
      intro: "The content a page actually runs: the pipeline from markup to pixels, the script engine, the platform APIs scripts call, and media playback. Each page runs this stack inside a sandboxed renderer." },
    { label: "Process & security architecture", groups: ["proc","sec"],
      intro: "The privileged browser process, the sandboxed processes around it, the messages between them, and the policies that decide what content from one origin may do to content from another." },
    { label: "Network & storage", groups: ["net","store"],
      intro: "How bytes arrive and how state persists. Both are owned by trusted processes, so a compromised renderer must ask for resources rather than reach them directly." },
    { label: "Foundation", groups: ["found"],
      intro: "The portable base the browser is built on: threading, platform abstraction, graphics backends, text libraries and tracing, so the layers above run on many operating systems." },
  ],
  groups: {
    shell: { title: "Browser UI shell", color: 13,
      about: "The browser's own interface, drawn outside the page. It runs in the privileged process, owns the tab strip, address bar and settings, and must stay responsive even while a page is hung.",
      items: [
        { id: "tab-and-window-manager", n: "Tabs & windows" },
        { id: "omnibox", n: "Address bar & omnibox" },
        { id: "bookmarks", n: "Bookmarks" },
        { id: "history-store", n: "History" },
        { id: "download-manager", n: "Download manager" },
        { id: "settings-and-policies", n: "Settings & policies" },
        { id: "passwords-and-autofill", n: "Passwords & autofill" },
        { id: "browser-ui-toolkit", n: "Browser UI toolkit" },
      ] },
    services: { title: "Accounts, updates & telemetry", color: 15, optional: true,
      about: "Services that run around the browsing session. They sign users in, replicate their data across devices, keep the code patched, and report crashes and measurements so the vendor can find regressions.",
      items: [
        { id: "accounts-and-sync", n: "Accounts & sync" },
        { id: "auto-updater", n: "Auto-updater" },
        { id: "crash-reporter", n: "Crash reporting" },
        { id: "field-trials-and-metrics", n: "Field trials & metrics" },
      ] },
    ext: { title: "Extensions", color: 14, optional: true,
      about: "Third-party code that extends the browser itself. Extensions get privileged APIs and the ability to modify pages and requests, so the permission model matters more than the loader.",
      items: [
        { id: "extension-loader", n: "Extension manifest & loader" },
        { id: "extension-apis", n: "Extension APIs & scripts" },
        { id: "extension-permissions", n: "Extension permissions" },
      ] },
    devtools: { title: "Developer tools", color: 12, optional: true,
      about: "Tools that inspect and drive a live page. They attach through a debugging protocol, so the same interface serves the built-in panels, remote devices and automation.",
      items: [
        { id: "devtools-frontend", n: "DevTools front end" },
        { id: "devtools-protocol", n: "DevTools protocol" },
        { id: "dom-and-style-inspector", n: "DOM & style inspector" },
        { id: "script-debugger", n: "Script debugger" },
        { id: "performance-tracing", n: "Performance tracing" },
      ] },
    nav: { title: "Navigation & session", color: 9,
      about: "Navigation turns an address into a document in a frame: decide which process loads it, fetch it, commit it, and record it in history. It spans the browser and renderer processes and can be cancelled at many points.",
      items: [
        { id: "navigation-controller", n: "Navigation controller" },
        { id: "session-history", n: "Session history" },
        { id: "url-and-scheme-handling", n: "URLs & scheme handlers" },
        { id: "navigation-throttles", n: "Redirects & navigation checks" },
        { id: "prefetch-and-prerender", n: "Prefetch & prerender" },
        { id: "back-forward-cache", n: "Back/forward cache" },
        { id: "frame-tree", n: "Frame tree & site instances" },
        { id: "page-lifecycle", n: "Page lifecycle & discarding" },
      ] },
    access: { title: "Accessibility, find & documents", color: 8,
      about: "Features that make content usable beyond the visual page: an accessibility tree for assistive technology, keyboard focus, find, printing and a built-in document viewer.",
      items: [
        { id: "accessibility-tree", n: "Accessibility tree" },
        { id: "platform-a11y-bridge", n: "Platform accessibility APIs" },
        { id: "keyboard-navigation", n: "Focus & keyboard navigation" },
        { id: "find-in-page", n: "Find in page" },
        { id: "print-pipeline", n: "Printing" },
        { id: "pdf-viewer", n: "PDF viewer" },
      ] },
    render: { title: "Rendering pipeline", color: 4,
      about: "The stages that turn markup, styles and input into frames. Main-thread stages build and lay out a tree, then a compositor assembles layers on its own thread so scrolling stays smooth even when script is busy.",
      items: [
        { id: "html-parser", n: "HTML parser" },
        { id: "dom-tree", n: "DOM tree" },
        { id: "css-and-style", n: "CSS parsing & style resolution" },
        { id: "layout", n: "Layout" },
        { id: "text-and-fonts", n: "Text shaping & fonts" },
        { id: "paint", n: "Paint & display lists" },
        { id: "compositing", n: "Layers & compositing" },
        { id: "rasterization", n: "Rasterization" },
        { id: "scroll-and-animation", n: "Scrolling & animation" },
        { id: "input-routing", n: "Input routing & hit testing" },
        { id: "frame-scheduler", n: "Frame scheduler" },
      ] },
    script: { title: "Script engine", color: 10,
      about: "The JavaScript and WebAssembly runtime embedded in each renderer. It starts code quickly in an interpreter, recompiles hot code with optimizing tiers and reclaims memory concurrently, all without freezing the page.",
      items: [
        { id: "js-parser", n: "Parser & bytecode generator" },
        { id: "bytecode-interpreter", n: "Bytecode interpreter" },
        { id: "jit-tiers", n: "JIT compiler tiers" },
        { id: "object-model-and-ics", n: "Object model & inline caches" },
        { id: "garbage-collector", n: "Garbage collector" },
        { id: "event-loop", n: "Event loop & microtasks" },
        { id: "webassembly-runtime", n: "WebAssembly runtime" },
        { id: "code-cache", n: "Code cache & streaming compile" },
      ] },
    webapi: { title: "Web platform APIs", color: 5,
      about: "The surface pages program against. Each API is specified as an interface, bound to the script engine, and implemented partly in the renderer and partly in a privileged process that enforces policy.",
      items: [
        { id: "web-idl-bindings", n: "Web IDL bindings" },
        { id: "fetch-api", n: "Fetch & XHR" },
        { id: "web-workers", n: "Workers" },
        { id: "websocket-api", n: "WebSockets" },
        { id: "webrtc", n: "WebRTC" },
        { id: "canvas-2d", n: "Canvas 2D" },
        { id: "gpu-graphics-apis", n: "WebGL & WebGPU" },
        { id: "device-apis", n: "Sensors & device APIs" },
        { id: "notifications-and-push", n: "Notifications & push" },
        { id: "shadow-dom-components", n: "Shadow DOM & custom elements" },
      ] },
    media: { title: "Media", color: 7, optional: true,
      about: "Audio and video playback and processing. Demuxing, decoding and rendering run as a pipeline with a master clock, usually using hardware decoders and, for protected content, a separately sandboxed decryption module.",
      items: [
        { id: "media-demuxers", n: "Containers & demuxers" },
        { id: "media-decoders", n: "Audio/video decoders" },
        { id: "playback-pipeline", n: "Playback pipeline & A/V sync" },
        { id: "media-source-extensions", n: "Media Source Extensions" },
        { id: "drm-module", n: "DRM module" },
        { id: "audio-output", n: "Audio output" },
      ] },
    proc: { title: "Process model & IPC", color: 3,
      about: "One privileged process coordinates many unprivileged ones. Splitting work by function and by site limits what any single compromise or crash can reach, at the price of memory and message-passing overhead.",
      items: [
        { id: "browser-process", n: "Browser process" },
        { id: "renderer-process", n: "Renderer process" },
        { id: "gpu-process", n: "GPU process" },
        { id: "network-process", n: "Network service process" },
        { id: "utility-processes", n: "Utility processes" },
        { id: "site-isolation", n: "Site isolation" },
        { id: "process-allocation", n: "Process allocation policy" },
        { id: "ipc-channel", n: "IPC channels & interfaces" },
      ] },
    sec: { title: "Security & sandboxing", color: 6,
      about: "Layers of policy that let untrusted pages run. Origin rules and headers constrain what content may do, certificates and reputation checks decide whom to trust, and the OS sandbox limits damage if all of that fails.",
      items: [
        { id: "same-origin-policy", n: "Same-origin policy" },
        { id: "cors", n: "CORS" },
        { id: "content-security-policy", n: "Content security policy" },
        { id: "permissions-model", n: "Permissions model" },
        { id: "safe-browsing", n: "Safe browsing" },
        { id: "certificate-validation", n: "Certificate validation" },
        { id: "os-sandbox", n: "OS sandbox" },
        { id: "cross-origin-isolation", n: "Cross-origin isolation" },
        { id: "security-indicators", n: "Security UI & interstitials" },
      ] },
    net: { title: "Networking", color: 11,
      about: "A network service owns every socket. It resolves names, reuses connections, negotiates encryption, multiplexes requests, caches responses and applies policy before any byte reaches a renderer.",
      items: [
        { id: "resource-loader", n: "Resource loader & priorities" },
        { id: "dns-resolver", n: "DNS resolver" },
        { id: "connection-pool", n: "Connection pooling" },
        { id: "http1-codec", n: "HTTP/1.1" },
        { id: "http2-multiplexing", n: "HTTP/2" },
        { id: "http3-quic", n: "HTTP/3 & QUIC" },
        { id: "tls-stack", n: "TLS & HSTS" },
        { id: "http-cache", n: "HTTP cache" },
        { id: "proxy-and-pac", n: "Proxies & PAC" },
        { id: "service-workers", n: "Service workers" },
      ] },
    store: { title: "Storage", color: 2,
      about: "Per-site and per-profile persistence. Each storage API has its own data model, but all share a quota manager, partitioning rules and a profile directory on disk that must survive crashes and upgrades.",
      items: [
        { id: "cookie-jar", n: "Cookie jar" },
        { id: "web-storage", n: "Local & session storage" },
        { id: "indexed-database", n: "IndexedDB" },
        { id: "cache-storage", n: "Cache storage" },
        { id: "quota-and-eviction", n: "Quota & eviction" },
        { id: "storage-partitioning", n: "Storage partitioning" },
        { id: "profile-data-store", n: "Profile data store" },
      ] },
    found: { title: "Platform & foundation", color: 1,
      about: "Portable infrastructure under every process: threads and task scheduling, operating system abstraction, graphics and text libraries and low-overhead tracing. A browser is as portable as this layer.",
      items: [
        { id: "task-scheduler", n: "Threads & task scheduler" },
        { id: "platform-abstraction", n: "Platform abstraction" },
        { id: "native-windowing", n: "Native windows & input events" },
        { id: "graphics-backend", n: "Graphics API backend" },
        { id: "text-and-intl-libs", n: "Text & i18n libraries" },
        { id: "tracing-and-metrics", n: "Tracing & metrics core" },
      ] },
  },
});
